### ISSUE TITLE
Realloc of aligned memory

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#108]
What, if any, alignment requirements are there in a call to ```shmem_realloc``` when the input buffer was allocated using ```shmem_align```?  The ```posix_memalign``` function has the following caveat, should SHMEM also have it?

> memory that is allocated via posix_memalign() can be used as an argument in subsequent calls to realloc(3), reallocf(3), and free(3). (Note however, that the allocation returned by realloc(3) or reallocf(3) is not guaranteed to preserve the original alignment).

**Comment by swpoole** [comment]
I will check from some users and see if this will have any impact either way. If we can follow posix as much as possible, that would be of value. I am not sure if you would ever program "to" the note in the aforementioned post. i.e. not guarenteeing to preserve the original alignment.

**Comment by jdinan** [comment]
This semantic does make the realloc call risky for some usage models.  If you are working with an array of integers, you are probably assuming you can always call shmem_int_put (or worse, C11 shmem_put will make this assumption for you).  After a call to realloc on the given buffer, this assumption could be broken.  I suppose this is not worse than realloc of a buffer in private memory, but it's almost always the case that a SHMEM buffer will be used in a operation that requires alignment.

**Comment by nspark** [comment]
@jdinan Under POSIX, a call to `realloc` will not return memory that would be unsuitably aligned for use as an array of integers. The [relevant excerpt](http://pubs.opengroup.org/onlinepubs/9699919799/functions/realloc.html) says (emphasis mine):
> The pointer returned if the allocation succeeds **shall be suitably aligned so that it may be assigned to a pointer to any type of object** and then used to access such an object in the space allocated (until the space is explicitly freed or reallocated).

I agree that `shmem_realloc` does not make this guarantee explicit.

**Comment by jdinan** [comment]
Reviving this thread -- @nspark, IIUC `posix_memalign` can be used to allocate memory that is aligned to a unit that is greater than the size of any basic object (e.g. cache line, page, etc.).  In POSIX, calling `realloc` on such a buffer is not guaranteed to maintain the original alignment [1].  Are we ok with the same semantic in SHMEM?

[1] https://stackoverflow.com/questions/9078259/does-realloc-keep-the-memory-alignment-of-posix-memalign

**Comment by nspark** [comment]
Yes, I'm okay saying that `shmem_realloc` on an allocation provided by `shmem_align` does not necessarily preserve the original alignment.

**Comment by jdinan** [comment]
@nspark Ok, no semantic change needed.  Do you want to include a warning to the effect that calling `shmem_realloc` on a buffer allocated using `shmem_align` may not preserve the alignment of the original buffer?

**Comment by nspark** [comment]
Yes, I think the _Notes_ section for `shmem_realloc` would be a fair place to add that.

**Comment by jdinan** [comment]
Closed by #201
