### ISSUE TITLE
Realloc of memory allocated with calloc

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#109]
Semantic of shmem_realloc on a buffer that was allocated using shmem_calloc is unspecified. 
 Unix realloc has the following semantic:

>  When extending a region allocated with calloc(3), realloc(3) does not guarantee that the additional memory is also zero-filled.

**Comment by jdinan** [comment]
@nspark, ```shmem_calloc``` is new in 1.4, so it should be fair game to clarify this through the section committee (since part of our job is integration of new changes).  Would you be ok with the text above?

**Comment by nspark** [comment]
That seems reasonable to me.

**Comment by swpoole** [comment]
As long as we do not diverge from the "normal" I agree. The initial call to calloc, does imply zero filled I assume.

**Comment by jdinan** [comment]
@nspark, please review the text added in edd26632.

**Comment by nspark** [comment]
After a little more thought, I don't think we need this change. The preceding sentence (to what is added in edd2663) says about `shmem_realloc`:

> If the new size is larger, the newly allocated portion of the block is uninitialized.

which says, in a more-general way, what ed2663 then immediately adds:

> When extending a block allocated with `shmem_calloc`, `shmem_realloc` does not guarantee that the newly allocated portion of the block is initialized to all zero bits.

The POSIX definitions for [`calloc`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/calloc.html) and [`realloc`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/realloc.html) also do not cross-reference each other in this way.

**Comment by jdinan** [comment]
Fair enough, I'll remove this edit.
