### ISSUE TITLE
Clarify precedence of SMA_* and SHMEM_* environment variables

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#111]
With #14, we deprecated the `SMA_*` environment variables and added equivalent ones with the `SHMEM_*` prefix. Since this change, the precedence of `SMA_*` vs. `SHMEM_*` env-vars is unspecified and should be clarified. From a practical perspective, this is particularly important for `SHMEM_SYMMETRIC_SIZE` vs `SMA_SYMMETRIC_SIZE`.

(This issue was split off from #98, where it was originally identified.)

**Comment by nspark** [comment]
This issue will be closed by the frontmatter draft (see as https://github.com/RaymondMichael/specification/pull/4).

**Comment by RaymondMichael** [comment]
This got merged into RaymondMichael, so pulling off the queue.
