### ISSUE TITLE
Inconsistent use of "null pointer" vs "NULL pointer"

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#112]
(This chiefly affects Section 8.2, although there are some references to "NULL pointers" in Annex C.)

The specification is inconsistent in its use of "null pointer" and "NULL pointer" (or "pointers"). For example, the C Standard says about `malloc` that:

> The `malloc` function returns either a null pointer or a pointer to the allocated space.

while `shmem_malloc` says:

> The `shmem_malloc` routine returns a pointer to the allocated space; otherwise, it returns a `NULL` pointer.

To be pedantically aligned with the C Standard -- _always_ my preference :wink: -- we should be using:

* "null pointer" when referring to such a thing
* "null pointer constant" when referring to such a thing
* and `NULL` when referring to the macro for a null pointer constant provided in `stddef.h` and elsewhere

In general, this means the OpenSHMEM Specification should use "null pointer" (or "pointers") except when we specifically mean something else.

Relevant C Standard references:
* C11 &sect;6.3.2.3, _Pointers_: defines "null pointer constant" and "null pointer"
* C11 &sect;7.19, _Common definitions `<stddef.h>`_: provides the macro `NULL`

**Comment by jdinan** [comment]
Oh crud, I just updated Section 8.2 to use _NULL_.  😬 🌴  (there's no facepalm emoji, so there you go)

**Comment by jdinan** [comment]
Of course, now it shows up in the search list.  🤦‍♀️ 🤦‍♂️

**Comment by jdinan** [comment]
Section 8.1-8.2: 37f8e30d
