### ISSUE TITLE
PEs started by shmem_init

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#119]
The following sentence should be updated (or better yet, deleted) now that thread safety (#43) has introduced shmem_init_thread:

shmem_barrier_all.tex:27 "This routine must be used with \acp{PE} started by \FUNC{shmem\_init}.

**Comment by jdinan** [comment]
General task: grep the spec for shmem_init to see if text needs to be updated for consistency with shmem_init_thread.

**Comment by abouteiller** [comment]
👍  for deletion.

**Comment by BryantLam** [comment]
xref #118 (Back Matter) https://github.com/openshmem-org/specification/pull/118/commits/ad9bcaeadfa04992586cd98b5359eddd645c3b64

**Comment by manjugv** [comment]
Another instance has been updated as a part of https://github.com/openshmem-org/specification/pull/145

**Comment by manjugv** [comment]
Instance in finalize is addressed here: https://github.com/openshmem-org/specification/pull/146

**Comment by BryantLam** [comment]
This issue appears in the Undefined Behavior annex and I fixed it as a document edit in #118. My opinion is that we should define a new section with "Initialization Routines" and use that phrasing anywhere `shmem_init` currently appears in the document. That way, we don't have to constantly repeat `'shmem_init' or 'shmem_init_thread'` everywhere.

**Comment by manjugv** [comment]
@BryantLam We had a lengthy discussion on this topic in the WG yesterday. The conclusion - we were not able to agree on quick fix for this version. So, we tabled this for now and decided to take it for next version.

**Comment by jdinan** [comment]
The "PEs started by..." issue has been resolved.  For the ```shmem_init``` and ```shmem_init_thread``` consistency issue, please use issue #132.
