### ISSUE TITLE
Deprecated "Implicit finalization" still supported?

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#124]
Annex F table has "Implicit finalization" listed as still supported under the current version of OpenSHMEM. This is clearly not intended behavior since implicit finalization was removed in #37 in favor of explicit finalization. Does this fall within the scope of a DocEdit (change "Current" to "1.3")?

**Comment by jdinan** [comment]
It was deprecated, but not removed.  It's still valid to use with ```start_pes()``` for backward compatibility.

**Comment by BryantLam** [comment]
Gotcha. That explains why the [jump-link](https://github.com/openshmem-org/specification/pull/37/files#diff-dc17c358e200fd3cda07436810bcc31d) is to `start_pes`. Issue resolved.
