### ISSUE TITLE
Environment Variables missing styling

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#126]
Library constants --> `\CONST`
Library variables --> `\VAR`
Environment variables?

Only existing actual use is for `SHMEM_SYMMETRIC_SIZE`, which does not *feel* correct.
We probably need a new macro.
```bash
$ grep 'SHMEM\\_SYMMETRIC\\_SIZE' * -R
content/environment_variables.tex:\texttt{SHMEM\_SYMMETRIC\_SIZE} & non-negative integer & number of bytes to
content/shmem_malloc.tex:    adjust the size of the heap using the \CONST{SHMEM\_SYMMETRIC\_SIZE} environment
content/shpalloc.tex:    adjust the size of the heap using the \CONST{SHMEM\_SYMMETRIC\_SIZE} environment
```

Affects deprecated `SMA_*` environment variables in Annex F.

**Comment by nspark** [comment]
I noticed this and, for now, I think we should use `\VAR{}`; at least, `\VAR{}`, `\FUNC{}`, and `\FUNC{}` all use the same styling. Another styling inconsistency is that the library constant table uses a particular styling (i.e., `\const{}`) in the table, but the constants themselves use `\CONST{}` elsewhere in the specification.

**Comment by nspark** [comment]
I'm also happy to pick up some of these in the frontmatter changes (if people want consistency). I already have an outstanding PR on @RaymondMichael's `section/front` branch.

**Comment by BryantLam** [comment]
May need another one for keywords (e.g., C "static", Fortran "target").

**Comment by nspark** [comment]
From this:
```bash
$ grep -E -o -h '\\[CV][A-Z]+\{SHMEM\\_[\_A-Z]+\}' -R content/ | sort -u
\CONST{SHMEM\_ALLTOALLS\_SYNC\_SIZE}
\CONST{SHMEM\_ALLTOALL\_SYNC\_SIZE}
\CONST{SHMEM\_BARRIER\_SYNC\_SIZE}
\CONST{SHMEM\_BCAST\_SYNC\_SIZE}
\CONST{SHMEM\_CMP\_NE}
\CONST{SHMEM\_COLLECT\_SYNC\_SIZE}
\CONST{SHMEM\_MAJOR\_VERSION}
\CONST{SHMEM\_MAX\_NAME\_LEN}
\CONST{SHMEM\_MINOR\_VERSION}
\CONST{SHMEM\_REDUCE\_MIN\_WRKDATA\_SIZE}
\CONST{SHMEM\_REDUCE\_SYNC\_SIZE}
\CONST{SHMEM\_SYMMETRIC\_SIZE}
\CONST{SHMEM\_SYNC\_SIZE}
\CONST{SHMEM\_SYNC\_VALUE}
\CONST{SHMEM\_VENDOR\_STRING}
\VAR{SHMEM\_DEBUG}
\VAR{SHMEM\_INFO}
\VAR{SHMEM\_SYMMETRIC\_SIZE}
\VAR{SHMEM\_SYNC\_SIZE}
\VAR{SHMEM\_VERSION}
```

It appears that only `SHMEM_SYMMETRIC_SIZE` and `SHMEM_SYNC_SIZE` get styled by both `\CONST{}` and `\VAR{}`. I think the proper choice should be `\VAR{SHMEM\_SYMMETRIC\_SIZE}` and `\CONST{SHMEM\_SYNC\_SIZE}`.

The offending files appear to be...

(for @jdinan)
```bash
$ grep -Fl '\CONST{SHMEM\_SYMMETRIC\_SIZE}' -R content/
content/shmem_malloc.tex
content/shpalloc.tex
```

(for @BryantLam)
```bash
$ grep -Fl '\VAR{SHMEM\_SYNC\_SIZE}' -R content/
content/backmatter.tex
```

**Comment by jdinan** [comment]
In back matter, the deprecation table needs \VAR and \CONST formatting.

And for @RaymondMichael, s/texttt/VAR/:
```
environment_variables.tex:\texttt{SHMEM\_VERSION} & any & print the library version at
environment_variables.tex:\texttt{SHMEM\_INFO} & any & print helpful text about all these environment
environment_variables.tex:\texttt{SHMEM\_SYMMETRIC\_SIZE} & non-negative integer & number of bytes to
environment_variables.tex:\texttt{SHMEM\_DEBUG} & any & enable debugging messages\tabularnewline
```

**Comment by jdinan** [comment]
@BryantLam How do you want to work this change into 1.4?  I'm happy to take it as a DocEdit (which we can still do between now and ratification).

**Comment by BryantLam** [comment]
@jdinan This issue can be delayed until 1.5 as a DocEdit since this change will not affect visible styling. Feel free to take up the mantle if you want to apply it as a DocEdit during section merging. For now, I used @nspark's suggestion of `\VAR{Environment Variables}`. We may want to differentiate later with a new `\ENV`, and possibly `\KEYWORD` (C `static`, Fortran `target`).
