### ISSUE TITLE
Deprecate Fortran description

### ISSUE THREAD

**Issue by minsii** [openshmem-org/specification#127]
Although all Fortran APIs are marked as deprecated, the related text description is still there. E.g., "When using Fortran, it must be of default kind" in Section 8.8.1 shmem_wait_until - Arguments. 

We need to figure out the way to mark a sentence as deprecated, and make the change for the whole spec.

**Comment by swpoole** [comment]
Do you mean something other than the macro's already supplied?

**Comment by swpoole** [comment]
I *think* in V1.5, we will move all of the Fortran material to an annex.

**Comment by min-si** [comment]
The deprecation macro is used only for the **API synopsis** in the current v1.4 draft. But the other description related to Fortran is still shown as normal text (e.g., search "For Fortran" keyword in the pdf).

**Comment by swpoole** [comment]
What I meant to imply, is can we use the same macro to wrap the other Fortran content? Use the same macro to wrap the examples.

**Comment by min-si** [comment]
Yes, we can use the current macro to wrap examples, whole paragraphs. But this might be hard for  some sentences which are in the middle of a paragraph.

**Comment by jdinan** [comment]
Could we update the \Fortran macro to emit "Fortran (deprecated)"?

**Comment by swpoole** [comment]
Any number of ways to work this one. Any seem fine.

**Comment by nspark** [comment]
@min-si (My $0.02.) All the "If Fortran, then..." text in the specification already adversely impacts its readability. I'd prefer _not_ to add deprecation text every place Fortran gets a mention. The Fortran API itself is deprecated; the behavioral aspects specific to those APIs only apply to the deprecated APIs and, therefore, are similarly (and implicitly) deprecated. My opinion is that marking every Fortran-specific clause as deprecated is overkill.

> @swpoole: can we use the same macro to wrap the other Fortran content?

Not exactly, but I did create a `DeprecateInline` environment just for inline text deprecations like this. The Fortran API deprecation uses the `DeprecateBlock` environment.

> @jdinan: Could we update the \Fortran macro to emit "Fortran (deprecated)"?

Yes, we could do that.

> @swpoole: I think in V1.5, we will move all of the Fortran material to an annex.

That would be awesome.

**Comment by swpoole** [comment]
@nspark Agreed on the readability. It is already a bit messy, but tolerable. As this is the section where we are discussing the Fortran future, my goal is to move ALL of the Fortran material to its own annex in V1.5. In V1.6 we move ALL of the Fortran material to its own document *IF* there is a sudden uprising of Fortran applications using it. Then there would be a larger Fortran community which could support this effort.

**Comment by jdinan** [comment]
I believe that this is now resolved with the removal of Fortran in 1.5. Please re-open if I missed something.
