### ISSUE TITLE
Remove deprecated examples

### ISSUE THREAD

**Issue by abouteiller** [openshmem-org/specification#133]
With the deprecation of Fortran (and start_pes, etc), there are a number of examples that are demonstrating deprecated usage. 

Deprecated examples should be removed and/or substituted with C11 examples.

**Comment by swpoole** [comment]
We will be moving all of the Fortran examples and deprecated functions to an appendix in V1.5, but keeping them as we do have Fortran users currently. I agree with the thought, just not the removal at this point.

**Comment by abouteiller** [comment]
linked to issue #127 

I can't tag for v1.5

**Comment by jdinan** [comment]
Resolved with Fortran removal. Please re-open if there were non-Fortran examples that need to be fixed.
