### ISSUE TITLE
executed in some order and overlapping regions

### ISSUE THREAD

**Issue by abouteiller** [openshmem-org/specification#134]
pp.20 l.20: "as if the calls executed in some order even if their execution is interleaved."

This block of text may be read as condoning that overlapping shmem_put to the same target memory region would be "atomic" in the sense that you'd read the exact result of the first put for the entire target buffer, **OR** the second put for the entire buffer. I do not think this is the intended semantic; if multiple put target the same region without barriers, the output buffer is undefined.

**Comment by jdinan** [comment]
This text is now in Section 9.2 item 4. I also agree that this does a poor job of capturing the semantic. It actually reads like the MPI text describing multithreaded send/recv, indicating that MPI will induce a matching order on send and receive operations. I think we can improve the document by simply deleting "and the outcome will be as if the calls executed in some order, even if their execution is interleaved."

**Comment by manjugv** [comment]
@jdinan The suggestion looks fine to me.

**Comment by manjugv** [comment]
Addressing via https://github.com/manjugv/specification/pull/13
