### ISSUE TITLE
earlier changes to notes under shmem_wait have been overwritten

### ISSUE THREAD

**Issue by spotluri** [openshmem-org/specification#135]
Changes to notes from this pull request have been overwritten in a latter commit. 

https://github.com/openshmem-org/specification/pull/24

**Comment by spotluri** [comment]
looks like the regression happened with the following commit: 

https://github.com/openshmem-org/specification/commit/09b534015d2d78f774b4beb31281b8c458989a5d

@nspark, can you confirm that the removal of text under notes section of shmem_wait was unintended.

**Comment by BryantLam** [comment]
The text was not erroneously removed. It was moved to the synchronization intro:
https://github.com/openshmem-org/specification/commit/09b534015d2d78f774b4beb31281b8c458989a5d#diff-b039d6c2bf9af7510d362563dc21966aR40

**Comment by spotluri** [comment]
Thanks @BryantLam, Sorry for the noise. Closing the issue.

**Comment by BryantLam** [comment]
Credits to @nspark for knowing what's up. 🥇
