### ISSUE TITLE
Move to `master` as the replacement for `osh_spec_next`

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#137]
This repository uses `osh_spec_next` to track what other projects refer to as `master`. We should move to `master` as the devel branch for OpenSHMEM 1.5.

**Comment by RaymondMichael** [comment]
Yes please

**Comment by BryantLam** [comment]
On the call, I contemplated `HEAD` pointing to some stable document on initial checkout. However, now my opinion is that anyone that wants to *work* on the spec just wants `HEAD` to point to `master`. Users that want a stable document should knowingly grab it from the appropriate repo tag.

**Comment by jdinan** [comment]
Done.
