### ISSUE TITLE
Add new constants to the constants table

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#143]
The following constants are introduced in 1.4 and should be added to the constants table:
 * SHMEM_THREAD_SINGLE, SHMEM_THREAD_FUNNELED, SHMEM_THREAD_SERIALIZED, and SHMEM_THREAD_MULTIPLE
 * SHMEM_CTX_SERIALIZED, SHMEM_CTX_PRIVATE, SHMEM_CTX_NOSTORE

The following existing constants should also be added to the constants table:
 * SHMEM_CMP_EQ, SHMEM_CMP_NE, SHMEM_CMP_GT, SHMEM_CMP_LE, SHMEM_CMP_LT, and SHMEM_CMP_GE

**Comment by BryantLam** [comment]
Yes they should. Also, are the values from `shmem_wait` considered the same (`SHMEM_CMP_NE`, ...)?

**Comment by jdinan** [comment]
@RaymondMichael Can you take this issue, since it falls in your section?

**Comment by nspark** [comment]
I'll take this one and submit a PR @RaymondMichael to incorporate into #120.

**Comment by nspark** [comment]
I have the changes ready to go; they're just waiting on the merges of #63 --> `osh_spec_next` --> RaymondMichael:section/front.

**Comment by RaymondMichael** [comment]
This was checked into RaymondMichael and into the master front matter PR, so I'm pulling it off the queue.

**Comment by jdinan** [comment]
@RaymondMichael Please leave this on your section's queue and close the ticket.  It will help us track the resolved issues to leave it there in the close state.

**Comment by RaymondMichael** [comment]
Re-adding and closing
