### ISSUE TITLE
Use of IN, OUT, and INOUT "modes" for function arguments

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#147]
@min-si observed that the IN and OUT argument "modes" are inconsistently used and submitted a set of changes (https://github.com/nspark/specification/pull/3) to the RMA/AMO Section Committee working draft. While this primarily affects the RMA and AMO sections, it also affects others; e.g., collectives, synchronization. I think this inconsistency is pervasive (and confusing) enough to need consideration by the whole committee.

In general, I think the whole IN/OUT distinction is superfluous (at best) and confusing (at worst). C already has a way of expressing the contract of an API that a function shall not change the object pointed to by a pointer-type argument; it's called `const`. I would love to see them removed entirely from the specification, but I think that will need to wait for 1.5.

Assuming we live with them for 1.4, I think there are three models for these sorts of "modes", as could be (or are) used by OpenSHMEM.

Specifically, a non-`const` pointer argument to a function call has a mode of:

When the object pointed to by the argument... | Model 1 | Model 2 | Model 3 | Example
----- | ------ | ------ | ------ | ------
...will only be modified if the target PE is the calling PE | IN | IN/OUT | OUT | `dest` of `shmem_put`
...is unconditionally modified by the call | OUT | OUT | OUT | `dest` of `shmem_get`

A `const`-modified pointer argument to a function call always has a mode of IN.

On review, I think that the OpenSHMEM RMA and AMO routines are pretty evenly split between Model 1 and Model 3, which only complicates deciding which one should be favored for the sake of consistency. The only reference to IN/OUT that I see in the specification is in `shpclmove`.

In addition, there are strange exceptions to these models. For example, the `dest` argument of `shmem_broadcast` will only be modified when the calling PE is not the root.

This won't be fixed in time for the RCM draft, but I think we should fix before ratification.

**Comment by BryantLam** [comment]
I would never expect a variable called `dest` to be an `IN` variable; model 3 is my preferred choice and I would need a convincing argument as to why `dest` can be considered anything else, especially for `shmem_broadcast`.

**Comment by BryantLam** [comment]
These modes are used in a confusing manner (argument input/output to the function vs. data-transfer input/output to the communications layer). I am in favor of getting rid of them altogether or consistently set them to be the C-interface equivalent (model 3) instead of this weird hybrid.

Personally, I admit to ignoring the IN/OUT modes because they were inadequately defined.

**Comment by swpoole** [comment]
Looks like a topic for V1.5

**Comment by jdinan** [comment]
I agree that the IN/OUT labels should disappear along with the Fortran bindings.  The MPI Fortran experts chose to call such arguments "OUT" (see, MPI_REDUCE with the MPI_IN_PLACE option, which uses the recvbuf argument as both the input and output), so I suggest we follow their convention.

**Comment by nspark** [comment]
@BryantLam said:

> I would never expect a variable called `dest` to be an IN variable; model 3 is my preferred choice and I would need a convincing argument as to why `dest` can be considered anything else, especially for `shmem_broadcast`.

Let's start with `shmem_put`. Except for when the calling PE is also the target PE, the `dest` argument is not _really_ a pointer to the object being updated, but a non-opaque handle that corresponds to the object being updated on the target PE. In this way, it truly is an IN variable. It is an input that tells the library half of what it needs to know about where the object to be updated lives. Unlike `memcpy` or `memmove` -- which will unconditionally update the object pointed to by `dest` -- it is not actually a pointer to the object being updated in the typical case.

With regards to collectives, I'm likely stretching it because I see the rationale for OUT in `shmem_broadcast`.

@jdinan I see what you mean about `MPI_REDUCE`, but MPI doesn't _really_ provide guidance for atomics or RMA. From my brief review of the MPI one-sided functions, MPI gets around the issue because the MPI equivalent of `dest` is really the pair of (displacement, window).

All that said, I'm begrudgingly fine using Model 3 and can make the changes as a post-{RCM draft deadline} change, but I would like to remove them entirely with OpenSHMEM 1.5.

**Comment by davidozog** [comment]
This is tricky/unfortunate, because I'd say we might be discussing semantically-relevant changes, which means these fixes might need to be deferred to v1.5, correct?

FWIW, I don't have too much trouble with either models 1, 2, or 3, as long as the whole specification is consistent (which it's clearly not).  That said, I find the labels to be _barely_ useful, if at all.  I think the text that accompanies the argument is where the semantics really become clear.  So, perhaps we just just remove them altogether (eventually).

On the other hand, it is useful to know from glancing at an Arguments list which args are set by the library and which are set by the user.  I kinda like Model 2 for that reason, but seems like nobody else does?  ;)

**Comment by BryantLam** [comment]
@nspark said:
> Let's start with shmem_put. Except for when the calling PE is also the target PE, the dest argument is not really a pointer to the object being updated, but a non-opaque handle that corresponds to the object being updated on the target PE. In this way, it truly is an IN variable.

I understand `dest`'s rationale as an IN variable. I simply don't agree with it. 😄

Under this same definition, is `shmem_put`'s `source` argument IN or OUT? It's an input to the function (the actual data in `source`), but the spec says it's a data-transfer output from the routine (the intent). One could ambiguously interpret `shmem_put` returning some data in `source` similar to how some handle is returned from `ctx` in `shmem_ctx_create` (... except it can't because `source` is `const` and the API description says `source` is a function input so why even have the labels).

**Comment by nspark** [comment]
> Under this same definition, is `shmem_put`'s `source` argument IN or OUT?  It's an input to the function (the actual data in `source`), but the spec says it's a data-transfer output from the routine (the intent).

That is one case that I am 100% confident is an error. Under no circumstance should a `const`-qualified pointer argument be an output argument. The `source` argument is labelled IN for both `shmem_iput` and `shmem_put_nbi`.

**Comment by min-si** [comment]
Sorry for my late response. 

I would prefer model 3 if we change the whole spec consistently. My understanding is that the IN/OUT models only define whether the library will/might update the variable.
`IN` means 1) the library needs the information; 2) the library will not change the data.
`OUT` means 1) the library will (might) update the data.
`IN/OUT` can be ignored if we think `OUT` also includes 1) the library needs the information. 

Thus the `source` variable in `shmem_put` is definitely an `IN`. I would suggest setting all *might-be-updated* variable as `OUT` such as the `dest` variable in RMA and AMO routines.

**Comment by jdinan** [comment]
Please keep in mind that these intents specify the ```intent(...)``` attribute on a Fortran interface, so this is not a matter of taste (rarely is when Fortran is involved).  Whatever this committee chooses specifies the intent attributes that should be given by a compliant Fortran 90 implementation.  Thus, changing the current values could impact backward compatibility for existing Fortran codes.

**Comment by jdinan** [comment]
@nspark We have this issue on the 1.4 roadmap.  Is this still 1.4 or are we going to punt to 1.5?

**Comment by nspark** [comment]
Yes, this issue is still on the docket for 1.4. It'll be fixed after the RCM and voted on at the FRM.

> Please keep in mind that these intents specify the `intent(...)` attribute on a Fortran interface, so this is not a matter of taste (rarely is when Fortran is involved). [...] Thus, changing the current values could impact backward compatibility for existing Fortran codes.

Generally, I don't think these changes should be too contentious. We'll only be fixing the cases that are certainly wrong (e.g., how `shmem_put` specifies `dest` as "IN" and `source` as "OUT").

**Comment by min-si** [comment]
@nspark From the aspect of Fortran `intent attribute`, I think there is no confusing whether changing the data in address `dest` (not the value of `dest` itself) should be `OUT`. 
I agree that at least for the RMA and AMO section, we should fix the incorrect cases in 1.4. I can quickly clean my previous patch later today.

Another question is, whether we should introduce `INOUT`(e.g., for `dest` in `SHMEM_SWAP`). To strictly follow the Fortran intent attribute definition, we will need to set AMO `dest` argument to `INOUT`. I am not sure whether we can make the decision at this RCM or delay it.

**Comment by nspark** [comment]
@manjugv The SHMEM Reductions section erroneously lists `dest` as having an "IN" argument intent. This should be "OUT". Please fix.

**Comment by nspark** [comment]
@spotluri The `shmem_wait_until` and `shmem_test` routines both list `ivar` as having an "IN" argument intent. I _think_ this should be "INOUT".

From the [Fortran 95 draft](http://j3-fortran.org/doc/standing/archive/007/97-007r2/pdf/97-007r2.pdf) &sect;5.1.2.3: 

> The INTENT (IN) attribute specifies that the dummy argument shall neither be defined nor become
undefined during the execution of the procedure.
>
> The INTENT (OUT) attribute specifies that the dummy argument shall be defined before a
reference to the dummy argument is made within the procedure and any actual argument that
becomes associated with such a dummy argument shall be definable. On invocation of the
procedure, such a dummy argument becomes undefined except for components of an object of
derived type for which default initialization has been specified.
>
> The INTENT (INOUT) attribute specifies that the dummy argument is intended for use both to
receive data from and to return data to the invoking scoping unit. Any actual argument that
becomes associated with such a dummy argument shall be definable.

Now, I don't know much of anything about Fortran and have no idea what a "dummy argument" is, however, the notion that an OUT variable is _defined in the function before its reference_ seems like it is _not_ what is intended (no pun intended [no pun inten... 💥 ]) for `shmem_wait_until`. The IN constraint that `ivar` "shall neither be defined [...] during the execution of the procedure" does not seem appropriate for these functions.

All that said, I wonder whether "if it ain't broke, don't fix it" applies here.

**Comment by manjugv** [comment]
> @manjugv The SHMEM Reductions section erroneously lists dest as having an "IN" argument intent. This should be "OUT". Please fix.

@nspark Thanks. Addressed here: https://github.com/openshmem-org/specification/pull/113/commits/6e35c6c5049ed1f1b10181011a381792655bad08

**Comment by jdinan** [comment]
@nspark If this issue is resolved, please close.  Otherwise, please update the milestone to 1.5.

**Comment by nspark** [comment]
This issue has been resolved for all but `shmem_wait_until` and `shmem_test`. It will be updated to the OpenSHMEM 1.5 milestone.

**Comment by minsii** [comment]
@nspark : I just checked the latest version with section sync PR [125](https://github.com/openshmem-org/specification/pull/125). The `ivar` in these two routines is listed as `OUT`. So they are consistent with the RMA/AMO section now.

**Comment by nspark** [comment]
@minsii : I left this issue open because I think the `ivar` arguments should be "INOUT". The input value definitely matters for `shmem_test` and `shmem_wait_until`.

**Comment by minsii** [comment]
@nspark : OK, agreed. And we have the same question for the AMO operations too, such as `dest` in `shmem_atomic_fetch_inc`.

**Comment by jdinan** [comment]
@nspark This ticket is flagged for 1.5, but it already closed.  Do we want to open a new issue to remove IN, OUT, and INOUT for OpenSHMEM 1.5?
