### ISSUE TITLE
Inconsistent use of \textit vs \emph

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#149]
This issue was brought up in https://github.com/nspark/specification/pull/5.

@nspark said:
> Do we typically favor \emph over \textit?

@BryantLam said:
>It depends on whether you/we [intend the text to be italicized, or simply emphasized](https://tex.stackexchange.com/a/1983). You can redefine `\emph` to be another style (e.g., underlining) and can nest `\emph`.
>
>Intent is not the same as favor though. Search results for [`\textit`](https://github.com/openshmem-org/specification/search?utf8=%E2%9C%93&q=textit&type=) and [`\emph`](https://github.com/openshmem-org/specification/search?utf8=%E2%9C%93&q=emph&type=) indicate that we use both about equally and both "incorrectly" in a few places if you accept the definition of italicization vs. emphasis. Def macros (VAR, CONST, TYPE, TYPENAME) should probably be `\textit` because that's the styling that we intended those to be and textual emphasis should be `\emph`. I would argue that [this line](https://github.com/openshmem-org/specification/blob/1150f36777d25629f4a44bf8ba7316e313f0d473/content/programming_model_overview.tex#L7) should be nested `\emph`ed, or should just be a singular `\emph` since there is no other emphasized text around it.

**Comment by nspark** [comment]
Thanks @BryantLam for clarifying the LaTeX difference. I agree with:

> Def macros (VAR, CONST, TYPE, TYPENAME) should probably be `\textit` because that's the styling that we intended those to be and textual emphasis should be `\emph`.

and that:

> [this line](https://github.com/openshmem-org/specification/blob/1150f36777d25629f4a44bf8ba7316e313f0d473/content/programming_model_overview.tex#L7) [...] should just be a singular `\emph` since there is no other emphasized text around it.
