### ISSUE TITLE
Remove IN, OUT, and INOUT "modes" for function arguments

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#151]
This issue spins off the removal aspect of revising the IN, OUT, and INOUT "modes" of function arguments from #147, explicitly targeted for [OpenSHMEM 1.5](https://github.com/openshmem-org/specification/milestone/2).

**Comment by jdinan** [comment]
@nspark Are you planning to implement this change as a section edit for OpenSHMEM 1.5?

**Comment by jdinan** [comment]
We have decided not to apply this change. A poll of committee members indicated that --- intents are helpful to document and since we already have them, why remove them?
