### ISSUE TITLE
OSSS incorrect expansion in cover page

### ISSUE THREAD

**Issue by swpoole** [openshmem-org/specification#153]
OSSS in the text is correct. Open Source Software Solutions, Inc.
It is incorrect in the expansion in the cover page.

**Comment by RaymondMichael** [comment]
I merged a fix into RaymondMichael:front/matter with https://github.com/RaymondMichael/specification/pull/9 which has made its way into the master front matter PR. I'm sure there's a better way to link things together in GitHub.
