### ISSUE TITLE
Cover Page

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#154]
Do we still want the "Development By" blurb on the title page?  There are many more folks involved now, and some folks have moved from UH to other institutions.

<img width="399" alt="screen shot 2017-09-18 at 3 10 43 pm" src="https://user-images.githubusercontent.com/3397618/30559757-b4252b6a-9c83-11e7-99bc-36cb5b84c16e.png">

**Comment by RaymondMichael** [comment]
I'll remove the first two. It will simplify things while still pointing people to the lists of supporters.

**Comment by RaymondMichael** [comment]
I merged this into RaymondMichael with #https://github.com/RaymondMichael/specification/pull/12
