### ISSUE TITLE
Contributors List

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#155]
The contributor list contains "Isayah Reed, Mellanox" which is incorrect, Isayah works at Intel; however, he has not been active in the specification committee.

Please add "David Ozog, Intel" who has been active in the specification committee.

**Comment by RaymondMichael** [comment]
I checked this into the master front-matter RaymondMichael PR with #https://github.com/RaymondMichael/specification/pull/10

**Comment by RaymondMichael** [comment]
Done
