### ISSUE TITLE
Alignment and C11 Interfaces

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#156]
The following sentence in Section 3 (Memory Model) should be updated to also reference the C11 type-generic bindings:
> Symmetric data objects accessed via typed OpenSHMEM interfaces are required to be naturally aligned based on their type requirements and underlying architecture.

Suggested text:
> Symmetric data objects accessed via typed +and type-generic+ OpenSHMEM interfaces are required to be naturally aligned based on their type requirements and underlying architecture.

**Comment by RaymondMichael** [comment]
This was merged into RaymondMichael with #https://github.com/RaymondMichael/specification/pull/13
