### ISSUE TITLE
Atomicity Guarantees Subsection

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#157]
Should the "Atomicity Guarantees" subsection 4.2 be moved from the "Execution Model" section to the "Memory Model" section?

**Comment by RaymondMichael** [comment]
I could support that. How does #https://github.com/RaymondMichael/specification/pull/14 look? During the merge I would do a squash & merge.

**Comment by jdinan** [comment]
Edit looks ok, but it might be good to leave this as an open issue for discussion at the RCM.

**Comment by jdinan** [comment]
Closed by https://github.com/RaymondMichael/specification/pull/15
