### ISSUE TITLE
Library contants typos

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#158]
In Section 6, Library Constants, the following constant names contain typos:

```SHMEM_CTX_SERIALIZE``` should be replaced with ```SHMEM_CTX_SERIALIZED```
```_SHMEM_CMP_NEEQ``` should be replaced with ```_SHMEM_CMP_NE```

**Comment by RaymondMichael** [comment]
This was merged into RaymondMichael with #https://github.com/RaymondMichael/specification/pull/11
