### ISSUE TITLE
Remove deprecated shmem_wait

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#159]
The ```shmem_wait``` routine is deprecated in 1.4 and should be removed from: Sections 8.10.1 (shmem_fence), 8.10.2 (shmem_quiet), and 8.10.3 (ordering) (including the first figure).

**Comment by spotluri** [comment]
@jdinan, I have updated the example figure for shmem_wait to use shmem_wait_until instead. The only other place where I saw shmem_wait is used is in the Fortan example which I did not change.

**Comment by jdinan** [comment]
shmem_wait is mentioned in the notes sections of 8.10.1 and 8.10.2:
> shmem_wait, shmem_wait_until, shmem_test, shmem_barrier, shmem_barrier_all routines can be
called by the target PE to guarantee ordering of its memory accesses.

It would be nice to not recommend this API, since it's deprecated, but it's not a big deal if this change isn't included in 1.4.

**Comment by spotluri** [comment]
I did see that. But I had observed deprecated API (fortran for example) being explained in notes sections elsewhere.  So, I was a little unsure which way to go. 

I will remove it.
