### ISSUE TITLE
Deprecate "sized" API

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#160]
The "sized" API (API names that end with 8, 16, 32, 64, and 128 -- e.g., ```shmem_put32```) have been made mostly redundant with the addition of fixed-width integer type support.

Can we deprecate this as legacy API in OpenSHMEM 1.5?

Note that we don't have exact matches for signed 128 bit types.  We could add these if it helps with deprecation (although 128-bit types are a C language extension).

**Comment by jamesaross** [comment]
This sounds reasonable.  But for the sake of argument, aren't all typed put routines beyond `shmem_putmem` mostly redundant? Out of the infinite number of types one can have, why specialize just the C types?

Is it perhaps to save a couple memory alignment checks and a multiply/bitshift to calculate the size in bytes?

**Comment by nspark** [comment]
If we want to consider deprecating the `shmem_put<SIZE>` API, then I want to see (micro-)benchmarks that demonstrate that there is *not* a performance advantage of that interface over `shmem_putmem`. My understanding has been that there can be some performance advantage from the alignment and sizing restrictions of the sized interfaces.

**Comment by jdinan** [comment]
The performance of the sized API can be better than the performance of ```shmem_putmem``` because of the alignment restrictions.  The argument for considering deprecation is that the sized interfaces are replaced by the new fixed-width integer bindings (shmem_int32/64_put).  Do we have users that are making their own types (e.g. structures) that are exactly 32/64 bits and using the sized interfaces for that?  That seems like a case that may be better served by generic 32/64 bit interfaces, versus the new fixed-width integer interfaces.

**Comment by nspark** [comment]
>Do we have users that are making their own types (e.g. structures) that are exactly 32/64 bits and using the sized interfaces for that?

There definitely are users that create structures and use the sized RMA interfaces to move data. Are they exactly 32 or 64 bits in size? Probably sometimes.

>That seems like a case that may be better served by generic 32/64 bit interfaces, versus the new fixed-width integer interfaces.

I'm not sure what you mean by "generic 32/64 bit interfaces". One cannot safely cast a pointer to a 64-bit structure type to a pointer-to-`uint64_t` and call `shmem_uint64_put` (directly or indirectly via `shmem_put`).

**Comment by jdinan** [comment]
@nspark Sorry need better terminology.  By "generic 32/64 bit interfaces" I intended to refer to ```shmem_put32``` and ```shmem_put64```.

Thanks for the discussion, I think we can close this issue with the conclusion that the sized API is still needed.

**Comment by jamesaross** [comment]
Hang on now...

I don't believe there's anything stopping an implementation from doing something like the code below.  The cost is four bitwise operations (2x OR, 1x AND, 1x right shift), one or two comparisons and a jump.   Compared to the latency of a memory/network transfer, the performance hit is negligible.

```c
void shmem_putmem(void* target, const void* source, size_t len, int pe)
{
	uintptr_t alignment = ((uintptr_t)target | (uintptr_t)source | len) & 0xf;
	switch(alignment)
	{
		case 0: return __internal_put128(target, source, len >> 4, pe);
		case 8: return __internal_put64(target, source, len >> 3, pe);
		case 4:
		case 12: return __internal_put32(target, source, len >> 2, pe);
	}
	// perform slow/unaligned transfer
}
```

Consider the argument if the opposite were true and the specification did not have `shmem_put<SIZE>` -- Expand the API to handle edge cases in order to save clock cycles that one can count with their fingers.

If the lengths are small, like a single C type, an application is probably better off using the `shmem_p` interface(s).

There's a certain elegance to the API should the sized and typed routines be removed. Data movement for all singular C types would then be handled by the C11 generics (such as `shmem_p`) and general memory would be handled by `shmem_putmem`.  A user could forget about types, sizes, and memory alignments for the cost of a few cycles.  It seems odd that there are typed routines for memory movement considering that there are no arithmetic operations and the type is only used to guarantee alignment...which is trivially handled like the code above.

**Comment by jdinan** [comment]
@jamesaross Your analysis is correct.  And the sized APIs are also not available through C11 generic selection.  However, the performance of certain user applications is dependent upon small message throughput.  For these apps, even the small number of cycles needed to optimize putmem for different alignments can have a measurable impact on message rate.  The _p and _g routines are similarly motivated.

**Comment by jamesaross** [comment]
@nspark said:
> If we want to consider deprecating the `shmem_put<SIZE>` API, then I want to see (micro-)benchmarks that demonstrate that there is not a performance advantage of that interface over `shmem_putmem`.

I did this and the code is below.

@jdinan said:
>  For these apps, even the small number of cycles needed to optimize putmem for different alignments can have a measurable impact on message rate.

This is not so -- at least for an SGI ICE FDR Infiniband cluster I'm testing.  The overhead just doesn't appear out of the noise.  I'm interested in seeing platforms and OpenSHMEM implementations that will actually show a statistically significant performance difference, but I'm not holding my breath.

The code does many small transfers of 1 to 128 bytes from PE 0 to PE 1 using various routines with 100,000 iterations.  If I've done the math right, there are about 8,000 clock cycles worth of overhead/latency for each transfer on this platform.  If trimming off a handful of cycles is critical to the performance of an application, there are other means to go about this and they don't involve the OpenSHMEM API.

Unless someone has a platform where the typed and sized routines make a demonstrable impact for small transfers, the `shmem_[put|get][32|64|128]` and perhaps `shmem_<TYPE>_[put|get]` routines seem to be ripe for deprecation.

```c
#include <stdio.h>
#include <stdint.h>
#include <sys/time.h>
#include <shmem.h>

#define NBYTES 128
#define NLOOP 100000

void my_putmem(void* target, const void* source, size_t len, int pe)
{
	uintptr_t alignment = ((uintptr_t)target | (uintptr_t)source | len) & 0xf;
	switch(alignment)
	{
		case 0: return shmem_put128(target, source, len >> 4, pe);
		case 8: return shmem_put64(target, source, len >> 3, pe);
		case 4:
		case 12: return shmem_put32(target, source, len >> 2, pe);
	}
	// perform slow/unaligned transfer
	return shmem_putmem(target, source, len, pe);
}

int main (void)
{
	shmem_init();
	int me = shmem_my_pe();
	int npes = shmem_n_pes();
	printf("%d of %d\n", me, npes);
	int nxt_pe = (me + 1) % npes;

	struct timeval start, stop;

	void* data = shmem_malloc(NBYTES);

	if (!me) // only PE #0
	{
		printf("shmem_putmem:\n");
		printf("    Bytes   Time (x%4d)    MiB/s\n", NLOOP);
		for (size_t b = 1; b <= NBYTES; b++) {
			gettimeofday(&start, 0);
			for (int l = 0; l < NLOOP; l++) shmem_putmem(data, data, b, nxt_pe);
			gettimeofday(&stop, 0);
			double dt = (stop.tv_sec - start.tv_sec) + (stop.tv_usec - start.tv_usec)*1.0e-6;
			double MiBps = (double)(b*NLOOP)/((double)(1024*1024) * dt);
			printf("%10u %1.8f %4.8f\n", b, dt, MiBps);
		}

		printf("my_putmem:\n");
		printf("    Bytes   Time (x%4d)    MiB/s\n", NLOOP);
		for (size_t b = 1; b <= NBYTES; b++) {
			gettimeofday(&start, 0);
			for (int l = 0; l < NLOOP; l++) my_putmem(data, data, b, nxt_pe);
			gettimeofday(&stop, 0);
			double dt = (stop.tv_sec - start.tv_sec) + (stop.tv_usec - start.tv_usec)*1.0e-6;
			double MiBps = (double)(b*NLOOP)/((double)(1024*1024) * dt);
			printf("%10u %1.8f %4.8f\n", b, dt, MiBps);
		}

		short* sdata = (short*)data;
		printf("shmem_short_put:\n");
		printf("    Bytes   Time (x%4d)    MiB/s\n", NLOOP);
		for (size_t e = 1; e <= NBYTES/2; e++) {
			size_t b = 2*e;
			gettimeofday(&start, 0);
			for (int l = 0; l < NLOOP; l++) shmem_short_put(sdata, sdata, e, nxt_pe);
			gettimeofday(&stop, 0);
			double dt = (stop.tv_sec - start.tv_sec) + (stop.tv_usec - start.tv_usec)*1.0e-6;
			double MiBps = (double)(b*NLOOP)/((double)(1024*1024) * dt);
			printf("%10u %1.8f %4.8f\n", b, dt, MiBps);
		}

		printf("shmem_put32:\n");
		printf("    Bytes   Time (x%4d)    MiB/s\n", NLOOP);
		for (size_t e = 1; e <= NBYTES/4; e++) {
			size_t b = 4*e;
			gettimeofday(&start, 0);
			for (int l = 0; l < NLOOP; l++) shmem_put32(data, data, e, nxt_pe);
			gettimeofday(&stop, 0);
			double dt = (stop.tv_sec - start.tv_sec) + (stop.tv_usec - start.tv_usec)*1.0e-6;
			double MiBps = (double)(b*NLOOP)/((double)(1024*1024) * dt);
			printf("%10u %1.8f %4.8f\n", b, dt, MiBps);
		}

		printf("shmem_put64:\n");
		printf("    Bytes   Time (x%4d)    MiB/s\n", NLOOP);
		for (size_t e = 1; e <= NBYTES/8; e++) {
			size_t b = 8*e;
			gettimeofday(&start, 0);
			for (int l = 0; l < NLOOP; l++) shmem_put64(data, data, e, nxt_pe);
			gettimeofday(&stop, 0);
			double dt = (stop.tv_sec - start.tv_sec) + (stop.tv_usec - start.tv_usec)*1.0e-6;
			double MiBps = (double)(b*NLOOP)/((double)(1024*1024) * dt);
			printf("%10u %1.8f %4.8f\n", b, dt, MiBps);
		}

		printf("shmem_put128:\n");
		printf("    Bytes   Time (x%4d)    MiB/s\n", NLOOP);
		for (size_t e = 1; e <= NBYTES/16; e++) {
			size_t b = 16*e;
			gettimeofday(&start, 0);
			for (int l = 0; l < NLOOP; l++) shmem_put128(data, data, e, nxt_pe);
			gettimeofday(&stop, 0);
			double dt = (stop.tv_sec - start.tv_sec) + (stop.tv_usec - start.tv_usec)*1.0e-6;
			double MiBps = (double)(b*NLOOP)/((double)(1024*1024) * dt);
			printf("%10u %1.8f %4.8f\n", b, dt, MiBps);
		}
	}

	shmem_finalize();
	return 0;
}
```
