### ISSUE TITLE
Remove references to SGI Altix systems

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#161]
The description of both `shmem_pe_accessible` and `shmem_addr_accessible` functions gives examples in the SGI Altix systems of how those routines could be used in hybrid MPI + OpenSHMEM or MPMD executions. This text is not actually a behavioral description and, as far as I can tell, SGI (now HPE) retired the "Altix" branding a while ago.

This issue proposes removing this text from the "API description" section for both routines.

This may be of interest to @RaymondMichael.

**Comment by jdinan** [comment]
Also, move hybrid programming rationale to notes, as suggested in https://github.com/jdinan/specification/pull/1.

**Comment by jdinan** [comment]
Edit applied in b08ee50d.  @nspark and @RaymondMichael please review.
