### ISSUE TITLE
Thread support interfaces not listed in "Programming Model Overview"

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#163]
PR #43 did not add the new thread support interfaces to the _Programming Model Overview_ (Section 2). I see this was referenced in #144 and #145, but it still does not appear to be addressed.

@manjugv Is this a WONTFIX issue?

**Comment by jdinan** [comment]
Closed by https://github.com/RaymondMichael/specification/pull/15

**Comment by manjugv** [comment]
@jdinan This commit (https://github.com/openshmem-org/specification/pull/145/commits/51fb5641624eb04d2fa23eb39e5f29126d80a508) seems to be missing.

**Comment by jdinan** [comment]
@manjugv Looks it was integrated in RaymondMichael/section/front:
```
$ git branch --remotes --contains 51fb564
  RaymondMichael/section/front
  manjugv/thread_frontmatter
```
And a check of that branch shows the changes are still there.
