### ISSUE TITLE
Editorial changes under "Memory Management Routines"

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#164]
## `shmem_malloc` and family

The current API description includes:

> The user is also responsible for calling these routines with identical argument(s) on all PEs; if differing _size_ arguments are used, the behavior of the call and any subsequent OpenSHMEM calls becomes undefined.

I suggest this should be modified to either (bold to highlight difference):

>The user is also responsible for calling these routines with identical argument(s) on all PEs. **For example,** if differing _size_ arguments are used, the behavior of the call and any subsequent OpenSHMEM calls becomes undefined.

or

> The user is also responsible for calling these routines with identical argument(s) on all PEs; if differing **_ptr_**, _size_, **or _alignment_** arguments are used, the behavior of the call and any subsequent OpenSHMEM calls becomes undefined.

The former makes it clear that it is not only _size_ that requires identical arguments across all PEs for the call; the latter identifies all three arguments that must have the identical value for calls that use them.

### `shmem_align`

The current description for `shmem_align` is styled as:

> The _shmem_align_ routine allocates a block in the symmetric heap that has a byte alignment specified by the alignment argument.

but should wrap the second instance of "alignment" with `\VAR{}` and be styled as

> The _shmem_align_ routine allocates a block in the symmetric heap that has a byte alignment specified by the _alignment_ argument.

### `shmem_malloc` and family

This is a subject-verb mis-agreement in the sentence:

> Each of these routines include at least one call to a procedure that is semantically equivalent to _shmem_barrier_all_: [...]

which should be (bold to highlight difference):

> Each of these routines **includes** at least one call to a procedure that is semantically equivalent to _shmem_barrier_all_: [...]

**Comment by jdinan** [comment]
Fix merged.
