### ISSUE TITLE
Review shmem_fence text

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#165]
The section committee added the following new to ```shmem_fence```.  The text is borrowed from ```shmem_quiet```.  Please review with the authors of the thread safety proposal.
```
 +    In an \openshmem program with multithreaded \acp{PE}, it is the
 +    user's responsibility to ensure ordering between operations issued by the threads
 +    in a \ac{PE} that target symmetric memory (e.g. \PUT{}, \ac{AMO}, memory stores,
 +    and nonblocking routines) and calls by threads in that \ac{PE} to
 +    \FUNC{shmem\_fence}. The \FUNC{shmem\_fence} routine can enforce memory store ordering only for the
 +    calling thread. Thus, to ensure ordering for memory stores performed by a thread that is
 +    not the thread calling \FUNC{shmem\_fence}, the update must be made visible to the
 +    calling thread according to the rules of the memory model associated with
 +    the threading environment.
```

**Comment by manjugv** [comment]
> the update must be made visible to the calling thread according to the rules of the memory model associated with the threading environment.

This may be stronger than we want for fence.  You don’t necessarily want the operations to be completed when you call fence, you want to ensure that when the operations complete they are ordered.

Otherwise, the text is fine.

**Comment by spotluri** [comment]
@manjugv, we had agreed that visibility to the calling thread is required for the calling thread to enforce any ordering/completion on the operations. Note that visibility to the calling thread does not necessarily mean ordering or completion as visible to other PEs. The shmem_quiet/shmem_fence by the calling thread is required to enforce that.

**Comment by manjugv** [comment]
We had a brief discussion offline to convince ourselves this is correct. 👍  for the change.
