### ISSUE TITLE
nonblocking vs. non-blocking

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#166]
Comments from RCM meeting for synchronization section (#125) indicated [we should prefer "nonblocking"](https://github.com/openshmem-org/specification/pull/125#discussion_r143017597), but that preference is not consistent with actual use of "non-blocking".

| Instances | nonblocking | non-blocking |
| -- | -- | -- |
| OpenSHMEM 1.3 | 5 | 7 |
| OpenSHMEM 1.4rc1 | 8 | 18 |
* Generated via PDF search

I personally prefer "non-blocking", therefore backmatter has been using that spelling without previous guidance.

**Comment by jdinan** [comment]
The Chicago manual of style prefers "nonblocking".  (ref: http://www.chicagomanualofstyle.org/qanda/data/faq/topics/HyphensEnDashesEmDashes/faq0079.html)

**Comment by BryantLam** [comment]
I fully implemented the [change to backmatter in a test branch](https://github.com/BryantLam/openshmem-specification/commit/dcbd06e6321811734b8cb137c82e87acc68d3624) for review. The only sketchy looking one is "non-null" --> "nonnull" which is more stylistic than incorrect.

Interestingly, backmatter uses no other hyphenated prefix except "non".

**Comment by jdinan** [comment]
"nonnull" is incorrect according to the Chicago manual.  It should be "non-null".

**Comment by jdinan** [comment]
I think this might be going too far given where we are in the ratification process.  It might be better to limit ourselves to making nonblocking consistent across the document.  Some of these others end up being up to preference (e.g., non- followed by an "n" or vowel can go either way).

**Comment by BryantLam** [comment]
I think that's the general problem with British (*non-*) vs. American (*non*) hyphenation in technical documents. :) We can DocEdit this change in OpenSHMEM 1.5. I'll convert only "nonblocking" for now.

**Comment by manjugv** [comment]
@BryantLam I guess, we can close this ticket, correct ?

**Comment by BryantLam** [comment]
As of ee7e8b43c9513115a6ab9d3eb9224eb76612d08c:

* non
  - nonblocking
  - nonnegative
  - nonzero*
* non-
  - non-fetching
  - non-initializing
  - non-existent
  - non-symmetric
  - non-atomic
  - non-collective
  - non-power-of-two (exceptional)
  - non-null
  - non-reentrant
  - non-standard
  - non-profit
  - non-const
  - non-hybrid (weird)
  - non-OpenSHMEM (weird)
  - non-critical (weird)
  - non-zero*

Looks like the no-hyphens are on the losing side given precedence. Also marked a few weird cases that should be looked at for possible wordsmithing.

**Comment by nspark** [comment]
@BryantLam I think the counts paint a slightly different picture...

```
$ KEYWORDS="atomic blocking collective const critical existent fetching hybrid initializing negative null profit reentrant standard symmetric zero"
$ for kw in $KEYWORDS ; do echo $kw $(git grep --name-only "non$kw" | wc -l) $(git grep --name-only "non-$kw" | wc -l) ; done | awk '{{ i+=$2; j+=$3; printf "%15s %3d %3d\n", $1, $2, $3 }} END {{ printf "%15s %3d %3d\n", "total", i, j }}'
         atomic   0   2
       blocking  17   0
     collective   0   2
          const   0   1
       critical   0   1
       existent   0   1
       fetching   0   5
         hybrid   0   1
   initializing   0   1
       negative   1   0
           null   0   2
         profit   0   2
      reentrant   0   2
       standard   0   1
      symmetric   0   1
           zero   8   2
          TOTAL  26  24
```

The counts are almost evenly split, but it seems like—where it most matters (with nonfetching and nonzero—we favor "non" over "non-".

**Comment by BryantLam** [comment]
> The counts are almost evenly split, but it seems like—where it most matters (with nonblocking and nonzero—we favor "non" over "non-".

I would argue the opposite since uniqueness is an indicator of what text authors tend to prefer when naively picking between "non" and "non-".

Also, I had a previous PR where I changed at least three "non-blocking" into "nonblocking" which is why this issue originated and why I marked nonzero as another conflict word still in the document today.

**Comment by jdinan** [comment]
If we look at the number of characters, there is a clear winner:
```
         atomic   0  38
       blocking 397   0
     collective   0  38
          const   0  20
       critical   0  24
       existent   0  15
       fetching   0  95
         hybrid   0  21
   initializing   0  15
       negative  24   0
           null   0  35
         profit   0  39
      reentrant   0  30
       standard   0  15
      symmetric   0  15
           zero 195  37
          total 616 437
```

**Comment by jdinan** [comment]
@nspark @BryantLam Can we close this issue?
