### ISSUE TITLE
Collect and broadcast collectives preclude C/C++ structures

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#167]
As of 1.3/1.4, the definitions of `shmem_broadcast` and `shmem_[f]collect` preclude data transfer of C/C++ structures. IIRC, we have discussed this before briefly, but no one was aware of the rationale.

* For `shmem_broadcast`, the typing constraint table specifies that "No [...] C/C++ structures are allowed."
* For `shmem_[f]collect`, the argument description for `dest` specifies that "C/C++ structures are not permitted."

Since these are untyped data movement collectives, I suggest removing this limitation against C/C++ structures in OpenSHMEM 1.5.

**Comment by jdinan** [comment]
Resolved by #276
