### ISSUE TITLE
Replace "OpenSHMEM standard" with "OpenSHMEM specification"

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#170]
The description of the ```SHMEM_MAJOR_VERSION``` and ```SHMEM_MINOR_VERSION``` in the library constants section, refers to the "OpenSHMEM standard".  This should be changed to "OpenSHMEM specification" since OpenSHMEM is not blessed by an industry standard setting organization.

(Same change has been applied to ```shmem_info_get_version``` text by the Mgmt. section committee)

**Comment by nspark** [comment]
How about "OpenSHMEM Specification" vs. "OpenSHMEM specification"?

**Comment by jdinan** [comment]
We are consistently inconsistent on lower/upper case "s".  But, sure, we can try to steer toward upper case.

**Comment by RaymondMichael** [comment]
There's lot of places that still say "standard". Are we going to change them all or update lazily?

**Comment by jdinan** [comment]
It would be nice to change them all.  The other instances of "OpenSHMEM Standard" are in front matter (which I think you already handled) and back matter, which @BryantLam has under control.  All of the other instances I spotted were for things like "standard types".

**Comment by shamisp** [comment]
Why do we need the change ???
MPI is not a standard either and nobody has problem with calling it
standard.
There is a concept of de-facto standards. It does not have to be industry
standard.

**Comment by nspark** [comment]
I'd say it's for internal consistency. Informally, we can call it the "OpenSHMEM standard", but in the specification itself, I think we should call it the "OpenSHMEM Specification".

**Comment by jdinan** [comment]
Resolved by https://github.com/RaymondMichael/specification/pull/15

**Comment by BryantLam** [comment]
If "standard" can be used as "C standard" or "C++ standard", why should OpenSHMEM be treated differently; e.g., "OpenSHMEM specification", "OpenSHMEM implementation".

I can see a valid reason for "OpenSHMEM Specification" to be a proxy for ["current OpenSHMEM specification version"](https://github.com/RaymondMichael/specification/pull/15/commits/ff7d9c6430b998e5fca977d81805e6313f1bfcea), but I feel this change will create some odd formatting for [statements like this one](https://github.com/BryantLam/openshmem-specification/blob/7e723c0ab314176166da942344a4ba52e66ba0c6/content/backmatter.tex#L307-L314). Should I also format as "the Specification", especially in intro paragraphs like [here](https://github.com/BryantLam/openshmem-specification/blob/7e723c0ab314176166da942344a4ba52e66ba0c6/content/backmatter.tex#L161-L162).

**Comment by jdinan** [comment]
I think those instances could be fixed by updating them to ```\openshmem Specification```.

**Comment by nspark** [comment]
> If "standard" can be used as "C standard" or "C++ standard", why should OpenSHMEM be treated differently; e.g., "OpenSHMEM specification", "OpenSHMEM implementation".

I don't think there's a meaningful semantic difference between "standard" and "specification". C and C++ are ISO Standards. They typically refer to themselves as "this International Standard". OpenSHMEM has called itself a "specification", and I think we should be consistent no matter which we choose.

**Comment by BryantLam** [comment]
My mistake! I should have been more clear. I am in favor of standard --> specification for consistency, but not in favor of "Specification" (uppercase) except in cases where it is treated as a direct proxy for "this current OpenSHMEM specification version".

**Comment by BryantLam** [comment]
https://github.com/BryantLam/openshmem-specification/commit/9b0b0172dce4e2f11d2a54f19d3bc6a760c19f48 shows all instances of *specification* in backmatter. I'll accept consensus, but I'll need someone to let me know if these are the edits that should be made.

**Comment by manjugv** [comment]
Collective chapter edits are here https://github.com/openshmem-org/specification/pull/113/commits/c73a4107e86a796d215bd2f8e2a556a4e4a7fec6, please let me know if this looks fine.
