### ISSUE TITLE
Memory Model Clarifications

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#172]
Reported by a reader of the 1.4 draft:

In 1.4 draft, Chapter 3 is “memory model”.  Section 3.1 is “atomicity guarantees”.  It says atomicity is guaranteed under simultaneous by atomics of the same type, but says nothing about atomicity or ordering otherwise.
 
That seems like an obvious place to mention concurrent non-atomic accesses.  I will claim that the negative (“an implementation is free to …”) _is_ still defining, but maybe not everybody agrees.
 
Another place is Annex C, which seems to me like a reasonable place to note the race-y behavior under multiple simultaneous writes.
 

Reading the atomics section suggests to me another use case which is maybe undefined:
 
put(dst, src, n, dstpe)
barrier()
x  = atomic_finc(&dst[ran() % n], ran() % num_pes())
barrier()
 
One observation here is that the spec (3.1) says accesses by atomics are exclusive, but not exclusive by other routines.
 
I’ll claim a reasonable programmer will expect that the barrier() ensures only the when any atomic_finc() routine runs, that only atomic_finc() routines are accessing dst, and so guarantees all atomic_finc() accesses are atomic with respect to _all_ memory accesses – e.g., cannot overlap in time with the earlier put().
 
However, there was an earlier non-atomic access (the put()), and I do not see anything in the memory model section which suggests barrier() can be used to “scope” the atomic and non-atomic calls.
 
The documentation for, say, shmem_barrier_all() says it “ensures completion of all previously issued memory stores … AMOs and RMA routines …” but again I don’t see a direct line saying this makes the put() and atomic_finc() usage above safe-to-use.
 
This may be an excessively picky reading, but it _is_ a specification :^)

**Comment by jdinan** [comment]
An example of “concurrent non-atomic accesses” is something like
 
shmem_barrier_all();
for (i=0; i<N; ++i)
  shmem_int_put_nbi(&dst[0], &src[0], 1, dstpe);
shmem_barrier_all();
 
That is, just copies the same source to the same destination repeatedly and in no particular order.
 
More realistic cases might be destination slices which are overlapping but not the same bounds; or several PEs simultaneously writing the same locations in one dstpe.
 
I think programmers will expect that writing different values to the same destination is unordered.  However, they may expect it behaves like a multiprocessor cache coherent model, in which the memory value at all times (during the writes and also afterwards) represents _some_ sequential interleaving of the writes.
 
SHMEM might not provide such a strict guarantee, and so it would be useful to know if multiple concurrent writes to the same memory can ever lead to a different result, such as dropped writes and/or a memory value which does not represent some sequential interleaving – e.g., the initial value is zero and various PEs write values 1..8, but an intermediate or final value is 33.

**Comment by RaymondMichael** [comment]
Let's assume multiple threads writing a stream of integers along the same array. If all writers are on the same machine then as a programmer I would assume some ordering at the integer / word level. If this is being done over the network, ordering might only be at the byte level. This is how most implementations work and we should make sure we don't prevent that, as nice as it would be otherwise. To throw a straw man out, how about the following at the end of the first paragraph of 3.1.

Simultaneous modification of a symmetric object by non-atomic operations is not inherently exclusive and has implementation-dependent results.
