### ISSUE TITLE
Deprecate shmem_wait_until?

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#176]
The C ```shmem_wait_until``` routine is now aliased in C11 translation environments by the type-generic ```shmem_wait_until``` binding.  As a result, this routine can never be invoked in a C11 translation environment (instead, ```shmem_long_wait_until``` will be dispatched by the type-generic binding).

At some point in the future, we will all be using C11 compilers and nobody will be able to even call this routine.  Should it be deprecated?

**Comment by BryantLam** [comment]
We should deprecate it. Older codes should favor the explicitly typed `shmem_long_wait_until` in C99.

**Comment by spotluri** [comment]
Closing. Merged into chapter draft.
