### ISSUE TITLE
SHMEM_CTX_DEFAULT should be a link-time constant

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#178]
The ```SHMEM_CTX_DEFAULT``` constant should be a link-time constant, not a compile-time constant.  If it is defined to be a compile-time constant, it introduces an indirection on the critical path to translate the handle value into a reference to an internal context structure (e.g. check for NULL, index into a table of context objects, etc.).  Defining ```SHMEM_CTX_DEFAULT``` as a link-time constant allows the implementation to use a direct pointer as the value for ```SHMEM_CTX_DEFAULT``` (e.g. ```extern shmem_ctx_t SHMEM_CTX_DEFAULT;``` in ```shmem.h```).

For reference, see MPI 3.1, Section 2.5.4 "Named Constants":
> MPI also provides predefined named constant handles, such as MPI_COMM_WORLD.
> All named constants, with the exceptions noted below for Fortran, can be used in initialization expressions or assignments, but not necessarily in array declarations or as labels in C switch or Fortran select/case statements. This implies named constants to be link-time but not necessarily compile-time constants.

**Comment by jdinan** [comment]
Unfortunately, I think this is something that we should fix for 1.4..

**Comment by jamesaross** [comment]
Might the prototype be defined `extern const shmem_ctx_t SHMEM_CTX_DEFAULT;`? This can lead to optimizations in a header-only implementation.

**Comment by jdinan** [comment]
@jamesaross ```extern const shmem_ctx_t SHMEM_CTX_DEFAULT``` is what I want, but provides a link-time constant, not a compile-time constant.

**Comment by jamesaross** [comment]
@jdinan I understand.  Your first comment dropped the `const`.

**Comment by jdinan** [comment]
Actually, const is probably incorrect, since the structure pointed to by ```SHMEM_CTX_DEFAULT``` is modified in calls to OpenSHMEM routines.  If it's defined in that way, users would end up needing to cast away const-ness to pass it to OpenSHMEM routines (since the routines take ```shmem_ctx_t``` rather than ```const shmem_ctx_t```).

**Comment by jdinan** [comment]
Proposed fix: https://github.com/RaymondMichael/specification/pull/18

**Comment by nspark** [comment]
> Proposed fix: https://github.com/RaymondMichael/specification/pull/18

@jdinan [A comment for your input](https://github.com/RaymondMichael/specification/pull/18#issuecomment-343986278)

**Comment by jdinan** [comment]
Fix merged into RaymondMichael/section/front
