### ISSUE TITLE
Section 8.10.3 diagrams using deprecated values

### ISSUE THREAD

**Issue by jamesaross** [openshmem-org/specification#179]
This is theoretically a very minor change.  An underscore needs removed from the diagram in 8.10.3 where it shows `shmem_int_wait_until(addr, _SHMEM_CMP_EQ, value)`.

It should read `shmem_int_wait_until(addr, SHMEM_CMP_EQ, value)` instead.

But the diagram is in a PDF and I can't change this very easily:
https://github.com/openshmem-org/specification/blob/osh_spec_next/figures/wait.pdf

This isn't the first time the figures have needed updated and it won't be the last.  We should consider using a more open and more portable source format than OmniGraffle.  I hadn't even heard of it before this specification.

**Comment by jamesaross** [comment]
I just realized there are more diagram problems that need fixed.

- `_SHMEM_CMP_EQ` -> `SHMEM_CMP_EQ` (as mentioned above)
- The second diagram on page 99 appears to be about 60% of the correct size.  It should fill the width of the column.
- The fourth and fifth diagrams use the deprecated `shmem_long_fadd` routine, which should be `shmem_long_atomic_fetch_add`.

Other issues that could be fixed:
- *All* of the diagrams could be updated with the C11 Generics because their types are irrelevant to the examples.
- The ordering `PE 2`, `PE 0`, `PE 1` is unusual an inconsistent with the Memory Model in figure 1.  And `PE K` should be `PE N-1` to be consistent with the Memory Model

**Comment by naveen-rn** [comment]
@manjugv will create a fix for this issue - it looks like he has grapple in his mac - which he can use to update the diagram

**Comment by jamesaross** [comment]
@manjugv Would it be possible for you to port the OmniGraffle/grapple figures to Inkscape SVG? Inkscape is open source and supports for Windows, Linux, and MacOS, enabling everyone to modify them.  Inkscape can also export to PDF by command for including the figures when building the document.

**Comment by manjugv** [comment]
@jamesaross @naveen-rn @jdinan I have created a PR #368  with diagrams in SVG format. Also, I have addressed the use of deprecated constant in wait (and created new version of figure wait_v2). Please feel free edit/update the diagrams. 

I have a PR against main spec. Does this have to go to a specific section committee or whole doc edit ?

**Comment by jdinan** [comment]
At this stage, my preference is to only merge changes to section branches. If that is hard to do in this case, we can merge it to master. This particular change seems very unlikely to cause a merge conflict. What's your recommendation?

**Comment by manjugv** [comment]
I can do either. But it is easier to review and merge this branch, though :) Does this go to Naveen's section. If so, whatever he prefers is fine with me.

**Comment by jdinan** [comment]
Technically, I think this is a section committee change that should go through our normal review process. But, we can try to make an exception if that would complicate the process. 🤷‍♂

**Comment by jdinan** [comment]
@manjugv is this issue resolved?

**Comment by naveen-rn** [comment]
Done - merged to Section Committee branch.
