### ISSUE TITLE
Memory management routines implicit shmem_barrier_all vs. shmem_sync_all

### ISSUE THREAD

**Issue by jamesaross** [openshmem-org/specification#180]
The 1.4 RC3 description for `shmem_malloc`, `shmem_free`, `shmem_realloc` and `shmem_align` states:
> Each of these routines includes at least one call to a procedure that is semantically equivalent to `shmem_barrier_all`.

Similarly, the description for `shmem_calloc` states:
> The `shmem_calloc` routine calls a procedure that is semantically equivalent to `shmem_barrier_all` on exit.

The `shmem_sync` and `shmem_sync_all` collective routines in 1.4 were added after `shmem_calloc`.  Before the new synchronization routines there was no way to synchronize without guaranteeing the completion of remote memory stores.  I don't believe there was any discussion of the implicit `shmem_quiet` operation for the memory management routines during the discussion of the new collective routines.

Since all of the memory management routines are local memory operations, wouldn't be be better if it called a procedure semantically equivalent to `shmem_sync_all`?  Do we really want an implicit call to `shmem_quiet`?

I believe the following code snippet would be an example which could behave differently depending on whether `shmem_calloc` calls a procedure equivalent to `shmem_barrier_all` or `shmem_sync_all`.

```c
shmem_putmem_nbi(a,b,n,pe);
int* z = shmem_calloc(n,sizeof(*z));
memcpy(z,a);
```

Weakening the synchronization could theoretically break codes that do this. But the semantics seem wrong the way we have it now.  It seems to me that applications shouldn't be using a local memory operation to guarantee completion of remote operations with the possible exceptions in the entry to `shmem_free` and `shmem_realloc`.  The synchronization for `shmem_align`, `shmem_calloc`, and `shmem_malloc` should only need to guarantee that the local memory is available on all PEs.

For `shmem_realloc`, it certainly doesn't need to call `shmem_barrier_all` a second time on exit because it is a symmetric operation and there couldn't have been any remote operations called in the middle of the routine.

**Comment by jdinan** [comment]
We may also need the notes to users blurb stating (reminding, I hope) that user contexts need to be quieted before calling free.

**Comment by manjugv** [comment]
@jamesaross Do you want to propose a PR, to address this in the committee? We have some discussion time for this tomorrow.

**Comment by jamesaross** [comment]
@manjugv, what you proposed (to change `shmem_barrier_all` to `shmem_sync_all`) is a semantics change.  It would change/break the behavior of certain codes, specifically, the snippet I included above.  I still don't know how to resolve this other than to leave it unchanged.  The specification has committed to a semantic `shmem_quiet` operation for collective memory operations.  This may be fine, despite the additional overhead, since memory operations should not be within critical code sections.

@jdinan has now proposed that user contexts need to be quieted before calling free, so I don't what to close this yet.

**Comment by manjugv** [comment]
We will move this ticket to 1.6 and address via a regular ballot process.

**Comment by jdinan** [comment]
The user contexts quieting change is a reminder to users of the current behavior. We have such text already elsewhere in the spec that can be copy/pasted.

**Comment by jdinan** [comment]
Clearing from OpenSHEM 1.5 section committee project, since this was pushed to the 1.6 milestone.

**Comment by manjugv** [comment]
This will be addressed as a part of spec version, which breaks backward compatibility (probably 2.0).

**Comment by jdinan** [comment]
This would break backwards compatibility. Closing, based on user feedback at Feb. 2024 meeting.
