### ISSUE TITLE
Fortran routines with no arguments are inconsistent

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#183]
Multiple Fortran routines have no arguments and are `CALL`ed with `()` and without. There doesn't appear to be any consistency other than new vs. old:
- **Without**: barrier_all, fence, quiet, cache
    - Example: `CALL SHMEM_BARRIER_ALL`
- **With**: init, finalize
    - Example: `CALL SHMEM_INIT()`

This may be a non-issue (newer Fortran standard?), but I don't know any Fortran. A cursory online search mentioned something about functions vs. subroutines having different semantics.

**Comment by swpoole** [comment]
All deprecated.

Steve...

**Comment by jeffhammond** [comment]
@BryantLam Unlike C/C++, Fortran doesn't care about the trailing `()`...

**Comment by jdinan** [comment]
I think we can safely close this, now that F*****n routines have been removed.
