### ISSUE TITLE
shmem_wait_until is missing from C/C++

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#184]
Related #176

The `long`-typed `shmem_wait_until` is missing from the C/C++ synopsis block.

**Comment by nspark** [comment]
@BryantLam By 04eb654, it seems like we're _not_ deprecating `shmem_wait_until(long*, ...)`. I thought the intent here (and of #176) is to deprecate it.

**Comment by nspark** [comment]
To be clear, I think the implicit intent of #32 (by way of this oversight) was to deprecate `shmem_wait_until(long*, ...)` under C99 and earlier. Explicitly deprecating it in section committee seems reasonable because it still has to exist and shouldn't cause issues with backwards compatibility.

**Comment by spotluri** [comment]
Closing this. Merged into chapter draft.
