### ISSUE TITLE
Annex G.1 should list section 9.6 as also having new datatypes

### ISSUE THREAD

**Issue by RaymondMichael** [openshmem-org/specification#188]
The 1.4 changelog section of Annex G lists expanded datatypes for the functions in sections 9.5 and 9.7. Section 9.6 has also been changed to use the expanded datatypes in Table 3 but is not listed.

**Comment by BryantLam** [comment]
I agree. This change could be made as a document edit, but I'm not sure where in the process it would be made given that we only have the opportunity to review the current RC5 draft and then immediately try to ratify it. The changelog could be updated in OpenSHMEM 1.5, but I don't like this idea.

As a general issue, wide-sweeping section edits and secondary edits on an existing PR are not necessarily reflected accurately (or at all) in the changelogs.

**Comment by jdinan** [comment]
It looks like the intent was to reference the type tables.  We could update this changelog entry to reference Tables 3, 4, and 5 as a doc edit before I publish the 1.4 document (I have a few other doc edits to apply as well).

**Comment by jdinan** [comment]
... and it looks like we forgot to mention the type expansion to the wait API.  Here's the proposed docEdit:
```
-\item Expanded the type support for RMA and AMO operations.
-\\ See Sections \ref{sec:rma} and \ref{sec:amo}.
+\item Expanded the type support for RMA, AMO, and point-to-point
+    synchronization operations.
+\\ See Tables \ref{stdrmatypes}, \ref{stdamotypes}, \ref{extamotypes}, and
+    \ref{p2psynctypes}
```

**Comment by BryantLam** [comment]
The changelog intro paragraph needs a similar modification if we're going down that rabbit hole.

**Comment by jdinan** [comment]
How about shortening "expanded type support for \ac{RMA} and \ac{AMO} operations" to "expanded type support"?

**Comment by jdinan** [comment]
Merged
