### ISSUE TITLE
Understanding the git workflow in this project

### ISSUE THREAD

**Issue by naveen-rn** [openshmem-org/specification#196]
@jdinan Quick question on understanding the git workflow in this project. 
We have two major branches: master and osh-spec-next. What is the official branch from which the current spec (1.4) is released? It looks like the version info has been bumped in master and not in osh-spec-next.

**Comment by jdinan** [comment]
osh_spec_next is being retired, but I hadn't done it yet to give folks with pendings PRs to migrate them to master.  I recently learned that GitHub will allow me to edit the base branch for pending PRs, so I'll update the pending PRs and go ahead with removing osh_spec_next.

**Comment by jdinan** [comment]
Done!  We are fully migrated to master.  🎉
