### ISSUE TITLE
Tools Interface

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#198]
Placeholder to develop a proposal for a tools interface, e.g. "pshmem" profiling interface.  Anybody want to take this and run with it?

**Comment by nspark** [comment]
Is there an example of a pre-OpenSHMEM "pshmem" interface in action? I Googled recently and didn't find anything, so it's not even clear to me what we're talking about. Alternatively, if it's "just" the SHMEM analog to "PMPI", then can someone reference "PMPI" in action?

**Comment by nspark** [comment]
Has there been any progress on the PSHMEM interface? Any chance we could land this in 1.5? I have at least one use case: I could adapt an internal tracing tool to trace native OpenSHMEM API calls.

**Comment by jdinan** [comment]
It might be a good idea to have a committee discussion about the design of the tools interface.  The MPI Forum is working on a new "qshmem" interface to address some of the challenges with "pshmem".  We might want to skip "p" and go directly to "q".  Once we have a clear idea of what we want, I can volunteer @wrrobin to draft the text.

**Comment by manjugv** [comment]
I would consider Sameer (Paratools) and John Linford (Arm) advise and experience in this regard. 

@sameershende 

@nspark Something like this would work for you ? 
https://www.csm.ornl.gov/workshops/openshmem2016/Others/Paratools_vendor_talk_John.pdf

**Comment by nspark** [comment]
> The MPI Forum is working on a new "qshmem" interface to address some of the challenges with "pshmem".

Do you have a link to any MPI Forum discussions that identify or describe these challenges?

> Something like this would work for you ?

I'm not sure whether you're suggesting the tool (Tau) or an approach (manual function wrapping). In either case, I'm talking about a using custom tracing format for which I already have a productive visualization tool. I'd _rather_ manually wrap functions with a PSHMEM interface than a manual approach using separate implementation paths for static (`-Wl,-wrap=<symbol>`) or dynamic (`dlsym()`) libraries.

**Comment by jdinan** [comment]
The PnMPI work from LLNL is good background reading:
 * Code: https://github.com/LLNL/PnMPI
 * Schulz et al, SC '17: https://dl.acm.org/citation.cfm?id=1362663

Info on the "QMPI" proposal:
 * https://github.com/mpiwg-tools/tools-issues/wiki/Interface-to-Replace-PMPI

**Comment by jdinan** [comment]
Resolved by #254
