### ISSUE TITLE
Locks and Threads

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#205]
## Summary

In OpenSHMEM 1.4, the lock API was defined to provide mutual exclusion between PEs and the behavior of recursive lock operations is undefined.  With the introduction of threading, we need to clarify the behavior when a lock that a given PE already holds or has already requested is requested again (e.g. by a second thread in that PE).  In terms of user impact, we must decide whether the lock API can provide:

1. Only mutual exclusion between PEs or 
1. Mutual exclusion between threads within PEs

The following example illustrates multiple threads using the lock API simultaneously:
```
int main(void) {
  static long lock = 0;
  shmem_init_thread(SHMEM_THREAD_MULTIPLE, ...);
  ...
#pragma omp for
  for (... ; ... ; ...) {
      shmem_lock_set(&lock);
      shmem_get(&lock);
      // local update
      shmem_put(...);
      shmem_lock_clear(&lock);
  }
  ...
}
```
## Proposed Changes

Requesting committee feedback to determine whether we should pursue option 1 or 2 above.

## Impact on Implementations

Existing implementations may use a non-reentrant lock algorithm and would need to be changed to support threading.

Implementations that provide a distributed queueing lock using the space provided in the symmetric lock object (e.g. https://github.com/Sandia-OpenSHMEM/SOS/blob/master/src/shmem_lock.h implements the MCS locking algorithm) may be unable to directly support multiple threads within a PE requesting a given lock at the same time.  This is because multiple threads at a PE cannot share the "who gets the lock after me" field that is stored in the lock object at that PE.  That is, the space requirements for such locking algorithms are proportional to the number of lock requesters and the space available (`sizeof(long)*npes`) is fixed.  In such cases, a two-level locking scheme could be used (local mutex gating access to the SHMEM mutex).

Implementations that poll over the network (e.g. spinlocks, bakery locks, etc.) have constant space requirements and can be used to support mutual exclusion between threads within PEs.

## Additional Materials

* [03-06-2018 -- Threads WG.pdf](https://github.com/openshmem-org/specification/files/1786915/03-06-2018.--.Threads.WG.pdf)

**Comment by jdinan** [comment]
Additional tickets that touch the lock API: #174 and #193

**Comment by jdinan** [comment]
Requesting committee feedback.  After spending some time thinking about this, I think I can implement option 2 (mutual exclusion between threads) with minimal overhead.

**Comment by nspark** [comment]
I'm a little nervous using the term "mutual exclusion between threads" here. Yes, the lock API uses the term "mutual exclusion" (which has been confusing before, #41), however, it also ensures that "waiting PEs [...get...] the lock in a first-come, first-served manner". Wording like "ensures first-come, first-served queuing between calling threads across all PEs" feels more consistent with the existing behavior.

I say all that just to be clear that I think Option 2 -- if we choose on it -- should provide such fair queuing behavior even for threads.  Saying that it provides "mutual exclusion between threads" does not alone seem to imply that.

I would certainly be interested to hear @jdinan's thoughts on supporting Option 2 (as I've defined it) with minimal overhead. Lamport's bakery algorithm requires _O(N)_ space, where _N_ is the number of threads. While this makes sense for the static parallelism model of SHMEM PEs, I'm unsure of the approach and concerned about the overhead required to ensure such queuing in a model with dynamic parallelism.

**Comment by jamesaross** [comment]
It's not clear to me why Option 2 should be OpenSHMEM's problem to solve.  The threading interface should provide a method for mutual exclusion.  In this case, with OpenMP, why not use the omp_*_lock() routines?

**Comment by jdinan** [comment]
@nspark FCFS across all threads in all PEs is a challenge without polling over the network, because the distributed SHMEM lock structure doesn't provide enough space to enqueue NPES*T requests for a given lock.  I implemented something close in https://github.com/Sandia-OpenSHMEM/SOS/pull/616 -- FCFS within a PE and FCFS across PEs (but not FCFS across threads at all PEs).  Interested whether you think this is a fair compromise.

@jamesaross If you take Section 9.2 semantics 1 (first sentence) and 4, it kinda sounds like we specified (whether intentional or not) that the implementation should support option 2.  The SOS PR I referenced above implements what I believe is the semantic as specified in 1.4.

**Comment by jamesaross** [comment]
@jdinan I may have initially misunderstood. I had understood Option 2 to be mutual exclusion *only* between threads within a PE like omp_*_lock().  My understanding now is that you meant Option 2 is mutual exclusion for all threads on all PEs per the specification.

Will this code behave correctly with the SOS implementation with Option 2?
```c
int main(void) {
  static long lock = 0;
  shmem_init_thread(SHMEM_THREAD_MULTIPLE, ...);
  ...
  shmem_set_lock(&lock); // Mutex for all PEs and all threads within all PEs (i.e. thread 0)
  ...
  shmem_lock_clear(&lock);
  #pragma omp for // Any problems if this is ignored or each PE has differing thread counts?
  for (... ; ... ; ...) {
    shmem_set_lock(&lock); // A thread in a PE acquires global mutex (one of npes*nthreads)
    ...
    shmem_lock_clear(&lock);
  }
}
...
```

Some of the problems with locking would have easier to address if using an opaque shmem_lock_t type, but this could break backward compatibility.  That and lock attributes are something we should consider for v2.0.

**Comment by jdinan** [comment]
@jamesaross Should work fine.  There's a unit test called mt_locking.c in the PR I linked above, in case you're interested to see another example.

**Comment by jdinan** [comment]
WG indicated that multiple threads at a PE using the same SHMEM lock concurrently should result in undefined behavior.  Closed https://github.com/Sandia-OpenSHMEM/SOS/pull/616, which would have added support for this usage model to SOS and refactored the multithreaded SHMEM lock code into a library that is used by the `unit/mt_lock*` unit test in SOS.
