### ISSUE TITLE
SHMEM wait-then-set

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#208]
This issue proposes an idea that I mentioned in the RMA WG and will be / was initially discussed on the [March 1, 2018](https://github.com/openshmem-org/specification/wiki/RMA-WG-03-01-2018) call.

## Motivation

A user application was implementing a barrier-free collective merge (here, a max _N_ reduction). In this case, each PE had a lock and each lock would be acquired and released both by the local PE and (some) remote PEs. Using OpenSHMEM atomics, we implemented a pattern like:

```c
enum { UNLOCKED = 0, LOCKED };

void collective_function(...)
{
  // acquire the lock
  while (shmem_atomic_compare_swap(&lock, UNLOCKED, LOCKED, pe) != UNLOCKED);

  // ...do stuff...

  // release the lock
  shmem_atomic_set(&lock, UNLOCKED, pe);
}
```

While `shmem_wait_until` provides API-level interfaces for waiting until a local symmetric variable satisfies a specified condition and improves application portability by ensuring proper use of memory fences, it does not provide the ability to wait on a remote symmetric variable or atomically set that variable to a specified value when the condition is satisfied.

The notion of SHMEM wait-and-reset -- a.k.a. @jdinan's SHMEM IFTTT ("if this, then that") -- is to (modestly) improve on an application pattern using OpenSHMEM's existing AMOs and point-to-point synchronization routines to provide mutual exclusion based on a remote lock (_without_ the queuing guarantees of the `shmem_lock` interfaces).

One implementation feature that we initially explored but did not ultimately implement was to add an exponential back-off with a hard limit for the `while(...)` loop. In a no- or low-contention case, this would have no impact on the application. In a high-contention case (e.g., multiple PEs trying to acquire and hold the lock for a nontrivial period), such a back-off scheme would reduce contention on AMO resources.

## Proposed Interface

```c
void shmem_wait_then_set         (TYPE *ivar, TYPE cond, TYPE value, int pe);
void shmem_TYPENAME_wait_then_set(TYPE *ivar, TYPE cond, TYPE value, int pe);
```

with type support equivalent to `shmem_atomic_compare_swap` and behavior as described above.

## Potential Benefits

* Provides an API for a  (potentially) useful pattern
* Reduces potential for user implementation error
* Provides opportunity for reduced AMO contention
* Should have a relatively straightforward implementation

## Potential Drawbacks

* Only supports the wait-until-equal comparison (vs. `shmem_wait_until`'s `cmp` argument) due to `compare_swap`-based implementation
* Adds another set of API calls for what may possibly (likely?) be a less-commonly used API
* The name seems a bit clumsy to me (but better than `shmem_wait_until_equal_then_set`)

## Questions

* If `shmem_wait_then_reset` is built on `shmem_atomic_compare_exchange`, should it accept a `shmem_ctx_t` argument?

**Comment by jamesaross** [comment]
This reminds me of https://github.com/openshmem-org/specification/pull/41.

Really, what this kind of pattern needs is a method to lock a remote PE, not necessarily full type support for a bunch of new functions.  The proposal is a generalization based on a single use case.

**Comment by naveen-rn** [comment]
I suppose this is not for OpenSHMEM-1.5.
