### ISSUE TITLE
Split up symmetric heap routines

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#212]
Split the current `shmem_malloc` section into separate `shmem_malloc`, `shmem_free`, `shmem_realloc`, and `shmem_align` sections.

**Comment by jdinan** [comment]
@manjugv This falls into your section committee. Do you want to tackle this for OpenSHMEM 1.5 or push to 1.6?

**Comment by manjugv** [comment]
Moving to 1.6 

1. Too much for 1.5 and a couple of tickets might actually change it.
2. Spaces and memory kinds can impact this ticket and might have to rework the section.
