### ISSUE TITLE
Long Function Names

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#224]
## Issue

According to Section 5.4.2.1 of the C standard, compilers must support a minimum of "31 significant initial characters in an external identifier".  Multiple OpenSHMEM function names are longer than 31 characters (30 characters, if we reserve one character for the "pshmem" profiling interfaces), e.g. `shmem_ctx_long_atomic_compare_swap` is 34 characters.

## Possible Solutions

1. Do nothing, most compilers support longer function names, so this is not an issue.
1. Clarify that OpenSHMEM requires compiler support for functions with long names.
1. Clarify that some functions may not be available if the compiler does not support long names.

## References

https://stackoverflow.com/questions/2352209/max-identifier-length

**Comment by tonycurtis** [comment]
> On Jun 19, 2018, at 9:52 AM, James Dinan <notifications@github.com> wrote:
> 
> Issue
> 
> According to Section 5.4.2.1 of the C standard, compilers must support a minimum of "31 significant initial characters in an external identifier".  Multiple OpenSHMEM function names are longer than 31 characters (30 characters, if we reserve one character for the "pshmem" profiling interfaces), e.g. shmem_ctx_long_atomic_compare_swap is 34 characters.
> 
> Possible Solutions
> 
> Do nothing, most compilers support longer function names, so this is not an issue.
> Clarify that OpenSHMEM requires compiler support for functions with long names.
> Clarify that some functions may not be available if the compiler does not support long names.

4. Advocatus Diaboli: change/revert atomic_compare_ to amo_c: this would then make the longest (current) name 30 chars.

tony

**Comment by nspark** [comment]
I'm inclined to go for Option 1: "Do nothing, most compilers support longer function names, so this is not an issue."
