### ISSUE TITLE
Inconsistent LaTeX formatting

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#227]
The LaTeX sources for the OpenSHMEM Specification aren't totally consistent with things like indentation. For example:

https://github.com/openshmem-org/specification/blob/034956cd6d32b91322845ef7ba9fbe37c2a6cd0a/content/shmem_calloc.tex#L17-L19

https://github.com/openshmem-org/specification/blob/034956cd6d32b91322845ef7ba9fbe37c2a6cd0a/content/shmem_wait_until.tex#L41-L45

We also have plenty of sources that have lines longer than 80 characters (a pet peeve of mine) and at one time had some invalid LaTeX characters (e.g., improper quotes).

We could (decide to) fix these individually (or not at all), or we could let a computer do it for us!

Potential tools:
- Formatting: [latexindent.pl](https://github.com/cmhughes/latexindent.pl) (docs: [PDF](http://mirrors.ctan.org/support/latexindent/documentation/latexindent.pdf), [HTML](http://latexindentpl.readthedocs.io/))
- Checking: [lacheck](https://ctan.org/pkg/lacheck?lang=en)

We need some experimentation using these tools. I plan to do some; others are welcome, too. It may even be possible to integrate these tools into a CI flow to check incoming pull requests.

If we decide to use some of these on the Specification sources, then I suggest that we wait until after we cut 1.5.

**Comment by nspark** [comment]
### First look at `lacheck`

On my initial evaluation, it looks like `lacheck` is excessively noisy (and that's even considering our LaTeX source has consistency issues). Many of these are not actually issues, as we use environments (e.g., `apidefinition`) to wrap other environments (e.g., `description`).

#### Excessive warnings

For example, running `lacheck` on `main_spec.tex` produces lots of warnings from `utils/defs.tex`:

https://github.com/openshmem-org/specification/blob/034956cd6d32b91322845ef7ba9fbe37c2a6cd0a/utils/defs.tex#L389-L396

```
"utils/defs.tex", line 389: possible unwanted space at "{"
"utils/defs.tex", line 393: <- unmatched "}"
"utils/defs.tex", line 390: -> unmatched "\begin{description}"
"utils/defs.tex", line 394: possible unwanted space at "{"
"utils/defs.tex", line 395: <- unmatched "\end{description}"
"utils/defs.tex", line 394: -> unmatched "{"
"utils/defs.tex", line 396: <- unmatched "}"
"utils/defs.tex", line 390: -> unmatched "\begin{description}"
```

In theory, we could probably find ways to silence these warnings, but that seems like it would be a fair bit of work.

Further, basically every API listing produces the following warning:

https://github.com/openshmem-org/specification/blob/034956cd6d32b91322845ef7ba9fbe37c2a6cd0a/content/shmem_ctx_destroy.tex#L15-L28

```
** content/shmem_ctx_destroy.tex:
"content/shmem_ctx_destroy.tex", line 1: possible unwanted space at "{"
"content/shmem_ctx_destroy.tex", line 15: possible unwanted space at "{"
"content/shmem_ctx_destroy.tex", line 23: possible unwanted space at "{"
"content/shmem_ctx_destroy.tex", line 27: possible unwanted space at "{"
```

#### Minorly helpful warnings

`lacheck` does produce some helpful warnings such as:

https://github.com/openshmem-org/specification/blob/034956cd6d32b91322845ef7ba9fbe37c2a6cd0a/content/rma_intro.tex#L20

```
"content/rma_intro.tex", line 27: perhaps you should insert a `~' before "\ref"
```

But, those could be fixed manually without much effort.

#### Mysterious warnings

`lacheck` also produces mysterious warnings that I don't understand:

```
"content/rma_intro.tex", line 12: missing `\@' before `.' in "PE."
"content/shmem_get_nbi.tex", line 79: missing `\ ' after "type."
"content/shmem_broadcast.tex", line 29: missing `\ ' after "halfwords."
"content/backmatter.tex", line 47: missing `\@' before `.' in "API."
```

#### Recommendation

I don't think that `lacheck` provides us enough benefit to be worth using.

**Comment by tonycurtis** [comment]
> On Jul 25, 2018, at 11:11 AM, Nick Park <notifications@github.com> wrote:
> 
> First look at lacheck
> 
> lacheck also produces mysterious warnings that I don't understand:
> 
> "content/rma_intro.tex", line 12: missing `\@' before `.' in "PE.”
> "content/shmem_get_nbi.tex", line 79: missing `\ ' after "type."
> "content/shmem_broadcast.tex", line 29: missing `\ ' after "halfwords."
> "content/backmatter.tex", line 47: missing `\@' before `.' in "API.”


Well, the \@ ones are explained here:

https://tex.stackexchange.com/questions/38842/what-does-missing-before-error-mean-in-vim <https://tex.stackexchange.com/questions/38842/what-does-missing-before-error-mean-in-vim>

And I think the other 2 are because the sentence after the highlighted word starts with a lower-case letter.

tony

**Comment by manjugv** [comment]
Closed as per authors request.
