### ISSUE TITLE
Terms that need definition

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#228]
### Terms needing definition or clarification in the OpenSHMEM Specification

- [x] blocking, nonblocking
- [x] local completion, remote completion
- [ ] partial and complete updates (from #271)
- [ ] "routine" vs. "operation". Currently, "operations" appear to encompass a set of routines.

See also: PR #141 for a glossary.

Yes, Culhane prepared a lot of this already We can just add to that.

**Comment by swpoole** [comment]
Pull the Culhane doc.

**Comment by RaymondMichael** [comment]
Where is the Culhane document?

**Comment by jdinan** [comment]
@swpoole, are you referring to #141?

**Comment by nspark** [comment]
I'm working on... (which will be updated here)

- Local completion
- Remote completion
- Blocking
- Nonblocking

**Comment by nspark** [comment]
From @wrrobin:

- Local completion: Completion of an operation that indicates the availability of local resources for safe reuse.
- Remote completion: Completion of an operation that indicates the availability of remote resources for safe reuse.
- Blocking: An operation that halts execution until the operation is complete, either locally or remote.
- Nonblocking: An operation that does not halt execution and returns immediately.
- Routine: Synonymous term for a sequence of a code that is intended to be called and reused during program execution.
- Operation: The task that is executed through an invocation of a routine.

**Comment by jdinan** [comment]
IIUC, quiet is the only blocking operation that returns upon remote completion. However, I suspect we can have an academic debate about whether this is required by the specification, or whether quiet can return immediately and block on the next communication operation in certain circumstances (e.g. when SHMEM_TEAM_SHARED contains only the local PE).

**Comment by nspark** [comment]
Using @jdinan's wording on "in-use" (see https://github.com/openshmem-org/specification/pull/340/commits/7ef07ea354c9b71e0b602b213f1cf730334020af):

> Buffers provided to OpenSHMEM routines are *in-use* until the corresponding OpenSHMEM operation has completed at the calling PE. Updates to a buffer that is in-use, including updates performed through locally and remotely issued OpenSHMEM operations, result in undefined behavior. Similarly, reads from a buffer that is in-use are allowed only when the buffer was provided as a `const`-qualified argument to the OpenSHMEM  routine for which it is in-use.  Otherwise, the behavior is undefined. Exceptions are made for buffers that are in-use by AMOs, [...].

Here are some proposed definitions:

- *Local completion* specifies the point (in time) at and after which a local buffer provided to an OpenSHMEM routine is no longer in-use by that operation.
- *Remote completion* specifies the point (in time) at and after which a remote buffer provided to an OpenSHMEM routine is no longer in-use by that operation.
- A *blocking* OpenSHMEM routine is one for which return from a call to that routine guarantees local completion for its associated local buffers.  
- A *nonblocking* OpenSHMEM routine is one for which return from a call to that routine guarantees neither local nor remote completion.

I'm starting to wonder:

1. Is this somewhat of a circular definition? (For example, "local completion" is defined in terms of "in-use", which is itself defined in terms of "completion".)
2. Is the restriction on reading from `const`-qualified buffers too restrictive? For example, one can safely write to the source buffer of a `shmem_put` after that call returns, however, the "in-use" restriction above seems to imply (for lack of its distinction between local and remote completion; see \#⁠1) that such a write is not safe until the operation is (remotely) complete.

Feedback anyone?

**Comment by RaymondMichael** [comment]
When we talk about local completion in terms of buffers, you can wind up saying that a const argument can be considered locally complete. While that may be true, it feels wrong. You could change you latest local completion definition to say, "...after which *all* local buffers...". I think this is an improvement. Still, I think discussing completion in terms of operations, as opposed to modifications to buffers, feels more natural.

**Comment by nspark** [comment]
:+1: on "..._all_ local buffers..."

> When we talk about local completion in terms of buffers, you can wind up saying that a const argument can be considered locally complete. While that may be true, it feels wrong.

We're not saying the buffer is complete, but that the operation is (locally or remotely) complete based on whether the buffer in question can be (re)used. But, if the wording feels wrong, we should revise it; I'd like it to both be correct and clear.

> I think this is an improvement. Still, I think discussing completion in terms of operations, as opposed to modifications to buffers, feels more natural.

Am I correct in interpreting that the definitions I posted at the F2F ("in terms of operations") are more natural than those I posted today ("in terms of operations")?

**Comment by jdinan** [comment]
In the first definitions, I think it would be better to talk about local completion of objects and then pull that together to describe local completion of the operation. This is roughly what I'm thinking, although there's plenty of room to improve the verbiage:
* For an OpenSHMEM operation that reads a local object of memory—for example, the source argument of shmem_put or shmem_team_broadcast for only the root PE—local completion *of that object* specifies the point (in time) after which a write (or update) to that object by the PE initiating the operation would not affect the value(s) read by the OpenSHMEM implementation in performing the operation.
* For an OpenSHMEM operation that writes a local object of memory—for example, the dest argument of shmem_get or shmem_team_broadcast—local completion *of that object* specifies the point after which a read of that local object by the PE initiating the operation will return the value(s) produced by the OpenSHMEM implementation in performing the operation.
* Local completion of an OpenSHMEM operation indicates that all local objects involved in the operation are locally complete.

**Comment by jdinan** [comment]
@nspark Did these get merged for rc2?

**Comment by nspark** [comment]
@BryantLam @RaymondMichael @jdinan Here's what I have (technically in the backmatter)...

![ToC](https://user-images.githubusercontent.com/2961664/78576789-2c2f1080-77fb-11ea-9810-2f2f0134f958.png)

![Glossary](https://user-images.githubusercontent.com/2961664/78576795-2e916a80-77fb-11ea-8e1d-ba0cdf6dbb0f.png)

I tried using the `glossaries` package, but this would actually require document-wide edits—because AFAICT terms must be referenced in the document (e.g., `\gls{...}`; cf. `\ac{...}`) to show up in the glossary itself. The above example, which uses the `description` environment, presents in the same style as the `glossaries` package, so we can maintain continuity of appears moving forward (if we want to accept this).

**Comment by BryantLam** [comment]
We have a glossary now with initial terms in it. Thanks @nspark!

Bumping to v1.6. The other terms can be added later.

**Comment by naveen-rn** [comment]
@davidozog can you please determine - whether we need to continue maintaining this issue or open new ones as we need new definitions.

**Comment by jdinan** [comment]
Closing this issue, please open new issues for any follow-on work needed in the glossary.
