### ISSUE TITLE
Inconsistent example formatting

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#230]
Continuing on the line of #227 and inspired by @jamesaross's [comment](https://github.com/openshmem-org/specification/pull/218#discussion_r204517239), I think we should run [ClangFormat](https://clang.llvm.org/docs/ClangFormat.html) over all the C and C++ examples during Section Committee period of release preparation. In order to avoid a religious war, I vote for using ClangFormat's default formatting style.

**Comment by jdinan** [comment]
It would be great to also number the examples so that they are easier to reference.

**Comment by jamesaross** [comment]
I prefer uniformity of the example code across the specification over any particular coding style/format.  I don't think ClangFormat will solve some of the example code issues regarding things like variable naming (i.e. `my_pe`/`n_pes` vs. `me`/`n`) or removing the unused `argc`/`argv`. I believe examples are easier to follow and most effective when the common code patterns are uniform and the meaningful differences are obvious.

**Comment by nspark** [comment]
@jdinan How about this?
![examplescreenshot](https://user-images.githubusercontent.com/2961664/43642605-44655502-96f6-11e8-9d20-3ce8bd9b5e4d.png)

**Comment by nspark** [comment]
> I don't think ClangFormat will solve some of the example code issues regarding things like variable naming (i.e. `my_pe`/`n_pes` vs. `me`/`n`) or removing the unused `argc`/`argv`.

@jamesaross, are you talking about the existing examples or new ones that might be added? There's only one example that uses `mype` instead of `me`. (It looks like [I wrote it](https://github.com/openshmem-org/specification/blame/a3b72d0351a218caef0a8b5ff990bd53559d8ba2/example_code/shmem_test_example1.c#L15); I don't like `me`.) No examples have used `argc` or `argv` parameters.

I agree, though, that the examples can be more consistent in more than just formatting style.

**Comment by nspark** [comment]
I'm leaning toward the `\newtheorem`-based example numbering, mostly because it doesn't have issues with `\Cstd[xx]`. (The issue _seems_ like it comes from the default-argument structure of the `\Cstd` command.) Which do any of you prefer?

**Comment by jdinan** [comment]
They both look good.  I have a slight preference toward `\newtheorem`.

**Comment by jamesaross** [comment]
> are you talking about the existing examples or new ones that might be added?

@nspark, Both. Uniformity and consistency should be the goal and I personally value good example code. Your grey box code view above looks good and I'm glad the outside text numbering doesn't spill into the code.  Could you try selecting/highlighting the text with your cursor and copy/pasting from the document to a text editor?  If PDF readers can copy source code directly and compile it without having to remove superfluous line numbers or markup from the source code, we've found a winner.

**Comment by jdinan** [comment]
@nspark Has this been resolved?

**Comment by jamesaross** [comment]
@nspark It's being resolved by #237 and also #350.
