### ISSUE TITLE
Conformance definition

### ISSUE THREAD

**Issue by anshumang** [openshmem-org/specification#231]
Is it useful to define categories and APIs (with types) belonging to each category to determine to what degree an OpenSHMEM implementation conforms to the specification?

For example, 
Level 0 conformance could mean init/finalize/my_pe/n_pes/malloc/free/put/fence/quiet/wait_until; 
Level 1 could mean all of Level 0 and get/amo and so on.

@manjugv @nspark @jdinan @shamisp @spotluri and others - any thoughts?

**Comment by jdinan** [comment]
I'm not sure we will get it right with numbered levels.  If we were to go this route, we should make it programmatic so an application can check whether the features it needs are supported by the given OpenSHMEM library.

**Comment by anshumang** [comment]
Alternatively, can we say that feature X is more critical than feature Y for the most common applications?

**Comment by manjugv** [comment]
Discussed during the WG meeting (June 28th, 2021) and it was concluded not to fix for now.
