### ISSUE TITLE
Move website to pages.github.com

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#240]
Not a specification problem, but I need to put this down before I forget.

It would be useful to move and/or spruce up the current openshmem.org website to pages.github.com and maintain it all here. Any problems with doing this?

**Comment by nspark** [comment]
Oh, hey. They're [already something there](http://openshmem.github.io/). :thinking:

**Comment by swpoole** [comment]
Yes, it was put there years ago. I like the look and feel of either the current site or the OpenMPI version, over the Git* version.

**Comment by manjugv** [comment]
Can we close this issue ? @BryantLam

**Comment by manjugv** [comment]
Closing ..
