### ISSUE TITLE
"const" ivar in wait routines

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#242]
## Problem Statement

Wait routines don't modify `ivar`, thus the argument should be `const` qualified (this doesn't mean `ivar` won't change, just that the calling routine won't change it).

## More Detail

Reported by a user ---

I think it helps users when the parameter is “const”.  That way, a routine with a “const TYPE *ptr” does not have to call cast.  For example, today this will generate a warning/error:
``` 
example(const int *A, int n) {
  sum = 0
  for i in [0..n) {
    wait_until(&A[i], CMP_NE, 0)
    sum += A[i]
  }
  return sum
}
```
So the signature that seems simplest to me would be e.g.,
```
wait_until(const TYPE *ptr, int cmp_function, TYPE value)
```
That lets the user pass both “TYPE *ptr” and “const TYPE *ptr” without casting.  Today (1.4) it is
```
wait_until(TYPE *ptr, int cmp_function, TYPE value)
```
which requires a cast
```
example(const int *A, int n) {
  sum = 0
  for i in [0..n) {
    wait_until(const_cast<int *>(&A[i]), CMP_NE, 0)
    sum += A[i]
  }
  return sum
}
```

**Comment by nspark** [comment]
I feel like we've discussed this before. I think the rationale was that some implementations may need to make a runtime call inside `shmem_wait_until` or `shmem_test` that will in fact modify `ivar` and, thus, `const`-ness might not be appropriate.

That said, it is not strictly incorrect to cast away a `const` type qualifier as long as the referenced object itself is not `const` qualified. It's dangerous, but not incorrect in all cases. It _might_ be reasonable to expect that any call to `shmem_wait_until` et al. should expect the referenced object _not_ to be immutable, but such a change as proposed here would make the following code valid:

```c
#include <shmem.h>
const int zero = 0;

int main(void) {
  shmem_init();
  shmem_wait_until(&zero, SHMEM_CMP_EQ, 0);
  shmem_finalize();
  return 0;
}
```

As long as the runtime never casts away the `const`-ness of `&zero` in the runtime, the implementation won't be invoking undefined behavior.

**Comment by jdinan** [comment]
I think it's safe now to close this issue. If anyone feels otherwise, please re-open.
