### ISSUE TITLE
Clarification on correct pt-to-pt synchronization

### ISSUE THREAD

**Issue by anshumang** [openshmem-org/specification#248]
The goal of this ticket is to agree on the list of API(s) that are allowed to signal to `shmem_type_wait_until `and `shmem_type_test`.

Signaling APIs are grouped into categories below.

- A (Single element put) : `shmem_type_p`, `shmem_ctx_type_p`
- B (Multi element put) : `shmem_type_put`, `shmem_ctx_type_put`, `shmem_type_iput`, `shmem_ctx_type_iput`
- C (Update AMO APIs; no `shmem_atomic_fetch`) : `shmem_type_atomic_set`, `shmem_ctx_type_atomic_set`, `shmem_type_atomic_inc`, `shmem_ctx_type_atomic_inc`, .....
- D (Put with signal API) : `shmem_type_put_signal`, `shmem_ctx_type_put_signal`
- E (Multi-element untyped put) : `shmem_putmem`, `shmem_ctx_putmem`
- F (direct memory access) : store to pointer obtained from `shmem_ptr`

`_nbi` APIs have been excluded for now as they may depend on `shmem_quiet` as noted in #246   

Different choice of allowed signaling APIs below.
    
1. A, D
2. C, D
3. A, C, D

Others?

In addition, the data type of the signaling API and `shmem_type_wait_until`/`shmem_type_test `needs to match.

**Comment by anshumang** [comment]
Follow up comments from RMA WG 9/27/2018 : 
- There is no strong push to keep multi-word put (B) in the list (only usecase mentioned is to send multiple signals but not aware of use)
- Agreement on using the same type on the initiator so `shmem_type_putmem` should fall out of B and can be excluded
- A has been used for signaling for a long time because `shmem_atomic_set` is very new so strong push to keep A in the list
- A needs single-copy atomicity because 1) in memory fabric, `shmem_wait_until` cannot rely on network event for visibility of update in a single-copy atomic way 2) in some network, error condition detection (like CRC) can trigger retransmission and it is hard to prevent visibility of incorrect update
- Agreement that two synchronizing operations to the same location between them need not be well-defined (A and C writing to same location is allowed to be undefined)
- No agreement on whether single-copy atomicity restriction should be placed on A because 1) it is unclear if that is feasible over the most common networks (PCI-E, IB, GenZ) and 2) there is caution against the resulting performance penalty

**Comment by anshumang** [comment]
Agreement on dropping multi-element put (B and E) and direct memory store (F) from the list of synchronizing operations. Also, agreement on including/retaining atomic APIs (C) in the list.

Summarizing the remaining open questions -
1)	Supporting single-copy atomicity of shmem_p (A) in all implementations is hard so don’t make shmem_p single-copy atomic : breaks applications
2)	Existing applications use shmem_p (A) to synchronize so make shmem_p single-copy atomic : implementations need to be changed
 
If we go with 1), a new API like shmem_signal is needed.
If we go with 2), implementations have to guarantee single-copy atomicity where unsupported by hardware (for example, by using RMW atomic).

**Comment by bcernohous** [comment]
Good question in email:

>– Do users use shmem_p for anything *apart from* signaling?  If the answer is no, or that a performance regression for non-signaling usage is not impactful, then we should accept the performance hit and make shmem_p operations valid for signaling

We think it's up to the application writers to comment at this point.  We'll support either choice.

**Comment by anshumang** [comment]
@jdinan @shamisp @manjugv @bcernohous @nspark and others : If there are no objections to making shmem_p be single-copy atomic, I will create a PR for this change. My plan is to update the shmem_p and the pt-to-pt synchronization sections. Any feedback on how to make this change will be very helpful.

**Comment by anshumang** [comment]
@shamisp Thanks for the feedback. All of this is very useful information, indeed.
Other than performance, what is the problem in realizing `shmem_p` as `shmem_atomic_set` when single-copy atomicity is not available? Are you saying, `shmem_p` performance hit is a problem and we need some other API (`shmem_signal`)? In either case, only read-modify-write atomicity is required ( single-copy atomicity is good to have but not must)

**Comment by shamisp** [comment]
@anshumang I think Nick measured atomic impact on multiple interconnects and it is quite substantial, which is expected. 
Moreover, there is additional complication for operations like wait(). If the NIC AMOs are not atomic in respect to the core (true for some implementations of NICs, PCIe, etc) you may end up issuing  loopback atomic read on the *NIC* in order to access local variable (a.k.a. wait will be issuing network requests). For example, PCIe 3.1 AMOs are optional and as a result there are systems that have no way to propagate atomics. 

Nevertheless, if the wait() is used just to discover the update without relying on the "full" value, it may work.

**Comment by anshumang** [comment]
@shamisp If I understand correctly, you have the following concerns:
- `shmem_wait_until` will be slower on some platforms
- `shmem_wait_until` will be software-only on some platforms (on those platforms the AMO APIs would also be software-only)
For all platforms supporting OpenSHMEM, we need an atomic update and visibility mechanism between a writer and reader to synchronize. 
In OpenSHMEM, we need to designate at least one writer and one reader API to use the above mechanism.
Do you agree?

**Comment by shamisp** [comment]
@anshumang 
* I concerned that atomic put is much slower that regular put, especially if you measure injection rate.  
* ```shmem_wait_until``` - will be slower on some platforms due to implementation concerns that I expressed in earlier post.

**Comment by manjugv** [comment]
(If this point is made, I apologize for repeating. There has been many discussion on this and I might have missed.)

@anshumang 

The network will itself can provide single-copy-atomicity guarantee up to the MTU size, but the issue is beyond the network. So, that guarantee is not necessarily ensured at the OpenSHMEM program level. It is difficult to provide single-copy-atomicity guarantee because the message can be across cache lines, the message may have to pass through the PCIe and other buses, and the message might have to be retransmitted because of error. 

With all above cases, I’m not convinced that we can implement shmem_p with single-copy-atomicity guarantee for current architectures in a reasonable way. Can you please shed more light on this, if you think otherwise ? If for current architectures, the only guarantee we can provide is multi-copy-atomicity (like shmem_atomic_set) then why can’t we just use shmem_atomic_set for signaling purposes. 

Question for CPU folks : On x86, Arm, POWER, can you guarantee single-copy-atomicity for stores up to 128bits, when the data is not aligned and/or on  the cache boundary ?

**Comment by anshumang** [comment]
@manjugv 

> With all above cases, I’m not convinced that we can implement shmem_p with single-copy-atomicity guarantee for current architectures in a reasonable way. Can you please shed more light on this, if you think otherwise ?
- `shmem_p` can be implemented as `shmem_atomic_set`. Why do you say that is *not* reasonable?
 
> If for current architectures, the only guarantee we can provide is multi-copy-atomicity (like shmem_atomic_set) then why can’t we just use shmem_atomic_set for signaling purposes.
- `shmem_p` is used for synchronization. Do we want to break existing code?

**Comment by shamisp** [comment]
@manjugv aarch64 - stores have to be naturally aligned otherwise the single copy atomicity cannot be guaranteed.

**Comment by shamisp** [comment]
> (If this point is made, I apologize for repeating. There has been many discussion on this and I might have missed.)
> 
> @anshumang
> 
> The network will itself can provide single-copy-atomicity guarantee up to the MTU size, but the issue is beyond the network. So, that guarantee is not necessarily ensured at the OpenSHMEM program level. It is difficult to provide single-copy-atomicity guarantee because the message can be across cache lines, the message may have to pass through the PCIe and other buses, and the message might have to be retransmitted because of error.
> 
> With all above cases, I’m not convinced that we can implement shmem_p with single-copy-atomicity guarantee for current architectures in a reasonable way. Can you please shed more light on this, if you think otherwise ? If for current architectures, the only guarantee we can provide is multi-copy-atomicity (like shmem_atomic_set) then why can’t we just use shmem_atomic_set for signaling purposes.

@manjugv you can but it is slow

**Comment by anshumang** [comment]
@manjugv @shamisp @jdinan
have we reached an agreement?
- `shmem_p` will continue to be a valid synchronizing operation
- `shmem_p` will change to single-copy atomic

**Comment by manjugv** [comment]
> * `shmem_p` can be implemented as `shmem_atomic_set`. Why do you say that is _not_ reasonable?

As far as I understand, shmem_atomic_set provides multi-copy-atomicity guarantee not a single-copy-atomicity guarantee. So it is not the same. Is your intention to provide only multi-copy-atomicity guarantee ?

**Comment by manjugv** [comment]
> > If for current architectures, the only guarantee we can provide is multi-copy-atomicity (like shmem_atomic_set) then why can’t we just use shmem_atomic_set for signaling purposes.
> 
> * `shmem_p` is used for synchronization. Do we want to break existing code?

@anshumang We are not breaking anything IMO. shmem_p is just a data transfer operation. If shmem_wait completes on it so be it.

**Comment by anshumang** [comment]
@manjugv 
> As far as I understand, shmem_atomic_set provides multi-copy-atomicity guarantee not a single-copy-atomicity guarantee. So it is not the same. Is your intention to provide only multi-copy-atomicity guarantee ?
My understanding is : if you have multi-copy atomicity, you also have single-copy atomicity with a same or different ordering

> We are not breaking anything IMO. shmem_p is just a data transfer operation. If shmem_wait completes on it so be it.
I don't follow you here. We **are** saying that `shmem_put` (and `shmem_put_nbi`, `shmem_iput`) and stores are not valid operations to complete `shmem_wait_until`. If existing code were using these, they would break. `shmem_p` needs an **atomic update property** to not break existing code.

**Comment by shamisp** [comment]
@anshumang Or we can leave it as it is.
shmem_p can be used if the app does not depend on observing full transaction and shmem atomic ops can be used when atomic update is required ?

**Comment by anshumang** [comment]
@shamisp 

> shmem_p can be used if the app does not depend on observing full transaction

I think then the specification should say synchronization using shmem_p is not supported.

**Comment by shamisp** [comment]
@anshumang why not ? It just set some notification bit on and off.

**Comment by anshumang** [comment]
@shamisp My concern is that the non-updated bits can be anything after the partial update. The spec should prohibit a partial update based synchronizing operation even if it happens to work.

**Comment by jdinan** [comment]
This was resolved for OpenSHMEM 1.5, thanks for all the insightful discussions.
