### ISSUE TITLE
What does "same ... and ... not overlapping" mean?

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#253]
In reductions, OpenSHMEM 1.4 states:

"The source and dest arrays may be the same array, but they may not be overlapping arrays."

Does this mean that:
1. The source and dest pointers must either be identical or correspond to different objects, or
1. The source and dest pointers may point to elements in the same array allocation, but they must not overlap in memory, or
1. Something else?

**Comment by spophale** [comment]
The sentence introduced in 1.4 suddenly moves away from symmetric objects and wants to be able to work with an object in fractions. It is okay if that is the route we want to go. But it needs to be consistent across the spec. 

When I read that in the spec I mentally corrected it to "The source and dest arrays may be the same array, but they may not be overlapping **sub-**arrays."  From reading of that sentence alone I would go with option 2.

**Comment by nspark** [comment]
Thinking about #266 also made me realize that we don't say anything about overlapping RMA operations. For example, which of the following RMA operations is well-defined...?

```c
const size_t nelems = ...;
int *sym_addr = shmem_calloc(nelems, sizeof(*sym_addr));
shmem_put(sym_addr    , sym_addr, nelems    , shmem_my_pe()); // Case 0
shmem_put(sym_addr + 2, sym_addr, nelems - 2, shmem_my_pe()); // Case 1
```

Now, throw `shmem_ptr` into the mix and...?
```c
const int nbr = (shmem_my_pe() + 1) % shmem_n_pes();
const size_t nelems = ...;
int *sym_addr = shmem_calloc(nelems, sizeof(*sym_addr));
int *nbr_addr = shmem_ptr(sym_addr, nbr);
if (nbr_addr)
  shmem_put(sym_addr, nbr_addr, nelems, nbr); // Case 3
```

**Comment by nspark** [comment]
It's worth noting that the statement for reductions that:

> `source` and `target` may be the same array, but they must not be overlapping arrays

goes all the way back to OpenSHMEM 1.0.

**Comment by davidozog** [comment]
> Thinking about #266 also made me realize that we don't say anything about overlapping RMA operations. For example, which of the following RMA operations is well-defined...?
> 
> ```c
> const size_t nelems = ...;
> int *sym_addr = shmem_calloc(nelems, sizeof(*sym_addr));
> shmem_put(sym_addr    , sym_addr, nelems    , shmem_my_pe()); // Case 0
> shmem_put(sym_addr + 2, sym_addr, nelems - 2, shmem_my_pe()); // Case 1
> ```

@nspark / @jdinan - I'm a little unsure of RMA overlap restrictions...  My apologies, I remember it coming up in discussion, but don't remember the exact conclusion.

Overlapped RMA (either complete or partial) is undefined in OpenSHMEM v1.5, correct?

From this (Section 4.2 v1.5):
```quote
Pointer arguments to OpenSHMEM routines that point to non-const data must not overlap in memory with other
arguments to the same OpenSHMEM operation, with the exception of in-place reductions as described in Section 9.9.9.
```

So for `shmem_put`, `dst` is a non-const pointer arg, so `dst` must not overlap with `source` or any other argument of `shmem_put`.  Is that interpretation correct?  If so, what is the reason for prohibiting overlap?

**Comment by jdinan** [comment]
The behavior is undefined when `src` and `dst` overlap, even for things like [memcpy](https://man7.org/linux/man-pages/man3/memcpy.3.html).
