### ISSUE TITLE
`ivar` argument type in point-to-point synchronization routines

### ISSUE THREAD

**Issue by akhillanger** [openshmem-org/specification#260]
`ivar` has been identified as an `OUT` argument in `shmem_wait/test*` routines description, when it is actually an `IN` argument. Is this a typo?
[OpenSHMEM 1.4](http://www.openshmem.org/site/sites/default/site_files/OpenSHMEM-1.4.pdf)

**Comment by jdinan** [comment]
This is a bug.  @davidozog did it correctly in #214, but I think we may need a separate PR to fix the existing routines.

**Comment by naveen-rn** [comment]
Should we close this issue? We have already fixed this.

**Comment by davidozog** [comment]
Yes - thanks @naveen-rn.
