### ISSUE TITLE
Header restrictions are too restrictive

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#262]
We are finding the following restriction to be too restrictive:

"The OpenSHMEM header files shmem.h for C and shmem.fh for Fortran must contain only the interfaces and constant names defined in this specification."

This doesn't appear to leave room for the implementation to define any internal bits in these headers.  For example, SOS uses the following definition for `shmem_ctx_t`.  A `struct` is used to ensure a unique type for use in C11 generic selection:

```
typedef struct { int dummy; } * shmem_ctx_t;
```

For compatibility with C++ and C99 we need to name this structure (anonymous structures are officially supported starting in C11).  However, the above requirement seems to suggest we can't introduce a name that is not part of the official API.

**Comment by jdinan** [comment]
Related to #336

**Comment by RaymondMichael** [comment]
Jim can you add a proposed solution?

**Comment by jdinan** [comment]
Closed by https://github.com/RaymondMichael/specification/pull/23
