### ISSUE TITLE
Clarification on pWrk in reduction calls

### ISSUE THREAD

**Issue by akhillanger** [openshmem-org/specification#264]
In the blocking reduction description the spec says (Page 83 in `OpenSHMEM` 1.4) - 

`Upon return from a reduction routine, the following are true for the local PE: The dest array is updated and the source array may be safely reused. The values in the pSync array are restored to the original values.`

The text does not say anything about the `pWrk` array after return from the reduction call. It needs to be clarified that `pWrk` is free to be used for other purposes after the return from the reduction call. 

There may be other places where the same may apply.

**Comment by manjugv** [comment]
@akhillanger Since we are depcreating pwork with Teams proposal, should we close this?

**Comment by akhillanger** [comment]
Sure. Thanks.
