### ISSUE TITLE
Global visibility effect of shmem_quiet

### ISSUE THREAD

**Issue by anshumang** [openshmem-org/specification#265]
Assume x and y are symmetric objects

```
PE 1 : x = 0, y = 0                 PE 2: x = 0, y = 0               PE 3 : x = 0, y = 0
A : shmem_p(&x, 1, 2)                                                 D : shmem_wait_until(&y, 1, CMP_EQ)
B : shmem_quiet()                                                     E : shmem_g(&x, 2) //should return 1 or 0?
C : shmem_p(&y, 1, 3)

```

Is the specification clear about `shmem_g` returning 1?

Note that this is a happens before relation per the memory model proposal draft (A is ordered before C at PE 1 and D at PE 3 reads from C and this implies A happens before E).

**Comment by anshumang** [comment]
ping @jdinan @manjugv following up on RMA WG 2/14/2019 discussion

**Comment by spophale** [comment]
Yes, the current specification is clear on the point that when shmem_quiet returns shmem_p on PE 1 is visible to all PEs. A happens before C and D waits on C, so we can assume that A happens before E.

**Comment by bcernohous** [comment]
I think we had some discussions a few months ago, I don’t remember the venue, about reordering put/gets like a CPU(weak)/compiler might reorder stores/loads.

So maybe the question, and the clarification needed, is can C be reordered before B?   Is shmem_quiet also a “compiler fence”/”sfence”/C++11 semantic?



PE 1 : x = 0, y = 0

A : shmem_p(&x, 1, 2)

B : shmem_quiet()

C : shmem_p(&y, 1, 3)

Imagine shmem_p is simple a macro for store on a single node, shared memory SHMEM.  Could a compile move them?  Or is shmem_quiet a macro for sfence?

If it can move, then you cannot guarantee AC ordering even if you guarantee global visibility of A (and a later quiet guarantees gv of C).   So I think the reasonable spec decision is “No, can’t move up past a quiet”.

Maybe that’s already obvious and this isn’t really the question.  But if this isn’t the question, then I think the obvious answer is A is ordered before E.

**Comment by anshumang** [comment]
@bcernohous I assumed the following in my question.

> “No, can’t move up past a quiet”

So what I wanted to clarify is this-

> But if this isn’t the question, then I think the obvious answer is A is ordered before E.

**Comment by shamisp** [comment]
Since shmem_quiet explicitly states that it requires completion and global visibility of store operations/instructions, it is reasonable to assume that shmem quiet invokes store barrier instruction. Implementation wise it also makes sense to place instruction barrier (for arch that requires this)

**Comment by manjugv** [comment]
> ping @jdinan @manjugv following up on RMA WG 2/14/2019 discussion

@anshumang Yes, I agree that A happens before C. I don't see an issue here.

**Comment by bcernohous** [comment]
Right, so if that assumption is accepted, then in the example A is visible at B.  Anything dependent on C *has* to see A.  I’m not seeing any ambiguity.

**Comment by anshumang** [comment]
@manjugv Does this example capture the 3-way transfer and sync that was discussed in RMA WG 2/14/2019? My understanding is that `shmem_barrier` across the 3 PEs is not required to guarantee `happens before`.

**Comment by manjugv** [comment]
@anshumang In this example, I do agree. But, I'm not sure we can generalize it.

**Comment by anshumang** [comment]
@manjugv Why not? Intuitively, it seems to me that if this holds for 3 PEs, it will also hold for N PEs. Are you looking for a more rigorous/formal proof?

**Comment by shamisp** [comment]
We can alway include an example describing the 3way test. If you want to generalize this, you would have to define litmus test and expected results for each combinations. This is probably the only formal way to define this.

**Comment by manjugv** [comment]
@anshumang 3-way transfer is not well defined concept. Can you precisely define 3-way transfer, so we can see if what you say extends beyond your example ? IMO, what you are quoting is an example of 3-way transfer. That is a point I was trying to make.

**Comment by naveen-rn** [comment]
I suppose this is not for OpenSHMEM-1.5.

**Comment by jdinan** [comment]
I'm not sure there is a task left here, given the clarifications we have made in OpenSHMEM 1.5. I will assign this issue to myself and take the task of reviewing this against the clarified memory model and capturing the example as part of some memory model tests.
