### ISSUE TITLE
Clarify the remote accessibility of the returned value of shmem_ptr

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#266]
This ties into some of @anshumang's work with `shmem_wait` and the memory model, but I thought it might be worth addressing a little more broadly (i.e., it's not only contained to the `shmem_wait` API family).

Currently, the Specification says that:

> `shmem_ptr` returns an address that may be used to directly reference `dest` on the specified PE. This address can be assigned to a pointer. After that, ordinary loads and stores to this remote address may be performed.

It seems ambiguous what it means for the returned pointer value to be a "remote address". (AFAICT, this term isn't used or defined elsewhere in the Specification.) I don't think we mean that this is a suitable address to a remotely accessible object for the purposes of OpenSHMEM operations such as RMA, AMO, and collectives. Yet, we've termed it something very similar.

That said, I think we would all expect that the following code would (or should) not be valid:

```c
const int nbr = (shmem_my_pe() + 1) % shmem_n_pes();
const size_t nelems = ...;
int *lcl_addr = calloc(nelems, sizeof(*lcl_addr));
int *sym_addr = shmem_calloc(nelems, sizeof(*sym_addr));
int *nbr_addr = shmem_ptr(sym_addr, nbr);
if (nbr_addr)
  shmem_put(nbr_addr, lcl_addr, nelems, nbr);
```

So, I think we should clarify the difference between pointers to remotely accessible objects as returned by `shmem_{malloc, calloc, realloc, align}` vs those returned by `shmem_ptr`, while also keeping in mind that a call like `shmem_ptr(sym_addr, shmem_my_pe())` will likely (must?) return the value of `sym_addr` itself.

**Comment by jamesaross** [comment]
```c
int me = shmem_my_pe();
int next_pe  = (me + 1) % shmem_n_pes();
int* foo = shmem_malloc(128); // foo is a local address
int* bar = shmem_ptr(foo, next_pe); // bar is a global (remote) address
foo = shmem_ptr(foo, me); // foo is now either a local address or "global-local address"
int* fubar = shmem_ptr(foo, next_pe); // presently, this cannot be expected to work
```
The pointer returned from calling `shmem_ptr(sym_addr, shmem_my_pe())` is ambiguous within the standard. Why shouldn't it return the global-local address in order to be consistent rather than a special case of returning the value of `sym_addr` itself?

**Comment by nspark** [comment]
I agree that the result (`foo = shmem_ptr(foo, me)` in your example) is ambiguous as to whether this is valid for use as a remote address. I see no reason that `shmem_ptr(addr, shmem_my_pe())` shouldn't be required to return `addr` in the case that `addr` is a symmetric address to a remotely accessible object.

**Comment by nspark** [comment]
I agree that the result (`foo = shmem_ptr(foo, me)` in your example) is ambiguous as to whether this is valid for use as a remote address. I see no reason that `shmem_ptr(addr, shmem_my_pe())` shouldn't be required to return `addr` in the case that `addr` is a symmetric address to a remotely accessible object.

**Comment by jdinan** [comment]
@nspark I think we resolved this in #276. Could you please check and close if this is resolved?

**Comment by jdinan** [comment]
@nspark Could you please check whether this issue is resolved?

**Comment by nspark** [comment]
@jdinan I think #276 resolves the example in the opening comment, but it _does not_ resolve the following "questionably allowed" example:

```c
const int mype = shmem_my_pe();
const int npes = shmem_n_pes();
long *sym_flag = shmem_calloc(1, sizeof(long));
long *lcl_flag = shmem_ptr(sym_flag, mype);
assert(lcl_flag != sym_flag);

if (mype == 0) {
  shmem_wait_until(sym_flag, SHMEM_CMP_EQ, npes - 1); // clearly allowed
  shmem_wait_until(lcl_flag, SHMEM_CMP_EQ, npes - 1); // questionably allowed
}
else {
  shmem_atomic_add(sym_flag, 1, 0);
}
```

Do we want to prohibit such behavior?

As of 1.5rc1, `shmem_wait_until` expects `ivar` to be a "local address of a remotely accessible data object," and `shmem_ptr` returns "a local address to a remotely accessible data object."

Proposed fix: Require `shmem_wait_until` and friends to require `ivar[s]` to be a "symmetric address of a remotely accessible data object."

**Comment by nspark** [comment]
Closing, as #276 does indeed clarify the specifics of this issue
