### ISSUE TITLE
shmem_pcontrol "const" level

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#268]
## Summary

Follow-up needed on PR #254

The new `shmem_pcontrol(const int level, ...)` function places the `const` qualifier on the `level` argument.  This was [discussed on the PR](https://github.com/openshmem-org/specification/pull/254/files/7a5bcdb6dacd203373624ec180770189a5e8f5cd#r236932839) but has not been resolved.

## Action Needed

The proposal was merged with `const level` to maintain consistency with the same function in MPI.  Before the OpenSHMEM 1.5 release, the committee should decide whether to keep `const` or remove it (e.g. via section committee).

**Comment by wrrobin** [comment]
Discussed in wrrobin#2

**Comment by wrrobin** [comment]
Resolved in #387
