### ISSUE TITLE
SHMEM Reduction Operations

### ISSUE THREAD

**Issue by jamesaross** [openshmem-org/specification#279]
In the Teams Proposal discussion on August 22, it became apparent that some typed reduction operations, although well defined in C, are not supported by the OpenSHMEM API.  For example, the min/max/product/sum of unsigned char types.  The types supported by reductions are not as full featured as the Standard RMA Types.  So should reduction operations support all Standard RMA types where the operations make sense?

**Comment by manjugv** [comment]
Should be closed before PR #280

**Comment by jdinan** [comment]
@jamesaross IIUC, this should have been closed by the addition of team collectives. Does the set of types added address this issue?

**Comment by jamesaross** [comment]
The unsigned char type continues not to have min/max/sum/prod.
https://github.com/gmegan/specification/blob/7df7b170d1f2a14063175e64e8ee966bdb058755/content/shmem_reductions.tex

Reduction operations exist for these RMA types:
```
unsigned char
short
int
unsigned int
long
unsigned long
long long
unsigned long long
float
double
long double
double Complex
float Complex
```

Reduction operations *do not exist* for these RMA types:
```
char
signed char
unsigned short
int8_t
int16_t
int32_t
int64_t
uint8_t
uint16_t
uint32_t
uint64_t
size_t
ptrdiff_t
```

I don't feel strongly about adding them to 1.5.  It's just seemed logically inconsistent to support some C types for RMA and not for reductions.

**Comment by jdinan** [comment]
Assigning to RMA section committee.

**Comment by jamesaross** [comment]
@nspark, your improvements look good to me.  I submitted pull request #392 to fix the `short *pWrk` in the deprecated active set reductions.

How far does this kick back the 1.5 timeline to include the additional team reduction type support?

**Comment by nspark** [comment]
@jamesaross I'm not sure what you mean by delaying 1.5. I think we have a chance to revise the RC one more time before ratification. Thanks for catching the copy-paste error!

**Comment by jamesaross** [comment]
For those following along, in case it's not clear from the single referenced commit, the deprecated active set reductions (`shmem_[TYPENAME]_[OP]_to_all`) and team reductions (`shmem_[TYPENAME]_[OP]_reduce`) as they are today have the following type support:

| **TYPE** | **TYPENAME** | (*Operations* | *Supporting* | *TYPE*) |
|------|------|------|------|------|
| unsigned char | uchar | AND, OR, XOR | | |
| short | short | AND, OR, XOR | MAX, MIN | SUM, PROD |
| unsigned short | ushort | AND, OR, XOR | MAX, MIN | SUM, PROD |
| int | int | AND, OR, XOR | MAX, MIN | SUM, PROD |
| unsigned int | uint | AND, OR, XOR | MAX, MIN | SUM, PROD |
| long | long | AND, OR, XOR | MAX, MIN | SUM, PROD |
| unsigned long | ulong | AND, OR, XOR | MAX, MIN | SUM, PROD |
| long long | longlong | AND, OR, XOR | MAX, MIN | SUM, PROD |
| unsigned long long | ulonglong | AND, OR, XOR | MAX, MIN | SUM, PROD |
| float | float | | MAX, MIN | SUM, PROD |
| double | double | | MAX, MIN | SUM, PROD |
| long double | longdouble | | MAX, MIN | SUM, PROD |
| double _Complex | complexd | | | SUM, PROD |
| float _Complex | complexf | | | SUM, PROD |

The issue is to expand the type support for just the team reductions (`shmem_[TYPENAME]_[OP]_reduce`) to have the following type support (below).  Are we missing bitwise AND, OR, and XOR operation support in this table for char, signed char, short, int, long, long long, and ptrdiff_t?

| **TYPE** | **TYPENAME** | (*Operations* | *Supporting* | *TYPE*) |
|------|------|------|------|------|
| char | char | | MAX, MIN | SUM, PROD |
| signed char | schar | | MAX, MIN | SUM, PROD |
| short | short | | MAX, MIN | SUM, PROD |
| int | int | | MAX, MIN | SUM, PROD |
| long | long | | MAX, MIN | SUM, PROD |
| long long | longlong | | MAX, MIN | SUM, PROD |
| ptrdiff_t | ptrdiff | | MAX, MIN | SUM, PROD |
| unsigned char | uchar | AND, OR, XOR | MAX, MIN | SUM, PROD |
| unsigned short | ushort | AND, OR, XOR | MAX, MIN | SUM, PROD |
| unsigned int | uint | AND, OR, XOR | MAX, MIN | SUM, PROD |
| unsigned long | ulong | AND, OR, XOR | MAX, MIN | SUM, PROD |
| unsigned long long | ulonglong | AND, OR, XOR | MAX, MIN | SUM, PROD |
| int8_t | int8 | AND, OR, XOR | MAX, MIN | SUM, PROD |
| int16_t | int16 | AND, OR, XOR | MAX, MIN | SUM, PROD |
| int32_t | int32 | AND, OR, XOR | MAX, MIN | SUM, PROD |
| int64_t | int64 | AND, OR, XOR | MAX, MIN | SUM, PROD |
| uint8_t | uint8 | AND, OR, XOR | MAX, MIN | SUM, PROD |
| uint16_t | uint16 | AND, OR, XOR | MAX, MIN | SUM, PROD |
| uint32_t | uint32 | AND, OR, XOR | MAX, MIN | SUM, PROD |
| uint64_t | uint64 | AND, OR, XOR | MAX, MIN | SUM, PROD |
| size_t | size | AND, OR, XOR | MAX, MIN | SUM, PROD |
| float | float | | MAX, MIN | SUM, PROD |
| double | double | | MAX, MIN | SUM, PROD |
| long double | longdouble | | MAX, MIN | SUM, PROD |
| double _Complex | complexd | | | SUM, PROD |
| float _Complex | complexf | | | SUM, PROD |

**Comment by nspark** [comment]
As of 1.5rc1, the team-based reductions use Table 9:

![reduction-types](https://user-images.githubusercontent.com/2961664/76346765-ec4c3a80-62db-11ea-9c24-1f78ce734be8.png)

Whereas, the active-set-based reductions use Table 10:

![reduction-types-aset](https://user-images.githubusercontent.com/2961664/76346987-3f25f200-62dc-11ea-9d0d-af2d71157e0c.png)

Unless I'm misunderstanding something, this seems like 1.5rc1 has what you want.

**Comment by nspark** [comment]
> Are we missing bitwise AND, OR, and XOR operation support in this table for char, signed char, short, int, long, long long, and ptrdiff_t?

No, those are intentionally omitted. The bitwise operations for AMOs on these types were excluded because they're not guaranteed to have twos-complement representations. (This may change in C++next and get some future C standard.) So, in keeping consistent with the AMOs, we omitted bitwise operations on signed types not explicitly specified as having a twos-complement representation.

**Comment by jamesaross** [comment]
You're not misunderstanding something. This is what I want.  I was mistaken and looking at an older draft of the PDF, not the 1.5rc1 that Jim emailed. Thank you, Nick.

**Comment by jdinan** [comment]
@jamesaross Thanks for following-up and working through this -- really appreciate the careful attention to detail!
