### ISSUE TITLE
DocEdit: Check phrasings for "routines ((word))"

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#284]
Forking from https://github.com/openshmem-org/specification/pull/247#pullrequestreview-292451615

From the current master, running:
```terminal
grep "routine[s]* [^ ]*" content/*
```
gives about 200 instances that should be manually checked for grammar and past-vs.-present tense

Also, 
```terminal
grep "operation[s]* [^ ]*" content/*
```
should be checked, though the term "operation" is a more fluid than our use of "routine". #228

**Comment by jdinan** [comment]
Delay until #228 defines routine and operation.

**Comment by jdinan** [comment]
I reviewed the relevant passages from the spec and didn't see anything that needs to be edited. There are a lot, so I wouldn't be surprised if I missed something, but there does not seem to be a high error density in the output of the above greps as suggested on the ticket (or perhaps the chapter committees already fixed them).
