### ISSUE TITLE
Specify domain of atomicity w.r.t. contexts and teams

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#288]
At the 9/24 F2F, the domain of atomicity for OpenSHMEM AMOs was raised with respect to contexts and teams: Are AMOs (on the same data type and address) atomic...

- ...across all contexts regardless of the team from which they were created?
- ...only across contexts created from the same team?

This has relevance to the Teams proposal #280 and multi-rail NICs.

**Comment by nspark** [comment]
@naveen-rn and @jdinan: suggested adding that "atomicity is guaranteed regardless of the context that is used" (to imply that AMOs issued on contexts created from different teams are mutually atomic).

**Comment by nspark** [comment]
Tagging @gmegan

**Comment by BryantLam** [comment]
Related https://github.com/gmegan/specification/issues/152

**Comment by jdinan** [comment]
Closed by #306
