### ISSUE TITLE
Teams: Error Handling

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#292]
Related https://github.com/gmegan/specification/issues/139

From discussion of Teams at Sep 2019 F2F, this issue notes that the Teams feature needs to clarify the current error-handling behaviors.

**Comment by agrippa** [comment]
I can't find the text mentioned in https://github.com/gmegan/specification/issues/139 anywhere in Section 9.4 of the current version of the spec. Is it possible this text has already been changed and this issue is out of date?

**Comment by jdinan** [comment]
It looks like the text was changed to the following:
> Team handle error checking and integer return codes are currently undefined. Implementations may define these behaviors as needed, but programs should ensure portability by doing their own checks for invalid team handles and for SHMEM_TEAM_INVALID.

@agrippa Looks to me like we can close this issue (and gmegan#139).
