### ISSUE TITLE
Teams: Vendor additions to shmem_team_config_t

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#293]
Related https://github.com/gmegan/specification/issues/153

From discussion of Teams at Sep 2019 F2F, this issue notes that the Teams feature needs to clarify the behavior of implementation-specific options in the `shmem_team_config_t` struct.

**Comment by shamisp** [comment]
@BryantLam Is there community agreement on this ? I was not present at the meeting ?

**Comment by BryantLam** [comment]
@shamisp - From the full-group discussion at the Sep 2019 F2F, I filed this issue as an action item for the Teams working group. I don't think a conclusion was reached that day.

**Comment by naveen-rn** [comment]
Duplicate issue https://github.com/openshmem-org/specification/issues/342 - closing the other issue - as this has more discussion traffic

**Comment by shamisp** [comment]
@BryantLam - I think we have two separate issues here.
1. Do we allow vendor specific extension within existing text. I don't think we prohibit this explicitly but I don't think we have spell this out in the text.

2. Current ```int shmem_team_get_config(shmem_team_t team, shmem_team_config_t *config)```
does not pass config mask as a separate argument and as a result binary backward compatibility is not possible. We have two options here: 
* integrate the mask into shmem_team_config_t. We woold have to remove config_mask from all the rest team create/split APIs

* add mask only to the shmem_team_get_config

We would have to community to agree on one of the changes. Either way it is change for API.

**Comment by naveen-rn** [comment]
> integrate the mask into shmem_team_config_t. We woold have to remove config_mask from all the rest team create/split APIs

+1

**Comment by BryantLam** [comment]
@shamisp - Oops. You're correct. This issue is specifically about vendor extensions. I personally would favor consistency and if the other APIs already have `config_mask`, adding it here to `shmem_team_get_config` is reasonable.

**Comment by shamisp** [comment]
Proposed #363 please take a look and comment.

**Comment by jdinan** [comment]
If we feel that users setting the config mask is too bothersome, we can add a compile time constant `SHMEM_TEAM_CONFIG_MASK_ALL` that users can pass to query all fields. Since it is a compile time constant from the SHMEM library used to build the application, implementations can set the bits so that it is forward compatible with future ABI as we have discussed.

**Comment by shamisp** [comment]
Patch moved here https://github.com/jdinan/specification/pull/9
