### ISSUE TITLE
Teams: Triplet-based ordering?

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#294]
Related https://github.com/gmegan/specification/issues/154 https://github.com/gmegan/specification/issues/131
Duplicate of #285 

From discussion of Teams at Sep 2019 F2F, this issue notes that the Teams feature needs to (possibly) clarify the current behavior for triplet-based ordering versus relaxed ordering.

This issue affects whether `SHMEM_TEAM_SHARED` can/should/must be represented by a triplet and potential behavioral implications on currently defined behavior for `shmem_ptr`.

One comment expressed by @nspark and @jdinan was that if relaxed ordering is used, the `team_split` API could have been specified with the more generic `split_color`-like API.

**Comment by jdinan** [comment]
Decision was made to use tripled-based ordering.
