### ISSUE TITLE
Teams and Undefined Behavior

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#296]
Update the undefined behavior annex to cover common cases with teams.

For example, the undefined behavior annex covers using an invalid PE id. We could add a row to cover the case where the PE id is valid, but not a member of the given team (e.g. in and RMA operations, as the root in a broadcast, etc.).

**Comment by davidozog** [comment]
Addressing here:
https://github.com/davidozog/openshmem-specification/tree/sec/backmatter-undefined_teams_behavior

and open to suggestions!

**Comment by BryantLam** [comment]
Closed by https://github.com/BryantLam/openshmem-specification/pull/4 (merged).
