### ISSUE TITLE
Teams Changelog Entry

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#301]
Add changelog entry for #297

**Comment by BryantLam** [comment]
Closed. Resolved by https://github.com/BryantLam/openshmem-specification/pull/12.

**Comment by BryantLam** [comment]
Merge conflict in Section Collectives v1.5rc1

**Comment by jdinan** [comment]
@BryantLam Could you create a PR to remove the changelog from the collectives section and a separate PR to add it to the back matter section?
