### ISSUE TITLE
Fixed-width integer bindings for reductions

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#311]
Teams reduction operations don't have bindings for fixed-width integer types (e.g. `int32_t`).  Do users need support for these types?

**Comment by nspark** [comment]
Here's the path we're taking...

- Split the reduction types table between team- and active-set-based reductions
- Add type support for fixed-width integer types (including `size_t` and `ptrdiff_t`) to team-based reductions
- Set the type support for active-set-based reductions as matching the API of OpenSHMEM 1.4; i.e., 1.5 will not add any new active-set reduction types.

Here's the main point of feedback we're seeking:

- Do we add support (or not) for bitwise operations in team-based reductions for C's standard signed integer types (i.e., `char`, `signed char`, `short`, `int`, `long`, `long long`)? These types are not required to be twos-complement and bitwise operations may not be supported on them on all architectures.

**Comment by nspark** [comment]
Closed by 1.5rc1
