### ISSUE TITLE
Copyright/Use Statement

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#313]
## Issue

This came up while incorporating new teams tests into our test suite.

We seem to be missing a statement regarding how the content of the OpenSHMEM specification may be used.  Here is the current IP statement in the OpenSHMEM specification:

> The OpenSHMEM specification belongs to Open Source Software Solutions, Inc. (OSSS), a non-profit organization, under an agreement with HPE. For a current list of Contributors and Collaborators, please see http://www.openshmem.org/site/Contributors/. We gratefully acknowledge support from Oak Ridge National Laboratory’s Extreme Scale Systems Center and the continuing support of the Department of Defense.

SOS uses the text from the specification verbatim in our manpages and also incorporates example programs into our test suites.  The intent of OpenSHMEM is to allow the community to use the spec in this way, but our IP statement doesn't grant us permission to do this.  IIUC, we need some sort of use statement to go alongside the IP ownership statement to enable this.

**Comment by jdinan** [comment]
The original issue didn't do a good job of capturing my concern.  I updated the text to hopefully better capture the issue that we ran into while incorporating new teams examples into the SOS test suite.

**Comment by RaymondMichael** [comment]
We could tack on something like, "The contents of this specification, including the code examples, are free to be included in other publications. A copy of this copyright must accompany them."

**Comment by jdinan** [comment]
This may be too restrictive, since it's necessary to make some modifications in order to include the text in manpages (or a user guide) and runnable unit tests. Also, it would be great to introduce a normal copyright statement (e.g. Copyright (C) 2020 OSSS).

**Comment by jdinan** [comment]
@RaymondMichael @swpoole Any chance of incorporating guidance on use in OpenSHMEM 1.5? This came up again recently while working on documentation -- the implications of copying text or examples from the spec are unclear. As an example, the following is adapted from the BSD license:

```
Redistribution of the contents of this document, with or without modification, is permitted provided
that the following conditions are met:

1. Redistributions must contain a reference to this document.

2. Neither the name of the copyright holder nor the names of its contributors may be used to endorse
or promote products derived from this software without specific prior written permission.
```

**Comment by jdinan** [comment]
@RaymondMichael @swpoole A corollary to this request would be to include an open source LICENSE file in the LaTeX source tree that we have posted on GitHub. This file isn't included in the PDFs that we publish, so there is no immediate need for it. But, if we were to feel comfortable using a BSD license (or any other license, just taking BSD as a commonly used example) for the sources, we could work backward from that to determine which terms should be put into the PDF.

**Comment by RaymondMichael** [comment]
We're starting to write up something for the lawyers to take a look at.

**Comment by RaymondMichael** [comment]
@jdinan, Devil's Advocate: Section 1 of the contributors' agreement says Contributions are made available to others with a BSD-3 license. I read this as saying that the standard can be copied and modified. Admittedly, the statements in the specification, contributors' agreement, and the software license could be better harmonized.

**Comment by jdinan** [comment]
@RaymondMichael A BSD license included in the repository and also in the specification document would resolve all concerns on my end. Many thanks for taking up this task.

**Comment by jdinan** [comment]
@RaymondMichael Any progress on this?

**Comment by RaymondMichael** [comment]
HPE Legal approved adding the BSD license for the text of the standard. On Monday I'll work on adding the file to source directory.

**Comment by jdinan** [comment]
This is awesome -- thanks for making this happen @RaymondMichael!

Could you push the update to the copyright notice that we include in the built PDF to the front matter section branch? And post the license file as a separate PR to master?

@manjugv I would like to propose that we conduct a special ballot for the section committee change and a regular ballot for the license file.

**Comment by manjugv** [comment]
@jdinan I will add it to the agenda.

**Comment by RaymondMichael** [comment]
I think you're saying I should:
o Add a Copyright notice to the PDF file in the front matter branch
o Add the license file to the sources in the main branch

**Comment by jdinan** [comment]
@RaymondMichael In addition to the items you mentioned above, it would be good to also include the license text in the front matter, since this is what we ultimately distribute to consumers of the specification.

**Comment by jdinan** [comment]
In fact, I think that requirement 2 of the license requires us to include it in the PDF.

**Comment by jdinan** [comment]
Pushed to OpenSHMEM 1.6. OpenSHMEM 1.5 will include #428

**Comment by naveen-rn** [comment]
Change #508 is blocked. Need to re-prioritize based on the interest on this change. Waiting for progress from @swpoole.

**Comment by jdinan** [comment]
Considering #428 as having resolved this issue for now. Follow-up on #508.
