### ISSUE TITLE
Add shmem_team_ptr

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#319]
## Issue

The `shmem_ptr` operation takes a PE argument that is always relative to `SHMEM_TEAM_WORLD`.

## Proposed Solution

Add team-based variant of `shmem_ptr` as suggested by @naveen-rn on #307. This function's PE argument is relative to the team argument:

`void * shmem_team_ptr(shmem_team_t team, void *ptr, int pe)`

**Comment by jdinan** [comment]
Missed the feature cutoff for OpenSHMEM 1.5, pushing to OpenSHMEM 1.6.

**Comment by agrippa** [comment]
@jdinan I can take this issue on as my first contribution to the spec.

Is there any contributors guide beyond opening a PR while remaining consistent with the macros and formatting of the rest of the document?

**Comment by jdinan** [comment]
Thanks @agrippa! The closest thing to a contributor guide I can think of is Chapter 3 of the [procedures document](http://openshmem.org/site/sites/default/site_files/procedures-1.1.pdf).
