### ISSUE TITLE
Remove "Short" and "unsigned Short" from the supported data types for Shmem_wait/Shmem_test APIs

### ISSUE THREAD

**Issue by rdesai16** [openshmem-org/specification#334]
I came across this issue while implementing vector APIs for shmem_test and shmem_wait. As of a recent change from PR #267 , shmem_wait and shmem_test only work with AMOs and based on this, the list of datatypes supported by both AMOs and wait/test APIs, should be the same. But currently that is not the case.

So basically the issue is that in current version, AMOs do not support data types "short" and "unsigned short" whereas wait/test APIs do. Hence, shouldn't we remove "short" and "unsigned short" from the supported data types list of wait/test APIs?

Any thoughts?

**Comment by jdinan** [comment]
👍 
I would suggest going a bit further and updating the wait/test routines to be defined according to the types in the extended AMOs table, removing the sync types table, and deprecating routines for the types not in the extended AMOs table. Will need to double check that the signal type is in the extended AMOs table.

**Comment by davidozog** [comment]
I agree that we definitely want to consider removing the point-to-point types table and replacing with the appropriate AMO table.  I would guess that we wouldn't want the floating point types in the extended AMOs table to be compatible with the p2p types though (due to FP equality issues...).  Are you thinking we support comparisons like `CMP_EQ` on FP types @jdinan?

And yeah, the signal type is only `uint64` which is in both the standard and extended AMO tables.

**Comment by jdinan** [comment]
Yikes, good point about the floating point types.

**Comment by naveen-rn** [comment]
> Will need to double check that the signal type is in the extended AMOs table.

Please clarify.

**Comment by davidozog** [comment]
> > Will need to double check that the signal type is in the extended AMOs table.
> 
> Please clarify.

I think @jdinan meant "standard" (not extended) AMOs table, and we need to assure the "signal type" (`uint64_t`) is covered by the proposed change - and it is.  I've posted that change [here](https://github.com/naveen-rn/specification/pull/3).

**Comment by naveen-rn** [comment]
Fixed in https://github.com/naveen-rn/specification/pull/3

**Comment by naveen-rn** [comment]
Can we close this issue? As the change is made in the above mentioned PR? @rdesai16

**Comment by jdinan** [comment]
The fix looks good. Did it also get a changelog entry?

**Comment by rdesai16** [comment]
@naveen-rn  Yes. The fix looks good and is merged so we can close this issue. We should just make sure of the changelog entry.

**Comment by jdinan** [comment]
Whoops, looks like we still need the changelog entry. Reopening.

**Comment by nspark** [comment]
@BryantLam Do you want to take this one? It seems you've had to resolve a lot of conflicts in the changelog already.

**Comment by BryantLam** [comment]
Can do.
