### ISSUE TITLE
shmem_team_config parameter taking void *pointer

### ISSUE THREAD

**Issue by naveen-rn** [openshmem-org/specification#342]
In SBU F2F, we discussed about adding a void *pointer inside the shmem_team_config parater - which can then be used by implementers to define their own team configuration parameters. I'm not sure whether it is added in the current 1.5 draft.

**Comment by jdinan** [comment]
Discussed at the Feb. 2020 FTF and IIRC the conclusion was that the config parameter is already intended to allow for implementation-defined extensions (fields), so adding a `void *` to the specification is not necessary.
