### ISSUE TITLE
Review APIs that take a team argument and verify they specify behavior for SHMEM_TEAM_INVALID

### ISSUE THREAD

**Issue by agrippa** [openshmem-org/specification#346]

**Comment by agrippa** [comment]
Most APIs that accept a team specify their behavior in the presence of an invalid team. Most of these APIs use consistent wording, e.g. "If team compares equal to SHMEM_TEAM_INVALID then ... If team is otherwise invalid, the behavior is undefined."

shmem_sync uses slightly different wording: "If an invalid team handle or SHMEM_TEAM_INVALID is passed to this routine, the behavior is undefined." This should be re-worded.

shmem_alltoalls, shmem_alltoall, and shmem_collect accept teams arguments but do not specify their behavior in the case of SHMEM_TEAM_INVALID or an otherwise invalid team. This needs to be added.

**Comment by agrippa** [comment]
Opened pull request https://github.com/openshmem-org/specification/issues/346

**Comment by jdinan** [comment]
@agrippa Are all of the edits merged to the respective sections? If so, please close this issue. Thanks!
