### ISSUE TITLE
Check and validate the examples in Teams section

### ISSUE THREAD

**Issue by wrrobin** [openshmem-org/specification#347]
Double-check for any changes with @davidozog or @wrrobin

**Comment by jdinan** [comment]
@davidozog @wrrobin Are there any changes on the SOS side that should be reflected in these spec examples?

**Comment by davidozog** [comment]
Please see https://github.com/jdinan/specification/pull/11

**Comment by jdinan** [comment]
Closed by @davidozog -- thanks!
