### ISSUE TITLE
Change reference of ptr to addr in memory alloc routines

### ISSUE THREAD

**Issue by manjugv** [openshmem-org/specification#351]
It seems like this PR #276 missed changes to memory alloc routines.

**Comment by agrippa** [comment]
An example change from PR #276 :

Old text: A pointer to the remotely accessible data object to be updated.
New text: Symmetric address of the destination data object.

We would like to make similar updates in 1.5, as it looks like the memory management routines were missed.

**Comment by agrippa** [comment]
Create a PR https://github.com/manjugv/specification/pull/16
