### ISSUE TITLE
Barrier All/Sync All in memory routines should be on SHMEM_TEAM_WORLD ?

### ISSUE THREAD

**Issue by manjugv** [openshmem-org/specification#352]

**Comment by agrippa** [comment]
With the addition of teams, we need to clarify that the barriers performed in shmem_malloc, free, realloc, calloc, malloc_with_hints are on SHMEM_TEAM_WORLD team.

**Comment by agrippa** [comment]
Addressed in https://github.com/manjugv/specification/pull/15
