### ISSUE TITLE
Revise contributors list to a versioned-over-time list

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#355]
For clarity and historical accuracy, we should update the contributors list to be versioned (e.g., 1.5, 1.4...) and preserve affiliations at the time of the release.

**Comment by RaymondMichael** [comment]
Looking at the current PR, this appears to be an add-only list. What are your thoughts for handling when people leave the effort or move between organizations?

**Comment by nspark** [comment]
I think listed affiliations should represent the contributor's affiliation at the time the time of their contribution. If a contributor moves between organizations during a release, then the listed affiliation should probably be their "final" affiliation. If a person stops contributing to OpenSHMEM, they will not be listed in future versions of the specification.

Examples:

- John D. works for XYZ Corp. and contributes to OpenSHMEM 1.3. He is listed as "John D., XYZ Corp." for contributing to OpenSHMEM 1.3.
- John D. continues contributing to OpenSHMEM 1.4, but changes companies to ABC Inc. (or XYZ Corp. gets bought by ABC Inc.). He is listed as "John D., ABC Inc." for contributing to OpenSHMEM 1.4.
- John D. contributes initially to OpenSHMEM 1.5, but only initially (e.g., duties change, switches companies, etc.). He is listed as "John D., ABC Inc." for contributing to OpenSHMEM 1.5.
- John D. is not listed for contributing to OpenSHMEM 1.6 and subsequent versions, unless he restarts activity.

How does that sound to you?

**Comment by RaymondMichael** [comment]
That works
