### ISSUE TITLE
Remove instance of "partial update"

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#357]
`shmem_signal_wait_until` includes:

> **Note to implementors**
> > Implementations must ensure that `shmem_signal_wait_until` do not return before the update of the memory indicated by `sig_addr` is fully complete. Partial updates to the memory must not cause `shmem_signal_wait_until` to return.

We've tried to remove references to "partial updates", and this is one lingering issue. Suggest:

> Implementations must ensure that **calls to** `shmem_signal_wait_until` do not return before the update of the memory indicated by `sig_addr` is ~~fully~~ complete. ~~Partial updates to the memory must not cause `shmem_signal_wait_until` to return.~~

**Comment by jdinan** [comment]
#358 was reverted, making a note here to cherry-pick the relevant commit from openshmem-org:master and merge into the relevant section committee's branch.

**Comment by jdinan** [comment]
@naveen-rn Has this issue been addressed?

**Comment by naveen-rn** [comment]
Issue closed as part of https://github.com/naveen-rn/specification/pull/5
