### ISSUE TITLE
The Fortran API should be deprecated

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#36]
As we frequently discuss, the Fortran API is not used and not particularly conformant Fortran anyway. The recommendation of those in the community with Fortran expertise is to use Fortran's `bind(C)` features to wrap the C API for OpenSHMEM. The Fortran API should be deprecated.

**Comment by jdinan** [comment]
Should we toss a coin on who gets to do the legwork?  :)

The easiest approach would be to add a deprecation note everywhere that we mention Fortran (e.g. on the line that says FORTRAN in the synopsis).  This is easy/fast, but it leaves all of the FORTRAN in place and we'll have to work around it until it's removed from the spec (or until we quarantine it in a future version of the spec).  Given that we want to deprecate ASAP and properly removing Fortran from the text will be tricky, I was thinking of trying to implement the deprecation in this way to see how it looks.  What do you think?

**Comment by jeffhammond** [comment]
Not it 😆 

I vote for the fast and easy approach of marking everything as deprecated and not trying to disentangle.

**Comment by nspark** [comment]
:+1: for marking deprecate in-place

**Comment by jdinan** [comment]
@swpoole Volunteered to take a first whack at this.

**Comment by manjugv** [comment]
@nspark Since this ratified, can we close this issue ?

**Comment by nspark** [comment]
@manjugv I was looking at this yesterday and wondered the same thing. Since #48 hasn't actually been merged -- I see now that there are merge conflicts I need to resolve -- then I think we should wait until the PR is merged.

**Comment by swpoole** [comment]
Now that it is ratified, YES, I will take the marking deprecation in place. I have suggested/urged the current FORTRAN folks to please work with their vendors to use bind(C) proposed solution. I am sure there will be marks, but longer term it will be best for code portability and growth. I am not going to specify a time when it can be "burnt with fire" ;-) but I will keep in constant contact with the FORTRAN folks. Currently, deprecation != removal.

**Comment by jdinan** [comment]
I added a cross-reference.  Github should close this issue automatically when #48 is merged.

**Comment by BryantLam** [comment]
Resolved with #48.
