### ISSUE TITLE
Replace default team with world team

### ISSUE THREAD

**Issue by minsii** [openshmem-org/specification#371]
The term "default team" is used in several sections. But it is unclear what the default team is unless read the definition in section 7. Library Handles. Replacing it with "world team" should fix this issue. The following sections should be updated:

- [x] Library Handles
- [x] Teams and context
- [x] RMA
- [x] Collectives
- [x] Memory management

**Comment by jdinan** [comment]
@minsii If all the changes are merged, could you please close this issue?

**Comment by minsii** [comment]
Github shows all merged :-)
