### ISSUE TITLE
Team Config Query Semantics

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#374]
## Issue

Clarify whether `shmem_team_get_config` returns the values provided in the config argument during team creation or the current (implementation defined) values for these parameters.

## Sub-Issues

Add a `SHMEM_TEAM_CONFIG_MASK_ALL` compile-time constant to make it easier to query/set all config parameters (for the given ABI that the application was compiled with).

Specify a `SHMEM_TEAM_NUM_CONTEXTS_ANY` constant that allows the user to specify that they will create contexts, but cannot specify how many.

Ref: https://github.com/jdinan/specification/pull/9

**Comment by shamisp** [comment]
@jdinan do you see this as 1.5 or 1.6 item ?

**Comment by jdinan** [comment]
Closed by #521
