### ISSUE TITLE
Deprecate Active Set Constants

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#375]
The active set collectives are deprecated in OpenSHMEM 1.5 and replaced by team-based collectives. However, I think we neglected to deprecate the constants (e.g. `SHMEM_SYNC_SIZE`) associated with these deprecated routines.

I believe there is work here both for front matter @RaymondMichael and back matter @BryantLam.

**Comment by RaymondMichael** [comment]
I created this PR for it, https://github.com/RaymondMichael/specification/pull/28
I'm having the problem I had before though, in that I can't assign reviewers to it.

**Comment by jdinan** [comment]
@RaymondMichael Will need to add the committee members as contributors on his fork (and they will need to accept) in order to be able to assign them as reviewers. Otherwise, you can just call them out by name in the discussion view and have them comment with their approval.

**Comment by jdinan** [comment]
Back matter work forked to #389
