### ISSUE TITLE
Clarify that in *mem routines, nelems is bytes

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#376]
User request to clarify that in the new *mem collective routines, `nelems` refers to number of bytes.

Ref: https://github.com/Sandia-OpenSHMEM/SOS/issues/936

**Comment by jdinan** [comment]
@nspark Can this be addressed by the collectives section committee?

**Comment by nspark** [comment]
Will do. It's worth noting that this ambiguity also exists for RMA routines.

**Comment by nspark** [comment]
@jdinan How does this look...?

![broadcast-bytes](https://user-images.githubusercontent.com/2961664/75396016-8619ed80-58c1-11ea-8433-11d72a94d6dd.png)

Or, would it be more clear to put this in the API description?

**Comment by jdinan** [comment]
What about in the `apiargument` description for `nelems`? I thought we had a routine that covers it there, but I'm not able to find it now.
```
    \apiargument{IN}{nelems}{The number of elements in \source and \dest arrays. For 
\FUNC{shmem\_broadcastmem}, elements are bytes and for an operation of fixed size $N$,
elements are $N/8$ bytes. }
```
This might be easy enough to apply to all of the *mem routines, what do you think?

**Comment by nspark** [comment]
I'm not crazy about those argument description sections, but it seems like a compact change.

**Comment by jdinan** [comment]
Thanks, agree that it's not ideal, but it looks like a change we can apply across the remaining routines without much trouble. If you'd like to include a top-level description, we could also add the `nelems` semantics to the front matter where we describe properties of buffers passed to OpenSHMEM operations.

**Comment by jdinan** [comment]
Pushing this issue to the RMA section, since the collective part of the fix is now resolved.

**Comment by nspark** [comment]
@shamisp Here's how we resolved this in the Collectives section:

**Comment by shamisp** [comment]
@jdinan do you have patch for this ?

**Comment by jdinan** [comment]
PR posted: https://github.com/shamisp/specification/pull/5
