### ISSUE TITLE
Remove cache management routines

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#378]
Should we remove the cache management routines section? IIRC, it started as deprecated in OpenSHMEM 1.0, but we kept it in because deprecated ≠ removed; however, we've since removed deprecated APIs, so it seems reasonable to consider taking it out entirely now.

Any thoughts?

**Comment by shamisp** [comment]
Remove.

**Comment by jdinan** [comment]
Please also add a changelog entry to mark the removal.

**Comment by BryantLam** [comment]
I don't think any Section owns this task so I'll take it since it affects backmatter the most.

**Comment by BryantLam** [comment]
Closed by:
- Frontmatter: https://github.com/RaymondMichael/specification/pull/29 (open)
- Backmatter: https://github.com/BryantLam/openshmem-specification/pull/9 (merged)
