### ISSUE TITLE
Review teams example programs

### ISSUE THREAD

**Issue by davidozog** [openshmem-org/specification#391]
I've proposed some changes to the teams example programs, and that PR is here on @jdinan's fork:

https://github.com/jdinan/specification/pull/11

Assuming these changes are appropriate/timely for the RC2 document, could I please get some feedback and a review from the Teams/Contexts section committee on that PR?  Thanks!

Related issue: #347.

**Comment by jdinan** [comment]
Suggestion on 3.20.2020 meeting -- example of team-based synchronization for a halo exchange.

**Comment by jdinan** [comment]
Closed by @davidozog -- thanks!
