### ISSUE TITLE
Make examples easier to read

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#397]
IMO, the examples are not so easy to read with the current choice of color stylings. Ideas to make it easier?

- Change the background color to 80% or 90% white instead of the current ~50% white.
- ...

**Comment by nspark** [comment]
Here are some samples to compare (the "Gray" example is the current background coloring):

![ExampleColoring](https://user-images.githubusercontent.com/2961664/76869889-58c8bb80-683f-11ea-94b2-ccb7b167fb94.png)

Does lightening the background help?

**Comment by nspark** [comment]
Another suggestion, a white background with a frame:

![ExampleFramed](https://user-images.githubusercontent.com/2961664/76871874-01781a80-6842-11ea-9d1f-22aaaa6043d8.png)

**Comment by jdinan** [comment]
@nspark @BryantLam Can we close this issue?
