### ISSUE TITLE
Update shmem_ctx_nostore definition

### ISSUE THREAD

**Issue by naveen-rn** [openshmem-org/specification#402]
The ```SHMEM_CTX_NOSTORE``` option definition is bit ambiguous. We have the following definition:

>Quiet and fence operations performed on the given context are not required to enforce completion and ordering of memory store operations. When ordering of store operations is needed, the ap- plication must perform a synchronization operation on a context without the SHMEM_CTX_NOSTORE option enabled.

In general, wrt to this definition, I understand what we mean by "memory store" operations. But recent discussions internally with some developers, lead to a confusion. As we don't have a standard definition for "memory store" it is ambiguous on whether we define the memory store here as a local op or on the remote op (PCIe to Memory by the memory controller). We might want to clarify that the memory store here is used as a simple local store operation and still the ordering/completion semantics has to be maintained for all network generated store operations on the remote process memory.

**Comment by jdinan** [comment]
In WG discussion, we had proposed adding the +text+ below:
> Quiet and fence operations performed on the given context are not required to enforce completion and ordering of memory store operations +performed by the application+. When ordering of store operations is needed, the ap- plication must perform a synchronization operation on a context without the SHMEM_CTX_NOSTORE option enabled.

**Comment by jdinan** [comment]
@naveen-rn Please review the change posted above.

**Comment by naveen-rn** [comment]
Changes looks fine with me.
