### ISSUE TITLE
List committee chairs in the credits

### ISSUE THREAD

**Issue by RaymondMichael** [openshmem-org/specification#405]
This issue will give us a space to discuss reorganizing the contributors list to highlight the committee chairs. This was brought up as an option at the recent board meeting.

I have a sandbox at #https://github.com/RaymondMichael/specification/pull/32 to play with different options. In my first prototype I'm listing everyone's organization every time they get mentioned. One improvement I'm thinking about is keeping the committee chair list simple with just their name and role, and having the trailing "everyone" list include the committee chairs with their organizations. The indention of the prototype is wonky, but that can get adjusted.

**Comment by jamesaross** [comment]
What about having special footnote-like symbols after names so that it can scale across versions?

In general, it seems like the "Current Authors and Collaborators" lists could be more compact so a new page doesn't get added per new version.  But I guess it's not at the level of a CERN Physical Review Letter yet.

Also, does it make sense to call the section "Current" when it lists some inactive people back to version 1.0?

**Comment by jdinan** [comment]
Looks good to me. I agree we should change the section heading from "Current Authors and Collaborators" to "Authors and Collaborators".

**Comment by RaymondMichael** [comment]
@jamesaross in regards to your footnote comment, do you mean that we should use those to indicate committee roles?

**Comment by jamesaross** [comment]
Yes, with the intention that prior and future versions committee roles could also be credited with common symbols.  It should be more compact.

Another idea could be to just have a generic section committee leader symbol since section names evolve.

**Comment by RaymondMichael** [comment]
I put together a prototype of the footnote approach. Let me know what you think.

https://github.com/RaymondMichael/specification/pull/32

**Comment by jamesaross** [comment]
Thanks, Raymond. I like the second approach more.

Quick comparison for people following along:

# First Approach
![image](https://user-images.githubusercontent.com/12766926/77760902-82d36800-700d-11ea-872d-2083f650c196.png)

# Second Approach
![image](https://user-images.githubusercontent.com/12766926/77760963-9c74af80-700d-11ea-8dec-9e565b3884b0.png)

**Comment by RaymondMichael** [comment]
I started new PR https://github.com/RaymondMichael/specification/pull/34 to clean up some internal bits. It has the same output as #2.

**Comment by jdinan** [comment]
@RaymondMichael Can this issue be closed?

**Comment by jdinan** [comment]
@RaymondMichael Closing this issue, please re-open if needed.
