### ISSUE TITLE
Unspecified error in shmem_team_destroy

### ISSUE THREAD

**Issue by jamesaross** [openshmem-org/specification#419]
Within the Notes of `shmem_team_destroy`, it lists:
> It is an error to destroy the world team or any other predefined team.

The issue is the method doesn't provide a return value to indicate an error.  The `shmem_team_split_strided` and `shmem_team_split_strided_2d` routines return 0 if successful and nonzero on error.

The prototype is:
`void shmem_team_destroy(shmem_team_t team);`

Possible solutions:
1. fix the issue by returning an error code?
    `int shmem_team_destroy(shmem_team_t team);`
2.  Change the text to say that destroying a predefined team is undefined behavior?

Elsewhere within `shmem_broadcast`, Notes specifies:
> Team handle error checking and integer return codes are currently undefined. Implementations may define these behaviors as needed, but programs should ensure portability by doing their own checks for invalid team handles and for SHMEM_TEAM_INVALID.

**Comment by jdinan** [comment]
I agree, this should be undefined behavior and not an error. This seems fine to handle as a document edit, if we decide to proceed with ratification next Monday.

**Comment by jamesaross** [comment]
Closed by passing #434
