### ISSUE TITLE
Collective APIs still describe "active set" routines (not deprecated)

### ISSUE THREAD

**Issue by aljo242** [openshmem-org/specification#438]
Looking at 1.5rc3.  This is my first issue for the spec so apologies if I am doing this incorrectly. 
 Collective routines like `shmem_collect()`, still discuss _PE_start_, _PE_size_, etc. in their API Descriptions.  The section on "Active-set based collectives" which introduces this terminology is marked as deprecated, so should the sections inside the individual API Descriptions be similarly deprecated?

It is possibly confusing because a reader will see that this info is deprecated in some sections and is not in others.

**Comment by manjugv** [comment]
IIRC, this was a deliberate choice. Tagging collectives section committee for their comments @jdinan @nspark @shamisp @davidozog .

**Comment by jdinan** [comment]
The function prototypes and argument descriptions for the deprecated
routines are also marked. I guess the question is whether we want to also
markup the active set text in the API description box. I believe it was a
deliberate choice not to mark this text since some of it applies to both
active set and team collectives.

**Comment by aljo242** [comment]
Yeah, I can see why that might have been done.  I'm not exactly what text that specifically discussed active sets applies to the team collectives though.  It's more like active set text is interspersed within the API descriptions, which makes it both hard to add deprecation markers, or hard to understand without them.  

A reader may skip over when active sets are introduced since that text is deprecated, then see that it is in an API description, and get confused.  I know this would require significant reorganization of text though, and might not be a priority.

**Comment by manjugv** [comment]
Discussed at the FRM meeting and closing for now.

**Comment by jdinan** [comment]
The committee felt that this will eventually be addressed when the now deprecated active set APIs are removed from the specification. If you have a suggestion in the meantime that would make the document clearer, please propose it.
