### ISSUE TITLE
Spec 1.5: typo/question in 9.4.3 SHMEM_TEAM_CONFIG_T

### ISSUE THREAD

**Issue by tonycurtis** [openshmem-org/specification#441]
> time. It is not a _guaruntee_

guarantee

> will be ignored, and the default value will be used instead. Therefore, a program _must only set the fields_

must set only ...?

seems a bit clearer.

**Comment by jdinan** [comment]
Could you post these edits as a PR? I'd be happy to merge them as a document edit.
