### ISSUE TITLE
Need for const and pointer for shmem_team_config_t in team creation operations

### ISSUE THREAD

**Issue by naveen-rn** [openshmem-org/specification#445]
The current APIs for strided and 2d split team creation - have the configuration parameter as ```const shmem_team_config_t *```. It is an input argument - so, it can be a simple ```shmem_team_config_t```. Not sure whether we need to pass by reference these configuration parameters.

**Comment by jdinan** [comment]
It sounds like you are suggesting passing the struct argument by value rather than by reference? This might be fine for how the struct is currently defined, but it could become a problem in the future. There are plenty of discussions online covering pro/con of passing structs by value.

**Comment by naveen-rn** [comment]
Stack usage (if struct gets bigger)
Performance in copying data
Binary compatibility with other compilers

Though, I don't see any forseable issues. But, to be safe, if these are anticipated issues, we are thinking about - looks fine to stick with the current syntax.

**Comment by jdinan** [comment]
@naveen-rn Can we close this issue?

**Comment by naveen-rn** [comment]
We can close - the reason for the pointer type is clear.
