### ISSUE TITLE
What team do memory management operations use?

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#458]
The memory management routines specify:

> The shmem_malloc, shmem_free, shmem_realloc, and shmem_align routines are collective operations that require participation by all PEs in the world team.

Is this a collective operation on `SHMEM_TEAM_WORLD` or on a different team containing all of the PEs in `SHMEM_TEAM_WORLD`? E.g. is it valid for a user to perform another collective on `SHMEM_TEAM_WORLD` in parallel with a call to `shmem_malloc`?

**Comment by davidozog** [comment]
My understanding is that there is only one "world team", and only the world team corresponds to the the `SHMEM_TEAM_WORLD` handle.  A separate team having the same PEs as the world team could certainly do another collective concurrently  with `shmem_malloc`.  Is this issue regarding the "world team" verbiage?

**Comment by jdinan** [comment]
@davidozog This is my recollection as well, but IMHO the text we have now is not specific enough in this regard.

**Comment by naveen-rn** [comment]
@jdinan Can you close this one, if the issue is clarified?

**Comment by jdinan** [comment]
Yes, it's specified in Section 9.4:
> OpenSHMEM communication routines that do not accept a team handle argument operate on the world team, which may be accessed through the SHMEM_TEAM_WORLD handle.
