### ISSUE TITLE
Queries on shmem_sync support

### ISSUE THREAD

**Issue by naveen-rn** [openshmem-org/specification#501]
With OpenSHMEM-1.5, we have ```shmem_sync``` as the API name for both the deprecated active-set-based collective operations and C11-generic interface. With this support, the following simple code should be supported.

```c
#include <stdio.h>
#include <shmem.h>
 
static long psync[SHMEM_SYNC_SIZE];
 
int main(void) {
                for (int i = 0; i < SHMEM_SYNC_SIZE; i++) {
                                psync[i] = SHMEM_SYNC_VALUE;
                }
                shmem_init();
                shmem_team_sync(SHMEM_TEAM_WORLD);
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
                shmem_sync(0, 0, shmem_n_pes(), psync);
                shmem_sync(SHMEM_TEAM_WORLD);
#else
                shmem_sync(0, 0, shmem_n_pes(), psync);
#endif
                shmem_finalize();
                return 0;
}
```

1. I'm not sure how to support this in an implementation without breaking compatibility.
2. Having the ```shmem_sync``` name for both active-set API as well as C11-generic interface doesn't seem to work.

Based on my understanding:
1. Cray OpenSHMEMX doesn't support C11-generic interface. Hence, ```shmem_sync(team)``` is not supported.
2. It looks like SOS somehow supports both the interface - this needs verification.
3. OSHMEM supports only C11-generic interface. Meaning, when a non-C11 compiler is used - they could break compatibility where the active-set based ```shmem_sync``` might not be supported. This is based on understanding this commit (https://github.com/open-mpi/ompi/pull/9631)

It looks like we have an issue in the specification. Do we need a fix? Or we might be missing something in our implementation.

**Comment by jdinan** [comment]
@naveen-rn `int shmem_sync(shmem_team_t team)` exists *only* as a C11 generic binding. It's not a C binding, so your item (1) above is correct, Cray OpenSHMEMX shouldn't have this function. Below is how SOS implements the C11 binding:
```
#define SHMEM_C11_ARG0(first, ...) first
#define shmem_sync(...) \
    _Generic(SHMEM_C11_ARG0(__VA_ARGS__), \
        shmem_team_t: shmem_team_sync, \
        int: shmem_sync \
    )(__VA_ARGS__)
```

**Comment by jdinan** [comment]
OSHMEM must have support for the C bindings, because the C11 generic bindings are evaluated into a call to one of the C functions. Are you saying that OSHMEM's C11 bindings aren't conditional on compiler support and that OSHMEM requires a compiler that supports C11?

**Comment by ronawho** [comment]
We were able to implement this with an SOS-like generic selection that @jdinan suggested. I don't think there's a spec issue, but will let @naveen-rn confirm and close when he's back.

**Comment by jdinan** [comment]
Looks like this was resolved. @naveen-rn Please reopen if needed.
