### ISSUE TITLE
Update/Deprecate Active-set-based Language

### ISSUE THREAD

**Issue by kwaters4** [openshmem-org/specification#504]
`SHMEM_COLLECT/FCOLLECT`

**API description** The API Description should be rewritten, currently the old API language of the active-set-based collectives routines is interspersed with the new team based language leading to a confusing description of the API.

**Notes** The notes section should be updated to remove the deprecated reference to `PE_size`.

`SHMEM_BROADCAST` 

**API description** for the active-set-based broadcast needs to be be deprecated. This can be noted with marking the section as deprecated and a red line or removed.

**Return Values** within this section the "active-set-based" language also needs to be be marked as deprecated.

`SHMEM_ALLTOALL` 

**API description** The API Description should be rewritten, currently the old API language of the active-set-based collectives routines is interspersed with the new team based language leading to a confusing description of the API.

`SHMEM_REDUCTION`

**API description** The API Description should be rewritten, currently the old API language of the active-set-based collectives routines is interspersed with the new team based language leading to a confusing description of the API.

**Comment by jdinan** [comment]
Closed by #511
