### ISSUE TITLE
Remove/Update examples using deprecated library constants

### ISSUE THREAD

**Issue by kwaters4** [openshmem-org/specification#506]
Currently two examples still use the deprecated shmem library constants of `SHMEM_REDUCE_SYNC_SIZE` and `SHMEM_REDUCE_MIN_WRKDATA_SIZE`

The examples are located in the following files:

1. Within the Atomicity Guarantees located in `./example_code/amo_scenario_3.c`
2. The example for`SHMEM_CTX_DESTROY` located in `./example_code/shmem_ctx.c`

**Comment by jdinan** [comment]
@kwaters4 Do you still want to make this change for OpenSHMEM 1.6?

**Comment by kwaters4** [comment]
@jdinan Both active set based example updates were captured in the following merge requests:

https://github.com/openshmem-org/specification/pull/528 
https://github.com/openshmem-org/specification/pull/538/
