### ISSUE TITLE
Sessions backmatter typos

### ISSUE THREAD

**Issue by davidozog** [openshmem-org/specification#515]
The backmatter for sessions has a couple of typos:
https://github.com/openshmem-org/specification/pull/493#discussion_r1617377039

In the special ballot for #493, `shmem_session_start` was renamed to `shmem_ctx_session_start` and `shmem_session_stop` was renamed to `shmem_ctx_session_stop`, but I forgot to change this in the backmatter.

**Comment by kwaters4** [comment]
@davidozog Can this issue be closed? I believe the merge requested has been completed.

**Comment by davidozog** [comment]
> @davidozog Can this issue be closed? I believe the merge requested has been completed.

Yes!  Thanks for the heads up.
