### ISSUE TITLE
Vector synchronization APIs need some const attributes

### ISSUE THREAD

**Issue by stewartl318** [openshmem-org/specification#542]
# Problem Statement

Parameters which are only read but which are passed as pointers should be marked "const" so that the compiler can (a) enforce the read-only and (b) perhaps perform extra optimizations.

credit to Phillip Marshal for noticing this.

# Proposed Changes

Mark the "cmp_value" parameters of the vector synchronization APIs as const.

# Impact on Implementations

Implementations will have to add const to their .h and .c files.

# Impact on Users

none

# References and Pull Requests

**Comment by davidozog** [comment]
Closed by #543
