### ISSUE TITLE
Fixing Typos outside the 1.6 RC1 release PR

### ISSUE THREAD

**Issue by ahayashi** [openshmem-org/specification#545]
# Problem Statement
We have found the following typos that are outside the changes made in pull request #540.

# Proposed Changes

1. content/backmatter.tex ([L1185](https://github.com/openshmem-org/specification/pull/540/files#diff-5e2b564c9b77bdfefeb121fd2cf226fd6780e7dbf6b5dc8d7f84af24c16334e5R1185) in the updated version in #540)
https://github.com/openshmem-org/specification/blob/1d6f40e2cd9b1c71754a3f45d4bc124b9065c5cd/content/backmatter.tex#L1157
   * “readabilty” -> “readability”?

2. content/shmem_ctx_session_config_t.tex
https://github.com/openshmem-org/specification/blob/1d6f40e2cd9b1c71754a3f45d4bc124b9065c5cd/content/shmem_ctx_session_config_t.tex#L72
   * “occurence” -> “occurrence”?

3. content/shmem_ctx_session_start.tex
https://github.com/openshmem-org/specification/blob/1d6f40e2cd9b1c71754a3f45d4bc124b9065c5cd/content/shmem_ctx_session_start.tex#L109
   *  “implemenation” -> “implementation”?

4. content/shmem_team_config_t.tex
https://github.com/openshmem-org/specification/blob/1d6f40e2cd9b1c71754a3f45d4bc124b9065c5cd/content/shmem_team_config_t.tex#L30
   * "existance” -> “existence”?

5. content/shmem_reductions.tex ([L382](https://github.com/openshmem-org/specification/pull/540/files#diff-39d3fa0e023850c92f24f5e2cd8c7e5ce0eaed60cb5ed45a60e3dba23c59c656R382) in the updated version in #540)
https://github.com/openshmem-org/specification/blob/1d6f40e2cd9b1c71754a3f45d4bc124b9065c5cd/content/shmem_reductions.tex#L346
   * “intializes” -> “initializes”?

6. content/p2p_sync_intro.tex
https://github.com/openshmem-org/specification/blob/1d6f40e2cd9b1c71754a3f45d4bc124b9065c5cd/content/p2p_sync_intro.tex#L19
   * “implemementation” -> “implementation”?

7. example_code/shmem_reduce_example.c
https://github.com/openshmem-org/specification/blob/1d6f40e2cd9b1c71754a3f45d4bc124b9065c5cd/example_code/shmem_reduce_example.c#L38
   *  “occured” -> “occurred”?

# Impact on Implementations
N/A
# Impact on Users
N/A
# References and Pull Requests
#540

**Comment by ahayashi** [comment]
@jdinanI'm not sure if this is the right place to report these typos. Please feel free to close this and let me know if there is a better option. Thank you!

**Comment by jdinan** [comment]
Thanks! These have all been applied to #546
