### ISSUE TITLE
Inconsistent naming for (future) types

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#56]
What naming rules do we want to use for types that are now being introduced with PRs pending for v1.4? Examples: `type`, `type_t`, `struct type`

- #32 `shmem_cmp`
- #41 discussion that suggested possible addition of `shmem_lock` or equivalent.
- Contexts `shmem_ctx_t`

**Comment by nspark** [comment]
In general, I prefer types with the name style `name_t`, however, I went with `shmem_cmp` for the `SHMEM_CMP_*` enumeration constants in #32 because `stdatomic.h` uses the [`memory_order` enumerated type](http://en.cppreference.com/w/c/atomic/memory_order) (which, was the only enumerated type explicitly defined in the C standard that I saw on a quick search.).

If it caused anyone heartburn, I'd gladly switch to `shmem_cmp_t` (and would favor the `name_t` form in general).

**Comment by jdinan** [comment]
I think I prefer a standard naming scheme for all OpenSHMEM types.  Something like ```shmem_<type>_t``` seems reasonable and may also reduce the likelihood of a conflict with an application variable (e.g. named ```shmem_cmp```).

**Comment by swpoole** [comment]
+1

Best,
Steve (ADTSC)

**Comment by nspark** [comment]
I stumbled across [this POSIX reference about the `*_t` namespace](http://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xsh_chap02.html#tag_22_02_12) (emphasis mine):

> The requirement that additional types defined in this section end in "_t" was prompted by the problem of name space pollution. It is difficult to define a type (where that type is not one defined by POSIX.1-2008) in one header file and use it in another without adding symbols to the name space of the program. **To allow implementors to provide their own types, all conforming applications are *required to avoid symbols ending in "_t"*, which permits the implementor to provide additional types.** Because a major use of types is in the definition of structure members, which can (and in many cases must) be added to the structures defined in POSIX.1-2008, the need for additional types is compelling.

I sincerely doubt there's any realistic chance of a `shmem_*_t` namespace collision with a POSIX standard type, but I thought it interesting that POSIX requires avoiding that namespace entirely.

**Comment by jdinan** [comment]
It seems like we have settled on ```shmem_<type>_t```.  Can we close this issue?

**Comment by boehms** [comment]
Before we settle this I just want to add to the confusion;
From POSIX Standard (1003.1, Rationale (Informative)):

> B 2.12.1 The requirement that additional types defined in this section end in ‘‘_t’’ was prompted by the problem of name space pollution. It is difficult to define a type (where that type is not one defined by POSIX.1-2008) in one header file and use it in another without adding symbols to the name space of the program. To allow implementors to provide their own types, all conforming applications are required to avoid symbols ending in ‘‘_t’’, which permits the implementor to provide additional types. Because a major use of types is in the definition of structure members, which can (and in many cases must) be added to the structures defined in POSIX.1-2008, the need for additional types is compelling.

**Comment by nspark** [comment]
@boehms Beat you to it with https://github.com/openshmem-org/specification/issues/56#issuecomment-290077888! 😉

**Comment by boehms** [comment]
I noticed, just a little late 😄

**Comment by jdinan** [comment]
@nspark I stuck this in your section committee's column.  We can discuss this as an "open issue" at the committee meeting.

**Comment by jdinan** [comment]
An additional item for this ticket.  I chose ```long``` as the type for the ```flags``` argument to ```shmem_ctx_create```, mostly because we didn't have the fixed-size integer types in the specification at the time this proposal was drafted and there is precedent for using long in the older SHMEM routines.  Do we want to change this type to ```uint64_t```?

**Comment by nspark** [comment]
@jdinan Given that the exact-width integer types are _technically_ optional types under the C Standard, I'd favor not using them. (In practice, `uint64_t` is going to exist on pretty much any platform.)

I actually think it feels more UNIX/Linux/POSIX-y to use `int` than `long`.

**Comment by jdinan** [comment]
@nspark Sounds like a good rationale for sticking with what we have.  I personally prefer ```long``` to ```int``` since it represents a potentially larger bank of dip switches.

**Comment by nspark** [comment]
We're coming down to the "speak now or forever hold your peace" moment, people.

Any strong feelings (for or against) contravening POSIX and using the convention of `shmem_*_t` for types?

**Comment by jdinan** [comment]
Chair's choice.  As long as we're consistent, it's ok by me.  🎰

**Comment by jdinan** [comment]
@nspark If this issue is resolved, please close.  Otherwise, please update the milestone to 1.5.

**Comment by nspark** [comment]
`shmem_*_t` it is
