### ISSUE TITLE
Add return code for shmem_init()

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#70]
I'm currently LaTeX-less (at least before the next specification cutoff), and would like to submit a change that adds a return value to `shmem_init()` to indicate whether the call was successful or not.

The rationale, in case it is not clear, is for libraries that build upon OpenSHMEM to detect a failure to initialize the OpenSHMEM library and fail gracefully. For example, OSHMEM, Cray SHMEM, and Sandia OpenSHMEM all abort or seg-fault if the OpenSHMEM program was not launched with an appropriate launcher (e.g., oshrun, aprun, srun).

**Comment by nspark** [comment]
Here is a [PDF of the proposed changes to shmem_init()](https://github.com/openshmem-org/specification/files/987837/OpenSHMEM-1.4-ReturnShmemInit-Draft1.pdf).

**Comment by naveen-rn** [comment]
Should every PE return the same return value?

**Comment by nspark** [comment]
> Should every PE return the same return value?

If the library cannot be initialized, then I don't think there really is a consistent concept of the "PE" in terms of what is actually executing. That said, I expect that `shmem_init()` should succeed (return zero) for all PEs or fail (return non-zero) for all PEs. Anything in between seems like the library was not properly initialized.

This proposal intentionally does not specify exactly which non-zero value should be returned.

**Comment by jdinan** [comment]
Can we roll this in with ```shmem_init_thread``` rather than making a change to the existing API?

**Comment by nspark** [comment]
@jdinan I think it should be there too, but I'm not opposed to also changing `shmem_init()` because it should be a backwards-compatible change.

@manjugv Are you open to extending `shmem_init_thread()` in #43 with this change? If so, would you want / do you think you could make those changes before tomorrow's deadline?

**Comment by jdinan** [comment]
Sure, the change is invisible to existing applications that will be recompiled.  However, it's not backward compatible for tools, code that takes a pointer to this routine, or applications that are not recompiled.  If I'm a tool writer, I would need to support two versions of this function depending on which version of SHMEM is in use.  If anyone has a Fortran BIND(C) interface, it will break.  It also breaks ABI backward compatibility.

Given that we are adding a new routine where we can provide this new semantic and that anyone who wants this functionality has to edit their code, I don't think the benefit from this change outweighs the these potential negatives.

**Comment by nspark** [comment]
@jdinan Fair enough.

**Comment by manjugv** [comment]
@nspark @jdinan It makes sense to include this in #43 . I will incorporate the C changes, and exclude the Fortran changes (#43 does not introduce any Fortran interfaces).

**Comment by nspark** [comment]
@manjugv 👍

**Comment by manjugv** [comment]
I have included the changes here: 36b9d957f92d768a73d13c84511b4da084af54cf
Please let me know, if you have any comments.

**Comment by nspark** [comment]
Closed by #43
