### ISSUE TITLE
non-blocking RMA Operations

### ISSUE THREAD

**Issue by boehms** [openshmem-org/specification#72]
I am adding this as an Issue to open it up for discussion.

The non-blocking RMA routines provide operations for updating memory locations on a remote PE. All explicit RMA routines either return a handle to a request object if the input handle is set to NULL,
or will merge the request into the request object given to the function as a parameter.

### Rationale
Mergeable explicit request handles provide a way to group related RMA operations into a single request object. This approach enables the OpenSHMEM implementation to better allocate the available resources to different streams of RMA operations. Another advantage of request objects is the possibility to separate communication streams in an environment where a PE is running multiple threads. The introduction of shmem_request_wait will remove the need to call shmem_quiet to complete outstanding RMA operations. Using shmem_request_wait can enable a finer granularity of progressing RMA operations in the runtime. Furthermore, the status of request objects can be tracked using the newly introduced shmem_request_test API function and can be used to improve the overlap between communication and computation. 

There are two ways of creating request objects. The first is to pass a NULL handle into an explicit RMA function. The runtime will create the request object and return the handle. The second is to use the newly introduced shmem_request_alloc function. Using the explicit allocation method will provide means to pass hints to the runtime during request creation that can be used to optimize the communication further.

The paper [Evaluating OpenSHMEM Explicit Remote Memory Access Operations and Merged Requests](http://link.springer.com/chapter/10.1007/978-3-319-50995-2_2) discusses an experimental implementation of mergeable requests.

There is a ticket in redmine that is related to this work (see [Extension #113](http://openshmem.org/redmine/issues/113)).

### Proposed API
```
shmem_TYPE_put_nbe (TYPE *target, const TYPE *source, size_t nelems, int pe, void **request);
shmem_putSIZE_nbe  (TYPE *target, const TYPE *source, size_t nelems, int pe, void **request);
shmem_TYPE_get_nbe (TYPE *target, const TYPE *source, size_t nelems, int pe, void **request);
shmem_getSIZE_nbe  (TYPE *target, const TYPE *source, size_t nelems, int pe, void **request);

shmem_request_wait (void **request);
shmem_request_test (void **request);

shmem_request_alloc (shmem_request_params_t  params, void **request);
shmem_request_free (void **request);

shmem_merge_request (size_t count, void *request, void **requests);
```

**Comment by jeffhammond** [comment]
Why do you need a request alloc and free? (I did not read the paper.)

**Comment by naveen-rn** [comment]
I'm trying to understand whether there will be any performance impact on small data buffers (say less than 32K). Creating separate request handles for every RMA event will be useful for very large data sizes. But, for small data sizes, it looks like there would be unnecessary overheads.

**Comment by manjugv** [comment]
> jeffhammond commented 16 hours ago
> Why do you need a request alloc and free? (I did not read the paper.)

It is not necessary to use these interfaces to create request objects. However, if used, the user can provide various hints (params). One hint we explore here - merging of requests, i.e, the same request object is used for a group of related operations. When this request object is used, the library now knows that it is not a single operation rather it is a group of related operations. So, the library can then choose to allocate a separate set of network / other resources for each request object, and this can translate into performance advantages.

**Comment by boehms** [comment]
> naveen-rn commented 16 hours ago
> I'm trying to understand whether there will be any performance impact on small data buffers (say less than 32K). Creating separate request handles for every RMA event will be useful for very large data sizes. But, for small data sizes, it looks like there would be unnecessary overheads.

Yes, managing requests introduces overhead. To help with this problem there is the option to utilize a memory pool for request objects and recycle request objects when the requests are finished. This is what we did for our implementation.

**Comment by manjugv** [comment]
> I'm trying to understand whether there will be any performance impact on small data buffers (say less than 32K). Creating separate request handles for every RMA event will be useful for very large data sizes. But, for small data sizes, it looks like there would be unnecessary overheads.

It doesn’t necessarily translate to performance degradation. One can design the libraries such that the overhead is negligible. Most network libraries create and use a descriptor for a operation or a group of operation, even if it is not exposed to the upper layers (programming models such as OpenSHMEM). We piggy back information to these descriptors (in simplest case). So overhead is minimal. Also, the request objects can be created during init and assigned to the operation during invocation. We use these in our design. You can see in our experiments that the performance degradation is negligible. 

In fact, there is huge performance advantage ,particularly, when we combine this with merging of requests and multithreading. We see this already in our experiments, and we plan to publish these results very soon.

**Comment by manjugv** [comment]
Closing. As there is no plan to revive this. @boehms If you (or others) plan to work on this, please feel free to open.
