### ISSUE TITLE
Create FindOpenSHMEM for CMake

### ISSUE THREAD

**Issue by BryantLam** [openshmem-org/specification#75]
For CMake users out there, it would be great to have a FindOpenSHMEM.cmake package locator to help find platform/vendor-specific paths.

We can upstream it to the CMake repository once it's solidified. Note that recent CMake (~3.6) package files are transitioning to using imported targets which were introduced in CMake ~3.0, so that may end up being the minimum CMake version.

**Comment by jeffhammond** [comment]
What does this have to do with the spec? This is a fine thing to open
source in any number of places, but the spec repo is not one of them.

I hate CMake and will fight to the gates of hell and back before I'll see
those five letters appear in any standards document.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by BryantLam** [comment]
@jeffhammond I agree. Used this issue as a project tracker for community interests. Doesn't belong in the spec at all. Closing!
