### ISSUE TITLE
Alignment argument to shmem_align

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#76]
The ```shmem_align``` function does not place any requirements on the ```alignment``` argument.   ```posix_memalign``` has the following requirement: "The requested alignment must be a power of 2 at least as large as sizeof(void *)."  Should ```shmem_align``` have this same requirement?

**Comment by jdinan** [comment]
Linux has an additional requirement, that alignment be a multiple of ```sizeof(void*)```.

**Comment by nspark** [comment]
I think it's a good question to consider whether `shmem_align` needs refinement in specifying what constitutes valid values for both `size` and `alignment`, however, we may want to consider how POSIX and C11 differ.

C11's definition of `aligned_alloc` says:
> The value of `alignment` shall be a valid alignment supported by the implementation and the value of `size` shall be an integral multiple of alignment.

The [latest POSIX standard for `posix_memalign`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/posix_memalign.html) has a slightly different definition than what you posted:
> The value of alignment shall be a power of two multiple of `sizeof(void *)`.

To me, `aligned_alloc` seems less portable and more restrictive than `posix_memalign`. It may not be divergence in the strictest sense, but I'm not sure which of these restrictions we'd want to put on `shmem_align`.

**Comment by jdinan** [comment]
I'm not sure the posix_memalign text you quoted is any stronger.  If sizeof(void*) is a power of two, all powers of two greater than or equal to sizeof(void*) will be multiples of sizeof(void*).  Actually, this new text may be worse if there is ever a case where sizeof(void*) is not a power of two.

Another breadcrumb -- the Cray test ```sma1/align.c``` requires the implementation to round up the alignment argument to the next power of two.

**Comment by nspark** [comment]
I agree; I don't think the two `posix_memalign` restrictions are different unless `sizeof(void*)` is not a power of two. I simply wanted to point out the difference in the text itself, in case we wanted to choose one to adopt.

**Comment by hppritcha** [comment]
Just to push things along, we're doing cross testing of different OpenSHMEM implementations with different test suites - a fun thing to do.  If we want to have a standardized test suite, we need consensus on ```shmem_align```.  As it stands, the Mellanox test checks that the function returns an error if an alignment of 0 is supplied.  The Cray OpenSHMEM implementation fails this test.  SOS passes.
