### ISSUE TITLE
Does shmem_free(NULL) imply barrier?

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#77]

**Comment by naveen-rn** [comment]
I suppose there should be a barrier in this scenario, because there can be scenarios where some PEs at the end of shmem_malloc() might receive NULL.

**Comment by nspark** [comment]
For reference, we had some discussion on this topic in #38. Per @davidozog's changes:
> `shmem_free` calls a barrier on entry

This is an unconditioned statement on the behavior of `shmem_free`, so I think the answer to the title question is "yes".

For "SHMEM 2", I would be inclined to adopt less-prescriptive definitions for the memory management routine that would allow for `shmem_free(NULL)` not to require a barrier.

**Comment by jdinan** [comment]
Thanks, I'll close this for now.  I don't know that we should be overly worried about optimizing cases like ```shmem_free(NULL)```.  There's probably an argument that we should always do the barrier to avoid surprising users.
