### ISSUE TITLE
Clarify shmem_malloc(0)

### ISSUE THREAD

**Issue by jdinan** [openshmem-org/specification#78]
The behavior of shmem_malloc with zero size argument is currently undefined.

**Comment by nspark** [comment]
For reference, we had some discussion on this topic in #38.

**Comment by jdinan** [comment]
From #38, @nspark commented:

POSIX expands on the C Standard definition of `malloc()` [to say](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html):
>If the size of the space requested is 0, the behavior is implementation-defined: either a null pointer shall be returned, or the behavior shall be as if the size were some non-zero value, except that the behavior is undefined if the returned pointer is used to access an object.

**Comment by jdinan** [comment]
I proposed we adopt the following: ```shmem_malloc(0)``` returns NULL and, when the ```shmem_malloc``` routine returns NULL, it is not required to perform an implicit barrier.
