### ISSUE TITLE
Validating triplet arguments for active-set

### ISSUE THREAD

**Issue by naveen-rn** [openshmem-org/specification#79]
Queries on handling a corner case while forming active sets. Should we validate the logPE_stride value comparing against the PE_size?

I suppose the following triplet values is considered valid for forming an active set.
PE_start = 0; logPE_stride = 1; PE_size = 1
In the above example, the logPE_stride doesn't matter since the active set size is just 1. 

PE_start = 0; logPE_stride = 25; PE_size = 1
Is this a valid triplet value?

**Comment by jdinan** [comment]
Seems like you would want to check whether the index of the last PE in the active set is valid.  IIUC, both of the above would clear that check.

**Comment by jeffhammond** [comment]
Checking for valid usage is a quality-of-implementation issue.  Invalid usage is erroneous usage - ideally the implementation aborts with a useful error message, but the implementation should be allowed by the standard to corrupt all of application memory and crash with no error message.  Market economics will take care of the latter 😉 

Whether or not a triplet is valid should be roughly equivalent to the following: 
```c
  for ( int i=PE_start ; i<PE_size ; i+=(1<<logPE_stride) ) {
    assert( 1 == shmem_pe_accessible(i) );
  }
```

Given that bitshifts can lead to [UB](https://stackoverflow.com/questions/3784996/why-does-left-shift-operation-invoke-undefined-behaviour-when-the-left-side-oper), the user should be prohibited from providing any `logPE_stride` value that may lead to this (although implementations should also guard against it).
