### ISSUE TITLE
Deprecated shmem_TYPE_wait routines

### ISSUE THREAD

**Issue by jamesaross** [openshmem-org/specification#84]
We've merged the overhaul of the point-to-point API #32, which deprecated `shmem_TYPE_wait` routines, specifically, `shmem_wait`, `shmem_short_wait`, `shmem_int_wait`, `shmem_long_wait`, and `shmem_longlong_wait`. And #32 also expanded the type support for the point-to-point routines, `shmem_TYPE_wait_until` and added `shmem_TYPE_test`.

The documentation for [shmem_wait](https://github.com/openshmem-org/specification/blob/osh_spec_next/content/shmem_wait.tex) states that the deprecated `shmem_TYPE_wait` routines support the same (newly expanded) point-to-point types.  So did we expand support for new deprecated routines?  Specifically, must an implementation of OpenSHMEM 1.4 support the following?
```
shmem_ushort_wait
shmem_uint_wait
shmem_ulong_wait
shmem_ulonglong_wait
shmem_int32_wait
shmem_int64_wait
shmem_uint32_wait
shmem_uint64_wait
shmem_size_wait
shmem_ptrdiff_wait
```

**Comment by BryantLam** [comment]
As written, the answer is yes. I could see the rationale being less confusing for users if the C11 API remained consistent despite deprecation, but it could also just be an oversight.

**Comment by nspark** [comment]
@jamesaross Good point. I'll take a pass at revising the point-to-point synchronization text to reflect that the expanded types should _only_ apply to `shmem_TYPE_wait_until` and `shmem_TYPE_test`.
