### ISSUE TITLE
Clarify behavior of SHMEM_SYMMETRIC_SIZE and other env-vars

### ISSUE THREAD

**Issue by nspark** [openshmem-org/specification#98]
The "Environment Variables" section in OpenSHMEM 1.3 says:
> The OpenSHMEM specification provides a set of environment variables that allows users to configure the OpenSHMEM implementation, and receive information about the implementation. The implementations of the specification are free to define additional variables. [...]

Currently, the specification is not explicit whether `SHMEM_SYMMETRIC_SIZE` is an input (configuration variable), an output (an informational variable), or both. While it is consistently handled as an input, it is inconsistently handled as an output across implementations, especially if an additional, related environment variable is provided by an implementation.

For example:
* OSHMEM will set `SMA_SYMMETRIC_SIZE` in `shmem_init` if its (non-standard) alternate env-var `SHMEM_SYMMETRIC_HEAP_SIZE` is set
* Cray SHMEM leaves it unset if the heap size is specified via `XT_SYMMETRIC_HEAP_SIZE`

Points for potential clarification:
* Should we clarify the input/output nature of all the `SHMEM_*` environment variables?
* Should it be made explicit that output environment variables may only be queried _after_ the call to `shmem_init`?
* Should `SHMEM_SYMMETRIC_SIZE` be set during `shmem_init` to whatever the heap size actually is, assuming the implementation uses a fixed-size symmetric heap?

(Moved precedence of `SMA_*` vs. `SHMEM_*` env-vars to #111.)

**Comment by nspark** [comment]
@RaymondMichael Since we deprecated the `SMA_*` environment variables and added the `SHMEM_*` ones for OpenSHMEM 1.4, I think the clarification on precedence is material for your section committee. This issue raises a number of related items, though they may not all be relevant for a section committee. If it make sense, we can split this into two issues: precedence and everything else.

**Comment by RaymondMichael** [comment]
I agree that it makes sense to split this into two issues.

**Comment by nspark** [comment]
@RaymondMichael Done!

**Comment by jdinan** [comment]
```getenv``` is a less-than-ideal interface for receiving output from the library.  The only variable that makes sense as an output is ```SHMEM_SYMMETRIC_SIZE``` and sticking a value there is a whole can of worms (see #90).  We also want to update this variable in the future to accept SI modifiers (e.g. "1G"), which will make it more challenging for users to parse (should be an issue for this somewhere on RedMine, but most implementations support this already).  Specifying these to also be outputs seems to me beyond the scope of what we would want to tackle at the chapter committee level.

**Comment by nspark** [comment]
I haven't tried every implementation to which I have access, but with OSHMEM, one gets:
```bash
$ SMA_INFO=1 oshrun -n 4 ./a.out
----------------------------------------------------------------------------------
SMA_VERSION - print the library version at start-up
SMA_INFO - print helpful text about all these environment variables
SMA_SYMMETRIC_SIZE - number of bytes to allocate for symmetric heap
SMA_DEBUG - enable debugging messages
----------------------------------------------------------------------------------
```

So... no. At least, the specification is sufficiently ambiguous about what setting `SHMEM_INFO` should do that it can be interpereted as throwing `--help` for the OpenSHMEM library.

**Comment by jdinan** [comment]
Oh, yeah, that's totally lame.  We should fix this in the specification.

But, I'm still not sure why you need ```SHMEM_SYMMETRIC_SIZE``` to be updated by ```shmem_init```?  Don't you actually want to print the value that the user set?

**Comment by nspark** [comment]
Yes, I want `SHMEM_SYMMETRIC_SIZE` to provide the value that the user set, but the user may have set any one (or more than one!) of:
- `SHMEM_SYMMETRIC_SIZE`
- `SMA_SYMMETRIC_SIZE` (see #111)
- `SHMEM_SYMMETRIC_HEAP_SIZE` with OSHMEM
- `XT_SYMMETRIC_HEAP_SIZE` with Cray SHMEM

We even say that:

> The implementations of the specification are free to define additional variables.

so it seems perfectly valid that OSHMEM and Cray SHMEM have their own ways of setting the heap size. I'd rather not check all _N_ different env-vars (depending on the implementation I'm using).

**Comment by jdinan** [comment]
That's obnoxious, but isn't the point of having a specification that all implementations should converge on ```SHMEM_SYMMETRIC_SIZE``` (which is required for compliance)?  Wouldn't a better fix be to remove the SMA_ prefixed env vars in 1.5?

FWIW, the OSHMEM-specific constants may go away, see https://github.com/open-mpi/ompi/issues/4098.  The spec allows implementations to define their own env vars; however, implementations are still forbidden by Section 5 from including implementation-specific constants in the header file:

> The OpenSHMEM header files for C and Fortran must contain only the interfaces and constant names defined in this specification.

**Comment by jeffhammond** [comment]
> Yes, I want SHMEM_SYMMETRIC_SIZE to provide the value that the user set,
> but the user may have set any one (or more than one!) of:
>
>    - SHMEM_SYMMETRIC_SIZE
>    - SMA_SYMMETRIC_SIZE (see #111
>    <https://github.com/openshmem-org/specification/issues/111>)
>    - SHMEM_SYMMETRIC_HEAP_SIZE with OSHMEM
>    - XT_SYMMETRIC_HEAP_SIZE with Cray SHMEM
>
>
I know a guy whose implementation checks every variant of this env var
that's documented online just to be safe 😁

https://github.com/jeffhammond/oshmpi/commit/eadc013d47f1b13bfc408a093e1cd1b273733d9f


-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by nspark** [comment]
Absent any objections, I'm removing this one from the 1.4 project. We can discuss this further for 1.5.

**Comment by BryantLam** [comment]
One user has suggested taking the maximum value of vendor-specified symmetric-size environment variables instead of specifying a precedence order.

**Comment by manjugv** [comment]
Discussed during FRM : The issue might be tricky to standardize. It was decided to close for now.
