### ISSUE TITLE
Glossary proposal

### ISSUE THREAD

**Issue by j-mike-culhane** [openshmem-org/specification#99]
Myself and other members of the OpenSHMEM community are in favor of adding a glossary to the 1.4 spec. Assuming that one is added, could I get some feedback as to what we'd like to see in said glossary?

**Comment by swpoole** [comment]
I am very much in favor of a glossary. I would not want it to replace the inline definitions we have, but it could certainly be used to augment what we have. I might start by using all of the definitions we currently have in italics. Could we use the MPI spec as an example?

**Comment by jdinan** [comment]
MPI doesn't have a glossary (a quick check of other specifications I have handy, OpenMP, UPC, etc also isn't turning up any that contain a glossary).  All of these specs have an index, which references the location in the document were a given term is defined.  I think I would prefer this approach over maintaining the definition in two places.

**Comment by manjugv** [comment]
@jdinan  [POSIX standard](http://pubs.opengroup.org/onlinepubs/9699919799/) has a definitions section, I think @j-mike-culhane @swpoole  would like to see something similar. 

I find having a section (where I can define the terms) as useful. Our specification has many undefined terms, we need a place where we can define them.

**Comment by manjugv** [comment]
Having “Semantic Terms” section (as in MPI) along with an Index section might be another solution.

**Comment by jdinan** [comment]
Either of these solutions would be reasonable.  As long as we define terms in normative sections of the document and define each term only once in the document, I'm happy.

**Comment by swpoole** [comment]
Either works for me. @j-mike-culhane can you look at both and see which might be the best longer term? A quick example of each might be useful to see.

**Comment by jdinan** [comment]
@nspark Please close this issue if you feel that your terms section addresses it.

**Comment by jdinan** [comment]
@nspark Is this issue resolved for OpenSHMEM 1.5? If you'd like to keep it for OpenSHMEM 1.6, please adjust milestone, project, and labels.

**Comment by BryantLam** [comment]
Resolved by https://github.com/BryantLam/openshmem-specification/pull/22.
